### ISSUE TITLE
Icon not visible in Activity Bar, nothing appears to be working

### ISSUE THREAD

**Issue by benlesh** [Microsoft/vscode-pull-request-github#1045]
- Extension version: `0.4.0`
- VSCode Version:
```
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.20-1rodete1-amd64
```
- OS: Linux

Steps to Reproduce:

1. Install the extension
2. Log into Github (everything appears to be successful)
3. Restart Code, nothing shows up. :man_shrugging: 

![Screenshot from 2019-03-12 15-38-41](https://user-images.githubusercontent.com/1540597/54240970-f119bb00-44dc-11e9-834a-5119344a150b.png)

**Comment by RMacfarlane** [comment]
For version 0.4.0 of the extension, the GitHub Pull Requests tree should be added to the existing Source Control Viewlet. The tree is only added when the extension detects that there are remotes associated with GitHub. What's the output of running `git remote -v` in the folder you have open? Can you also check to see what's in the Output panel when you select `GitHub Pull Requests` from the dropdown?

**Comment by akbyrd** [comment]
I'm having a similar problem. Selecting `Show GitHub Pull Requests` opens the Explorer (not the SCM section). There's no new section that I can find.

After messing with it I realized the extension is choking because my employer uses a GitHub Enterprise with a self-signed certificate.

It's a really bad first experience to have the extension fail silently and require the user to go spelunking to figure out why. I would expect the viewlet to still be created so I at least know the extension is working and I don't go disabling a bunch of other extensions to see if they're interfering. I'd also expect some sort of useful error message when the extension can't communicate with server.

Before setting an an access token and host the log just said "No GitHub remotes found", rather than saying *why*. My remote is named as expected. Once I set the host the log said "Authentication> Token is no longer valid for host", again rather than describing the actual issue with certs. Now that I've installed the certs on my machine I can get to the website to authorize VS Code for access to GitHub, but  now that page is just stalling when I click authorize. Arg.

**Comment by carlocardella** [comment]
I use a multi-root workspace with repos both from Azure DevOps and Github: the viewlet is not loaded at startup and it's still not visible even if I select one of the Github repos.

This is what I see in the extension Output panel when a Github repo is selected:

```
[Info] C:\Users\carlo\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\carlo\.ssh\config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch master
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch master
```

**Comment by e-dergachev** [comment]
i have the same problem, i have just installed it and it it is neither visible in the source control viewlet nor it has its own icon on the activity bar and i have absolutely no idea how to make it work, re-starting vs code and re-installing the extention doesn't help
![github pull request](https://user-images.githubusercontent.com/49060938/55866471-c6964d00-5bc3-11e9-977f-0385079ae386.png)

**Comment by RMacfarlane** [comment]
@carlocardella @e-dergachev With version 0.6.0 of the extension, can you go to settings and change `githubPullRequests.logLevel` to `debug`, and then report what is printed in the Output panel for GitHub Pull Requests?

**Comment by e-dergachev** [comment]
sure
![vs code github pull requests debug](https://user-images.githubusercontent.com/49060938/56079047-2c880c00-5e32-11e9-8756-8bcdaf945273.png)

**Comment by carlocardella** [comment]
In this multi-folder workspace I have 8 repos on Azure DevOps and one repo on Github

![image](https://user-images.githubusercontent.com/5784415/56096810-a9060380-5ea1-11e9-80d5-6a2387971281.png)

**Comment by RMacfarlane** [comment]
@e-dergachev Can you check that your "Git: Enabled" setting is checked? And just to confirm, the folder you have open is one that either had git initialized with `git init` or `git clone`?

@carlocardella What version of VSCode are you using? With 1.33, there is a bug where selection changes are not being fired when changing the folder in the SCM viewlet. https://github.com/Microsoft/vscode-pull-request-github/issues/1111
