### ISSUE TITLE
Quick Open shows files twice

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-pull-request-github#1099]
- Extension version: 0.5.1
- VSCode Version: 1.33.0
- OS: macOS

Steps to Reproduce:

1. Checkout a branch
2. Open the diff view from Files, then open the real file

![image](https://user-images.githubusercontent.com/4033249/55449545-c7eec680-5580-11e9-95ed-8ef3174fffbc.png)

**Comment by RMacfarlane** [comment]
The right hand side of the diff editor that we open is a document that has a URI matching a local file, except with a query at the end of it. So then in the quickpick two version of the file are shown, the normal local file, and our version that has a query. @rebornix and I discussed potential fixes to this a while ago, it requires some work to get right.

If we drop the query from document on the right hand side of the diff editor, we would need to
- change the comment controller so that comments for `file` scheme documents only include comments on existing lines and additions. Currently I believe comments on deletions are also shown closest to where the deletion was
- For `review` scheme documents (i.e. the left side of the diff editor), only show comments that are on deleted lines. Currently we show comments on existing lines that are not additions on the left
- Handle collapsing behavior appropriately. This is the thorniest part of the fix. We only have one set of comments for `file` scheme documents, so the collapse state is shared when you open a diff editor vs opening the local file. Ideally we want to expand comments by default when looking at a diff editor and collapse when looking at a local file. We need to be able to detect whether the visible editor is a diff editor or not, by looking at the visible text editor array we should be able to approximate this by seeing if the editor in the previous position of the array matches what we expect the URI of the left hand editor would be. Then we would need to update the collapsed state of all of the relevant `file` scheme document comments
