### ISSUE TITLE
Allow custom pull request filters

### ISSUE THREAD

**Issue by szszoke** [microsoft/vscode-pull-request-github#1106]
On GitHub, we have the ability to filter pull requests, and reuse the same filter by storing the URL in a bookmark.
![image](https://user-images.githubusercontent.com/2766129/55618695-6fdddd00-5797-11e9-9877-3c14dfe99775.png)

Allow adding our own categories here :point_down: with custom filters using the pre-existing GitHub search qualifiers.
![image](https://user-images.githubusercontent.com/2766129/55618784-a0be1200-5797-11e9-99fd-db360a3aa65b.png)

[More info on the search qualifiers](https://help.github.com/en/articles/searching-issues-and-pull-requests)

**Comment by RMacfarlane** [comment]
I love this idea! I made a prototype of how this could work:
![custom_categories](https://user-images.githubusercontent.com/3672607/58119981-17349900-7bb9-11e9-9e94-d6019e6c3c7c.gif)

On GitHub.com, it's nice to be able to use the dropdowns to help construct the query. I'm not sure what we could do here to help with query writing, validation seems challenging since my understanding of the query language is that anything not interpreted as a search qualifier would just be used as a keyword.

Other things we could have:
- "Edit", which allows you to pick a category, first modify the title, then modify the query
- Be able to view the query in the tree?
- Have an inline action on a category to either view or modify the query
