### ISSUE TITLE
Show notifications when there are changes to pull requests

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/vscode-pull-request-github#1128]
**Background:**
When working in VS Code, it is impossible today to know when there are changes to Pull Requests that you care about. Typically users must rely on email notifications or notifications on the GitHub website for that detail. 

**Solution:**
To reduce context switching between GitHub.com and email, it would be great to provide notifications in the Pull Requests extension to call attention to when there are changes to be aware of.

Examples of notifications can include:
- When someone comments on your PR
- When someone leaves a review on your PR
- When you are requested to review a PR
- When there are changes to PRs for a repo you watch
- When new PRs are created

**Comment by richardgazdik** [comment]
Any chance to get this feature soon? I really like how the GH iOS app works (which already sends push notifications of recent PR review requests) but it would make total sense to get notifications in the code editor instead of 3rd party apps. I really like the idea in one of the already closed issues to show the PR review requests of open PRs in a badge counter like this:

<img width="39" alt="CleanShot 2021-08-30 at 09 54 42@2x" src="https://user-images.githubusercontent.com/851261/131305702-4738dac8-f4aa-40d8-93ca-8783c68fcf5b.png">

It would be a super simple and straightforward solution / first version of this request.

**Comment by richardgazdik** [comment]
Hi @alexr00 ! Is there any chance that this request gets implemented in some way? It would a huge improvement to get PR review notifications directly in VSCode. Email is too cumbersome, the Slack plugin wants to solve too many GH-related notification issues at once, the iOS app is, well, the iOS app and it's harder to review code on a smaller screen.

**Comment by alexr00** [comment]
It's a good feature request, but no work is currently planned for it.

**Comment by Russkoubrothers** [comment]
need it too!!

**Comment by benibenj** [comment]
Currently in pre-release with the `githubPullRequests.notifications` setting: #3748
