### ISSUE TITLE
Cannot find example of configuring multiple remotes in documentation

### ISSUE THREAD

**Issue by jknapp25** [microsoft/vscode-pull-request-github#1143]
- Extension version: 0.6.0
- VSCode Version: 1.33.1
- OS: Windows _NT x64 6.1.7601

Steps to Reproduce:

1. Go to official extension documentation -> https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
2. Scroll down to #6 in the "Getting Started" steps, and notice it mentions configuring githubPullRequests.remotes, but it doesn't show an example of that configuration

Not knowing what that looks like, makes it so that I do not know how to configure multiple remotes for my ultimate goal of seeing open PR's for multiple repositories.

**Comment by RMacfarlane** [comment]
Hey @jknapp25, I'll update some of the documentation so that this is clearer.

The `githubPullRequests.remotes` setting is an array of remote names, so something like
`"githubPullRequests.remotes": ["origin", "fork"]` would be a valid configuration, or leaving it null to have the default behavior of searching for "origin" and "upstream".

If you have a workspace with multiple folders open, you can select one of them in the source control viewlet:
![Screen Shot 2019-05-06 at 1 33 49 PM](https://user-images.githubusercontent.com/3672607/57253479-abbcca00-7003-11e9-9c80-9ec61baa49aa.png)

This should cause the PR tree to refresh with PRs for that repository. We have an open feature request for making this UI clearer: https://github.com/Microsoft/vscode-pull-request-github/issues/1116

**Comment by jknapp25** [comment]
@RMacfarlane after selecting the other repo in my Source Control Providers list, the list of PR's in the extension does not update to the PR's for the selected repo. Is this a bug?

**Comment by RMacfarlane** [comment]
For the first point, can you share what the format of the urls for "origin" and "server" are with `git remote -v`? In the newest version of the extension, the icon should always be shown, but previously it would only bet shown if a remote pointing to GitHub was detected. So maybe we're having an issue parsing those urls.

The second point sounds like a bug, could you open another issue for that after testing with version 0.7.0 of the extension?

For the third point, is this https://github.com/microsoft/vscode-pull-request-github/issues/436?

**Comment by jknapp25** [comment]
_Format of both URL's:_
https://github.com/team-name/repo-name.git

_Testing with 0.7.0:_
How do I test with this version? In VSCode there is no update option, and it shows my extension is at 0.6.0

_Lastly:_
Yes, it does look like the same issue as #436

**Comment by RMacfarlane** [comment]
Ah, testing with 0.7.0 requires the latest version of VS Code, 1.34.0

**Comment by jknapp25** [comment]
Tested with 0.7.0, looks like it works now!
I think all that's left to be resolved is #436 now.

Thank you!
