### ISSUE TITLE
Consider renaming the extension

### ISSUE THREAD

**Issue by smashwilson** [microsoft/vscode-pull-request-github#1182]
The current extension name is fairly constraining: "GitHub Pull Requests."  I think, ultimately, we'd like to have the freedom to implement non-pull-request-related functionality - issue management, repository discovery and creation, something with projects or GitHub Actions maybe. How would everyone feel about renaming this repository and extension to be more general?

Note that there is already a "GitHub" extension on the Marketplace, but its README [has a note directing users to install this one instead](https://github.com/KnisterPeter/vscode-github).

One alternative would be to create several distinct extensions ("GitHub Repositories", "GitHub Issues") but I feel like that would interfere with discoverability and not provide much benefit. I'm not sure why someone would want to install repository management but not the pull request features, for example. Another would be to leave the name as it is and grow the scope regardless, which feels somewhat misleading.

* I see that VSCode extensions have a distinct name and ID. Will we cause any problems if we collide in name but not ID? Will we cause more confusion than it's worth if there are two extensions called "GitHub"? Are there any other names we should use instead?
* How difficult mechanically is renaming an extension in the Marketplace? Is there a way to accomplish this without losing reviews, ratings, and download counts? Will existing users be upgraded to the renamed extension seamlessly?

cc @queerviolet @kuychaco @vanessayuenn @RMacfarlane @rebornix for comments, thoughts, and feedback.

**Comment by kuychaco** [comment]
Yessss 💯

> Will we cause more confusion than it's worth if there are two extensions called "GitHub"?

Perhaps the existing "GitHub" extension author would be willing/happy to cede the name to us. He's already suggesting that folks use this extension instead.

**Comment by kuychaco** [comment]
Additionally, I agree that distinct extensions would interfere with discoverability. Furthermore, it would create unnecessary friction and complexity for both our users and developers, hindering progress toward getting features into the hands of users.

And I also agree that leaving the name as-is would be misleading and cause some confusion. 

Best case scenario in my mind -- there is one "GitHub" extension, and it is this one.

**Comment by meaghanlewis** [comment]
@smashwilson thanks for starting this conversation. I am in total agreement that we rename the extension from "GitHub Pull Request" to "GitHub".  I don't think we should just limit ourselves to Pull Request functionality when there are a wealth of other GitHub features that we can bring into the extension to create a richer experience. 

I'm not sure about the technical limitations of this, and need someone else (@RMacfarlane, @rebornix) to chime in there. 

If it is pretty straightforward to rename the extension, I am happy to reach out to the author, `KnisterPeter`, to see if he's up for us taking over the "GitHub" extension name. Alternatively, we could follow a similar approach as the VS extension and name it "GitHub Extension for VS Code".

**Comment by smashwilson** [comment]
You know, even though I'm usually one to prefer brevity, I do like how Official-Sounding "GitHub Extension for VS Code" sounds. 🤔 Granted, every word but "GitHub" _is_ self-evident by the places you're likely to discover it (i.e. the VS Code extension marketplace)...

**Comment by RMacfarlane** [comment]
What about having a GitHub extension pack that bundles together a number of GitHub extensions? Then users could either install that and get a complete GitHub feature set, or pick and choose what integrations they want. One monolithic extension could feel bloated.

**Comment by rebornix** [comment]
It seems we are discussing two items here in this issue: 1. if we should extend this extension to be a generic GitHub extension, and 2. if we want to do that, how difficult to do the migration. I'll suggest we focus on the first one here.

At this point GitHub Pull Request is the right name for this extension. It supports pull request browsing and code review but it doesn't manage github repositories (like GitHub Desktop), or issues/actions/wikis/etc. The viewlet (I called it tree view on Tuesday but viewlet is the name we use in VS Code) is already bloated as it has multiple categories/queries for filtering pull requests and it will also changes in local pr if users are reviewing.

Besides, we don't have a good answer where should new features fit into VS Code UI yet, for example, should we have a dedicated viewlet for GitHub issues or actions? Or probably we can use a web view for that? IMO we may do some experiments and even go back and forth, it may confuse existing users who currently only reviews pull requests in VS Code.

I prefer the approach @RMacfarlane recommended, that we can have a GitHub extension pack and every individual extension serves its own purpose. If we go this route, we may need to change the extension icon to something like below

![GHPR](https://user-images.githubusercontent.com/876920/58651173-6bc8ca00-82c5-11e9-873c-3c84ebd97a1c.png)

**Comment by smashwilson** [comment]
> What about having a GitHub extension pack that bundles together a number of GitHub extensions? 

Oh! I wasn't aware that this was a possibility. I'm 👍 on going that route. ([Here are the docs](https://code.visualstudio.com/api/references/extension-manifest#extension-packs) to save the others a Google :wink:)

**Comment by kuychaco** [comment]
Cool, the GitHub extension pack route sounds promising! I have a couple questions to consider, mainly around getting a full sense of the friction and complexity that this path might involve.

Say we publish a new extension and add it to the pack. What would users need to do, if anything, to get the new extension installed? I'm assuming/hoping the extension pack will automatically upgrade (would love to verify this). If not, then using an extension pack could introduce unnecessary friction/complexity for our users.

What tradeoffs would we be making in terms of adding friction/complexity to our development process? Having all of the GitHub integration code in one repo seems like it would give us maximum dexterity. If we go with the modular approach, we'd want to think about how to extract and share functionality that all extensions would need (authentication, user identity, etc). And some extensions might need access to the same information (for example, the issues extension and PR extension would both want access to a list of mentionable users) or share components (assignees and labels for issues and PRs).

A modular approach is great for encapsulation and separation of concerns, but less great if there's significant interdependency or if you’re fixing bugs or making changes that require first fixing a shared dependency. 

We can certainly tolerate increased friction and complexity in the development process. I'd simply like to wrap our heads around the tradeoffs involved as much as reasonably possible before making a decision.

**Comment by kuychaco** [comment]
### Discussion summary from today's sync-up on this topic:

Currently our extension is called "GitHub Pull Requests" and only has pull request features.

It's just a matter of time until we will want to support other basic GitHub features like viewing issues in the editor, or creating a repository. These are non-PR features, but still core GitHub features that users would reasonable expect and want to use alongside PR features. Separating them out into other extensions would introduce complexity and friction without clear justification from a UX standpoint. 

On the other hand, more "stand-alone" features like project boards and actions seem like decent candidates for separate extensions. Many GitHub users don't use these features. Depending on the level of coupling and impact on bundle size, it might still make sense to include these in the core extension. We'll want to consider things on a case-by-case basis.

We talked about a philosophy of breaking things out when it makes sense. That is, waiting until we have a clear and compelling use case rather than preemptively doing so.

**With regards to naming and extension pack usage, these are two separate but related decisions.**

The driving force for renaming the current extension to a more general name like "GitHub" is to 

1. improve the current extension discovery process (search "GitHub", find a third party extension, hopefully see the note at the top of the readme saying to install "GitHub Pull Requests" instead)
2. widen the extension's scope and accommodate features pertaining to issues, repositories, etc

According to the [extension pack documentation](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup#_why-would-i-want-to-create-an-extension-pack), the driving force for using an extension pack is to bundle extensions, so users can easily disable and enable individual extensions. 

In our case, some users may not use GitHub projects or actions. The question is, would they care enough to want to disable or uninstall the code that implements these features?

Or perhaps from the developers perspective, would we want to implement these in a separate extension in order to minimize complexity and bloat in our core package?

If we decide the answer to either of these questions is yes, then it makes sense to discuss creating an extension pack. Which is simply a package that has other packages listed as dependencies. Users that install our extension pack will get all new packages that we add to it, and can choose to disable packages as they wish.

We also discussed practical limitations... We can rename the extension, however changing the extension ID `github.vscode-pull-request-github` could be a pain if other extensions reference ours by ID. Is there an easy way to get a sense of how many packages would be affected by this? If it's a small enough number of extensions we can submit PRs for the renames to make the transition easier for extension authors.

I think that summarizes what was discussed. 

Now I'll shift gears and share some personal thoughts I've fleshed out in writing this summary...

______________________________________________

### Let's consider all of this through the lens of discoverability

One of our main priorities is to get features into the hands of users. If we can't do this effectively, then we can't have the impact we want. We want to simplify discoverability and minimize friction for users accessing our new features, and very intentionally introduce friction only when there is a clear and compelling reason.

My 2 cents is that the simplest discovery process with the least amount of friction would be to have a single package published by GitHub called "GitHub". When a user types "GitHub" in the extensions marketplace it's obvious which package to install and they need not choose from a collection of packages that implement different features, or some extension pack that installs them all. 

Currently dozens of extensions come up when you type "GitHub", only one of which is owned by GitHub. Let's imagine that KnisterPeter has kindly ceded the name "GitHub" to us, so the top result is "GitHub" by GitHub. There's simplicity and minimal cognitive overhead in having a single clear choice.

<img width="495" alt="Extension__GitHub_—_Untitled__Workspace_" src="https://user-images.githubusercontent.com/7910250/58831270-2ed04080-8601-11e9-919f-f9b8925b3ecf.png">

Now imagine we decide to implement separate "GitHub Actions" and "GitHub Project" extensions (note that there is already a "GitHub Actions" extension)... A new user wanting our features would have to sift through the many "GitHub" results and decide what extensions to install. _Hmm do I install this "GitHub core features" extension, or this "GitHub extension pack"? It looks like there are two packages for "GitHub Actions", which do I choose? Oh, probably the one that's by GitHub... But I haven't used Actions yet, so maybe I don't need it... But who knows, maybe I will! Oh, I guess the extension pack has it bundled. So maybe I'll just install that..."_

In addition to additional cognitive overhead when installing our extension(s), we risk having our newly-released features fall through the cracks. If users opt to install individual extensions instead of the extension pack, then new features we release as separate extensions bundled in the extension pack will never reach their finger tips. Thus limiting our impact and leading to missed opportunities.

Sidenote -- funnily enough, looking at that screenshot I just realized that our "GitHub Pull Requests" extension is listed as uninstalled for me. Yet clearly the extension is installed for me based on the tree view icon. Having multiple GitHub extensions has confused even me! 
___________________________________________________________________________

### Where to go from here...

We discussed a lot of options and tradeoffs and in service of grounding/focusing our conversation and walking a linear path towards a solution together, I'm going to throw something out as a starting point for us to move forward from. To be clear, I'm not saying that I think this is the final decision we should make. Just a launching point for further discussion.

Priority: Getting features into users' hands (package discoverability and new feature discoverability)
Solution proposal: Have a single extension with all GitHub features we choose to support
Drawbacks from a users' standpoint: Disk space limitations. Increased installation/load time.
Drawbacks from developers' standpoint: Increased code complexity (though I suppose we can still develop in separate modules as we see fit...)

@meaghanlewis @queerviolet @rebornix @RMacfarlane @smashwilson @StanleyGoldman please feel free to fill in things I might have missed, or share your thoughts on where to go from here 💭. For new solution proposals, please explicitly state the priority that is driving the proposal, and the tradeoffs involved.

**Comment by meaghanlewis** [comment]
@kuychaco thanks for the thorough summary about our discussion about this. 

>Priority: Getting features into users' hands (package discoverability and new feature discoverability)

I totally agree that getting features into users' hands is a priority. It's also important that they like the features we build and use what we build.

>Solution proposal: Have a single extension with all GitHub features we choose to support

It seems this is where we are split. Half of us are interested in the extension pack route and half of us are interested in having a single extension with all the GitHub features we want to build.

With the extension pack, the main drawback from a user's standpoint I see is discoverability since there are already so many GitHub related extensions. 

From a developer's standpoint I think that there will still be increased code complexity-- especially when we are trying to figure out the best way to share code between extensions. I know one point that came up last week was in regards to authentication and how we will share authentication or a connection between the extensions.

**Comment by meaghanlewis** [comment]
It appears that discussion has slowed down in this issue so I propose we extend next week's sync by 30 minutes to discuss the pros and cons of each solution and then come to a shared agreement about how we want to move forward.

**Comment by RMacfarlane** [comment]
Closing this issue since extending the functionality of this extension to other GitHub uses is not in scope for the foreseeable future
