### ISSUE TITLE
Autocomplete @ mentions on description page

### ISSUE THREAD

**Issue by davidblum** [microsoft/vscode-pull-request-github#1206]
When making comments on the PR in vscode, the @<mention name> does not auto populate.

Small feature, but very useful if your coworkers have creative GH names.

Thanks!
![image](https://user-images.githubusercontent.com/7356579/58897440-8d56f680-86b5-11e9-8f1c-6a3182392dec.png)

**Comment by martynchamberlin** [comment]
Would also love this on any textarea, including when you're commenting on a PR or when you're doing an inline comment. Thanks!

**Comment by ibrowne** [comment]
This is a great extension, but I agree, the lack of @mentions in most places is more than a little frustrating since I then need to go back into GitHub in the browser just to @mention a team member in a comment. 

Here's what I've noticed from my short experience using this extension:
- @mentions **do not** auto-complete on: 
   - PR Description page
   - File Diff view when trying to leave an in-line comment
- @mentions **do** auto-complete on:
   - Actual file when leaving an in-line comment in when in review mode (so this is a great first step 👍 )

**Comment by alexr00** [comment]
The description page is a webview, so we don't have access to the VS Code suggest/autocomplete there. Closing as there are no plans to address this issue.
