### ISSUE TITLE
Signing into github.com message stays after pressing Cancel in auth callback prompt

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#1351]
From @chrisdias:
> If I start the auth dance, then press Cancel when asked if I want to let the extension open a URL, the status bar stays at Signing into github.com.... Since I cancelled, I expect it to revert back to Sign in to github.com.

> Also (just noticed this) we say into and in to. Not sure which version is right or wrong, or if its based on context :).

**Comment by JeffreyCA** [comment]
I noticed if you press Cancel, the webpage still says success.

In addition, the instructions on the webpage for when the redirection failed might have to be changed because Step 3 says "Click Signing in to null... in the status bar."

It should say github.com instead of null, and if the status bar changes to "Sign in to github.com" after cancelling how would the user be able to manually input the token?

**Comment by RMacfarlane** [comment]
Hmm, the behavior I see now is that the browser automatically opens, there's no dialog asking if you want to open the login link. You mean after the browser is open and you've clicked "Continue"? As far as I know, I don't think there's a way for the web page to detect that opening the link to VSCode was cancelled.

Agree that we shouldn't display null in the status bar 😄 

I think it's reasonable to revert to "Sign in to github.com" if the process has been cancelled rather than failed, but we may not always be able to detect which is which. There's always the `Manually provide authentication token` command in the command palette.

There used to be a dialog that was shown for first opening the login page, but VSCode has added login.microsoft.com as a trusted domain to skip this. For other community builds like VSCodium, the dialog would still show since its not part of the whitelist there. So I think we can still address the original issue for that.
https://github.com/microsoft/vscode-pull-request-github/blob/0d1c7ce6c9dfcaaa9a88f72a94909c54ba7357fd/src/authentication/githubServer.ts#L190

The call to open the browser url returns whether or not it was successful, so I was thinking we could throw an error there if it fails. But I think there may be cases where it fails for reasons besides the user hitting "cancel"

**Comment by lerros99** [comment]
#1868

**Comment by akwabay** [comment]
Hi

**Comment by burkeholland** [comment]
It looks like there is a 60 second timeout on the whole auth flow. If you cancel at the last point and then wait long enough, VS Code shows an error message saying that the login failed and the logs show "Cancelled".

There doesn't appear to be any event that is thrown in that time. No way to know other than to wait for the timeout.

@alexr00 thoughts?


https://user-images.githubusercontent.com/686963/132909849-91f248d0-ed76-4003-8a93-b848330ace60.mp4

**Comment by alexr00** [comment]
> There doesn't appear to be any event that is thrown in that time. No way to know other than to wait for the timeout.

I'm ok with this current behavior, since the user basically has cancelled at this point. 

The dialog mentioned in the OP isn't shown here because we allow that URL to be opened without an additional dialog. Additionally, the old `openExternal` code shown above isn't even used in this extension anymore since it is handled by the GitHub auth extension. , so I think we can close this issue.
