### ISSUE TITLE
New commits on PR appears misaligned

### ISSUE THREAD

**Issue by JeffreyCA** [microsoft/vscode-pull-request-github#1353]
Back from a long hiatus!

- Extension version: 0.12.0
- VSCode Version: 1.39.0
- OS: macOS 10.14.6

Steps to Reproduce:
1. Navigate to PR where there is an added commit

Issues:
- Commit hash is misaligned
- Username overflows to two lines

<img width="684" alt="Screen Shot 2019-10-02 at 10 56 02 PM" src="https://user-images.githubusercontent.com/9157833/66102917-d4bc9900-e568-11e9-96c0-fe5dfe5757b2.png">

**Comment by RMacfarlane** [comment]
Welcome back @JeffreyCA!

The rendering of the "..." button on GitHub seems a bit strange to me
![Screen Shot 2019-10-03 at 9 49 45 AM](https://user-images.githubusercontent.com/3672607/66147273-61944080-e5c3-11e9-8fa4-8a2d3383075b.png)
But I think something like this would be useful, since the commit message could potentially span even more than two lines. My expectation when I clicked to expand was that it would render the whole text as an unbroken block and move the "..." button the end

**Comment by RMacfarlane** [comment]
Looking back through old issues, there's https://github.com/microsoft/vscode-pull-request-github/issues/302 already tracking the "..." for toggling the whole commit message. So let's use this issue to specifically track the alignment issue
