### ISSUE TITLE
Conversation comment source links don't work

### ISSUE THREAD

**Issue by bryceschober** [microsoft/vscode-pull-request-github#1370]
Issue Type: <b>Bug</b>

In conversation view, the source comments source locations are decorated as links, but do nothing when clicked or ctrl-clicked.

Extension version: 0.11.2
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment]
@bryceschober Can you add a screenshot of one of these links? Do you mean these?

![Screen Shot 2019-10-09 at 3 18 13 PM](https://user-images.githubusercontent.com/3672607/66524729-150ba200-eaa8-11e9-9984-c68ee80c7bb9.png)

**Comment by bryceschober** [comment]
@RMacfarlane Your screenshot is exactly what I mean.

**Comment by RMacfarlane** [comment]
Thanks for confirming! I'm having trouble reproducing this myself.

- Does this happen when you have the pull request checked out, when you're on a different branch and just looking through the "GitHub Pull Requests" tree, or both?
- Does this happen for all file links? Was the file added, deleted, or modified?

The expected behavior is that this should open that file in a new editor (or focus the editor if already open)

**Comment by burkeholland** [comment]
Found in https://github.com/github/codespaces/issues/1608

This happens when the branch is checked out. So...

Nightly: 2020.10.34021
Code: 1.50.1
GitHub Codespaces Service

### Steps to reproduce
1. Click "Checkout"
1. Leave a comment
1. Return to Description
1. Click on file link

### What happens?
Nothing

### What should happen
I should be taken to the spot in the file where the comment was made
