### ISSUE TITLE
LGTM: Unnecessary self assignment in pullRequestNode

### ISSUE THREAD

**Issue by emtei** [microsoft/vscode-pull-request-github#1421]
Found by LGTM [report link](https://lgtm.com/projects/g/microsoft/vscode-pull-request-github/snapshot/cb6d19308dc80a998002c7771df5ebe6cd0536ff/files/src/view/treeNodes/pullRequestNode.ts?sort=name&dir=ASC&mode=heatmap#x69881219b0217846:1)

Whole this block of code seems to be useless. But i`m not so experienced in this module to remove it so i decided to open issue firstly.

https://github.com/microsoft/vscode-pull-request-github/blob/master/src/view/treeNodes/pullRequestNode.ts#L944-L954
```
if (commentThreadCache[params.fileName]) {
	commentThreadCache[params.fileName].forEach(thread => {
		if (!thread.comments) {
			return;
		}

		if (thread.comments.find((cmt: GHPRComment) => cmt.commentId === comment.commentId)) {
			thread.comments = thread.comments;
		}
	});
}
```
@rebornix @RMacfarlane can you remember what is the job of this code?

Should reaction authors be listed in `commentThreadLabel` as "Participants"?

**Comment by RMacfarlane** [comment]
@emtei With the comments API in VSCode, the only way to get the UI to update is by updating certain properties on the comment thread. Setting `comments`, `range`, `label`, `contextValue`, or `collapsibleState` on the comment thread object will trigger an update event and redraw the comment widget. Because we have just updated data on the comments here, we need to signal to VSCode that it should redraw. So this code is actually necessary.

I'm not sure about adding reaction authors as "Participants", on the one hand, there's currently no way to see what user reacted so this could be very useful, I'm not sure if it would be noisy or not. Can you open a separate issue to discuss it?

**Comment by RMacfarlane** [comment]
Would accept a PR adding a comment that explains this block

**Comment by emtei** [comment]
@RMacfarlane Thank you for the comprehensive explanation. I opened the request according to your request.
