### ISSUE TITLE
Spell check comments

### ISSUE THREAD

**Issue by kevintechie** [microsoft/vscode-pull-request-github#1487]
Would it be possible to add spell check to the comment boxes?

**Comment by Shahaed** [comment]
Bump? Is this something the team would be willing to do?

**Comment by Shahaed** [comment]
Looking more into it, it seems it would be difficult to implement since this extension is using the built-in [vscode comment API](https://code.visualstudio.com/api/references/vscode-api#CommentController) for PR comments (see `src/github/prComment.ts`). 

I suppose any change should be dependent on vscode to enable the electron spellchecker for input boxes. That should trickle down to the comment API but I'm not sure.

See: https://github.com/microsoft/vscode/issues/35571

**Comment by alexr00** [comment]
A spell checker extension can actually spell check in the comment widget, but it can show an action to fix the error currently. Closing as upstream.

**Comment by globalhuman** [comment]
Now that this is unblocked upstream, is this now possible?

**Comment by alexr00** [comment]
@globalhuman this would be a request you can make against your favorite spell checker extension. Some may actually support it already with a setting. For example, streetsidesoftware.code-spell-checker can support this already:

```
	"cSpell.allowedSchemas": [
		"file",
		"gist",
		"sftp",
		"untitled",
		"review",
		"pr",
		"comment", // this is one you need to add to get it working in comments
		"vscode-userdata",
		"vscode-scm"
	],
```

**Comment by globalhuman** [comment]
thanks @alexr00 that's what was missing. 

Is there an issue for displaying the `quick fix` action that this extension is tracking or is it blocked elsewhere?

> A spell checker extension can actually spell check in the comment widget, but it can't show an action to fix the error currently. Closing as upstream.

**Comment by alexr00** [comment]
Tracking that here now: https://github.com/microsoft/vscode/issues/164262
