### ISSUE TITLE
Hover doesn't add links for PR descriptions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1491]
<img width="304" alt="Screen Shot 2020-02-13 at 8 13 10 AM" src="https://user-images.githubusercontent.com/2193314/74454426-bcbf2500-4e38-11ea-80c1-00fdfa931534.png">

Created one for the white follow link text at https://github.com/microsoft/vscode/issues/90614

**Comment by alexr00** [comment]
Added detection of issue numbers in the issue body text. The PR review webview gets the issue body HTML instead of the issue body text. In the HTML, it's a link. I can't do that in the hover because the hover supports only markdown and I deliberately strip out most formatting to more closely match what the hovers on GitHub look like.
