### ISSUE TITLE
@user hovers on scss functions and sassdoc comments

### ISSUE THREAD

**Issue by GrimLink** [microsoft/vscode-pull-request-github#1605]
## Versions
- Extension version: 0.15.0
- VSCode Version: 1.43.2
- OS: maxOS Mojave

## Steps to Reproduce:

1. Hover any name with a `@` symbol, e.g. `@if`
2. User reference is shown

![Screenshot 2020-04-05 at 23 04 18](https://user-images.githubusercontent.com/4387541/78510052-c60ea300-7792-11ea-983c-9a9a7993e6bb.jpg)

## Solution

Please exclude:
* `@`'s that are not a comment
* Documentation words like `@return` and more from sassdoc.
   Same as with jsdoc where I don't get github user info on.

**Comment by alexr00** [comment]
We already check if the current location is a comment with 149f33482f009b75fabc2ca6a41ca93f0a2b9b03

**Comment by eduludi** [comment]
It looks this bug is back. 

In JSDoc comments, like `@typedef` or `@type`, I can see a user reference appearing on mouse over these symbols. 

If I disable the extension, no user reference appears.

Example:

![JSDoc Example](https://github.com/user-attachments/assets/868a919a-23aa-4c13-a837-f6971f7d5b7e)

**Comment by alexr00** [comment]
It still looks fixed to me. Please make sure that the language of your file is set to either typescript of javascript.
