### ISSUE TITLE
Update extension icon

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#1617]
Adopt the PR icon in place of the GitHub icon

**Comment by misolori** [comment]
Another related question is if we should adopt the [official GitHub logo](https://github.com/logos) in our codicons, because right now we use our outline version. This icon appears in the activity bar and status bar:

![image](https://user-images.githubusercontent.com/35271042/79243714-daa20980-7e2a-11ea-9fd8-fc85eb3eb758.png)

cc @bpasero

**Comment by bpasero** [comment]
I find both GitLens and GH icon out of place with our new icons:

![image](https://user-images.githubusercontent.com/900690/79437957-327b7480-7fd3-11ea-938b-168d503ec3a8.png)

//cc @eamodio

**Comment by misolori** [comment]
I believe the GitHub PR icon will be updated to use the PR icon (which is what this original issue is about):

![image](https://user-images.githubusercontent.com/35271042/79503741-8c396a00-7fe6-11ea-97e5-8fd1b3059eb8.png)

**Comment by RMacfarlane** [comment]
Right, we'll use the PR icon in place of the GitHub icon.

As part of adopting the auth provider API, I also removed the status bar icon that has the GitHub icon. Now the only place it's used in the extension is as a fallback avatar if a user doesn't have one on the description page
