### ISSUE TITLE
Extension host frozen with large document

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-pull-request-github#1629]
* have this setting `"typescript.tsserver.log": "verbose"`
* open the TS server log
* in another editor request intellisense
* 🐌 the extension host will be slow, blaming this extension for taking up for then 5 seconds CPU time

<img width="819" alt="Screenshot 2020-04-15 at 11 50 21" src="https://user-images.githubusercontent.com/1794099/79324063-4e1d4700-7f0f-11ea-8604-ccba92706fc6.png">

[GitHub.vscode-pull-request-github-insiders-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-pull-request-github/files/4480376/GitHub.vscode-pull-request-github-insiders-unresponsive.cpuprofile.txt)

**Comment by jrieken** [comment]
This due to finding a word with a custom (expensive) regexp https://github.com/microsoft/vscode-pull-request-github/blob/master/src/issues/issueHoverProvider.ts#L15. Which in this case will scan the entire document

**Comment by jrieken** [comment]
This isn't soo simple... You are using an API and the usage is correct but it triggers a very unhappy case here (with v e r y long lines). The API should at one point just bail out and throw the towel - I will follow up with that.

What you could do for finding links is this: Instead of running your own link-regex (which I suspect causes slowness), you could rely on the built-in link detection. Run the [`vscode.executeLinkProvider`](https://code.visualstudio.com/api/references/commands)-command and get all links that we have already found, then filter them by the github-prefix. That might help, be a valid bandaid.

**Comment by alexr00** [comment]
Since this is for hovers using `vscode.executeLinkProvider` won't catch `#123` issue numbers, but it would be better than nothing. 

Simplest work around would be to just not provide issue and user hovers when the line is very long. Users probably won't have issue hovers they care about on giant lines anyway (with the exception of markdown).

In this case, I will just not provide hovers if the line is greater than 300 characters (except for markdown). If a user eventually asks for hovers on long lines, I'll add the `vscode.executeLinkProvider` check.

**Comment by jrieken** [comment]
> In this case, I will just not provide hovers if the line is greater than 300 characters (except for markdown).

300 might be a little strict, I think 10000 should still do it. We might also come up with something smart here https://github.com/microsoft/vscode/issues/95319 and it might resolve this issue after all

**Comment by jrieken** [comment]
@alexr00 fyi - your workaround shouldn't be needed any longer

**Comment by alexr00** [comment]
Very nice, I will remove it!
