### ISSUE TITLE
Broken OAuth flow

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#164]
I tried using the new OAuth flow. After accepting app access to my github data, I got redirected here:

![image](https://user-images.githubusercontent.com/22350/43945119-7e04baa6-9c81-11e8-8598-8d9356728345.png)

Went back to Code, clicked refresh int he splitview header, got this:

![image](https://user-images.githubusercontent.com/22350/43945164-a144d884-9c81-11e8-8016-fbcbb0bddcd7.png)

Reloaded, expanded `Assigned To Me`, got the `Login` again, but this time it worked:

![image](https://user-images.githubusercontent.com/22350/43945203-bbd8ccf0-9c81-11e8-9e0a-204d4943d25b.png)

**Comment by shana** [comment]
Thank you for testing this! I think perhaps the connection timed out between you initiating the login and accepting it, which is why it gave that cryptic error. You should have gotten an error message on the vscode side about the authentication failing, before you hit refresh, did you see it by any chance?

**Comment by joaomoreno** [comment]
Unfortunately I didn't see it...

**Comment by shana** [comment]
I've opened #188 and #189 to add more commands and UI to the authentication flow, and I've updated the web UI so it's less cryptic. I'm pretty sure this was a timeout issue, and there's not a lot I can do about that other than direct the user to try again (and having a command on vscode plus some more UI will hopefully help with that).
