### ISSUE TITLE
Restore option: Manually Provide Authentication Response

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode-pull-request-github#1665]
Recent Nightly builds changes authentication method that relies on OAuth app which seems great (especially if also used for Settings Sync) bit has problems with access to private repos except your own.

It would be great to have option to manually provide token to resolve access problems as it worked in 0.15 and earlier.

**Comment by RMacfarlane** [comment]
I just changed the authentication flow of the new GitHub authentication provider to be what this extension used to have. So, instead of directly using an OAuth app, it goes to an authentication server owned by GitHub, which grants tokens that do not have the restriction about organziation-owned private repos. Settings sync uses the same GitHub authentication provider.

This is a temporary solution - we eventually want to get rid of the server, but should make the extension behave as it used to

**Comment by IllusionMH** [comment]
> we eventually want to get rid of the server

So then it would be changed to OAuth again or there is some third alternative?

**Comment by RMacfarlane** [comment]
Not sure what it would be yet, the current possibilities are OAuth app again, or a GitHub app. GitHub app poses other challenges, instead of dynamically requesting tokens with different scopes, you have to specify permission at create time, so would not work well for the GitHub authentication provider. We're talking to some people at GitHub, so we may be able to come up with an alternative to those.

**Comment by IllusionMH** [comment]
Thanks for the explanation!

**Comment by jedster1111** [comment]
I think I'm having a problem that's related to this.
My company has a privately hosted version of GHE that lives at `https://github.<company-name>.com`. I authenticated previously by running the `Manually Provide Authentication Response` and provided a token and host name.
My authentication settings got removed, and now I can't set the auth token again since that command is missing. I tried to manually set the settings in my VSCode settings using:
```json
{
  "githubPullRequests.hosts": [
    {
      "host": "github.<my-company>.com",
      "token": "myToken",
      "username": "jthompson"
    }
  ],
}
```
but that doesn't seem to work either.

Also the instructions here - https://github.com/Microsoft/vscode-pull-request-github/wiki#personal-access-token-authentication still reference the now missing command.

How can I log into my company's Github Enterprise instance? I might be missing something obvious though. Thanks

**Comment by jedster1111** [comment]
Just noticed the paragraph on that FAQ page about discontinuing support for GHE.
https://github.com/Microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported
Looks like support for GHE has been withdrawn.
Really like the extension though 😄  I guess I will stick with `0.15.0` for now. Wonder how much work it would be to re-add support for manually providing an auth token, or is that something that will be purposely disallowed from now?
