### ISSUE TITLE
PR Title Source needed?

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#1702]
https://github.com/microsoft/vscode-internalbacklog/issues/1021

Both the latest commit's message and the branch name seem unlikely to be helpful titles. Maybe instead just have an input box with #issuenumber as its preselected text?

![image](https://user-images.githubusercontent.com/9205389/80494574-18447d80-8967-11ea-8747-8199ac44f443.png)

**Comment by alexr00** [comment]
@chrmarti I almost always (even before using the PR extension) want to use the latest commit message as the title of my PRs, so this makes sense for me. I hate having the issue number in the title of a PR because it is utterly un-scannable (if I'm quickly looking through commits to try to find something suspicious, a number is meaningless), so I always put the issue number on a new line. 

Because of this, I never want to encourage people to put an issue number as the first thing in their commit messages. You can specify a custom PR title, is that sufficient?

**Comment by chrmarti** [comment]
I see, then make the last commit's message the default text in an input box and skip the PR Title Source step? The branch name doesn't make more sense than the issue number.

**Comment by alexr00** [comment]
Sounds good to me!

**Comment by misolori** [comment]
I agree that we should use the last commit message, that is what the GH ui does as well:

Commit message
![image](https://user-images.githubusercontent.com/35271042/80517134-6fcbf480-8939-11ea-877e-4236395d3e0a.png)

Default text for pr
![image](https://user-images.githubusercontent.com/35271042/80517111-65115f80-8939-11ea-910d-d936a5882be0.png)

**Comment by alexr00** [comment]
Since the selected option is the last commit message, I don't think there is any further work here.
