### ISSUE TITLE
Copy Permalink: Does not work in multi-root workspace

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#1772]
Steps to Reproduce:

1. have more than one folder in VSCode (multi root)
2. select Copy Permalink on a file of the first root

=> the URL is built with the second folder.

I think the extension is not multi-root ready. Not sure if that is only specific to this command or entirely.

**Comment by alexr00** [comment]
Previously, the repo was whatever was selected in the SCM view.

Now, for file related issue actions, it should use the repo for the file you are in.

**Comment by bpasero** [comment]
@alexr00 yeah seems to work better now, but I notice a huge slowdown for any copy/open operation, up to 10s before something happens, is that known?

**Comment by alexr00** [comment]
Yes, that is [this](https://github.com/microsoft/vscode-pull-request-github/issues/1884) bug. I merged  a work around for it today, and am working on add more git extension API to improve it further. With the work around you should <3s.

**Comment by bpasero** [comment]
Ok let me know when I can test your change from a new nightly release.

**Comment by alexr00** [comment]
@bpasero, I made a new nightly release so that you could try out the work around for the slowness. In a repo where this is slow, it will not use the slower way to get the "best" remote (so if you have a fork with an "upstream" remote, you will not get a permalink in the upstream, but in the fork). For repositories where this isn't slow, it will still try to make a permalink for the "best" remote.
