### ISSUE TITLE
Label suggestion dialog should only contain labels

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-pull-request-github#1952]
Testing #1938

Can we remove these items from the suggestion dialog?

![image](https://user-images.githubusercontent.com/3372902/86226827-7fabc300-bb8c-11ea-85ed-9543a76823df.png)

**Comment by alexr00** [comment]
I don't think we have a way to do this since those are coming from the markdown extension. Even if I make the document selector as specific as possible (`{ scheme: NEW_ISSUE_SCHEME, pattern: '**/NewIssue.md', language: 'markdown' }`, the Trigger Suggest command will show all. If you just hit space (the trigger character for this specific suggestion) then you will only see labels. 

@jrieken, is there a way to prevent the markdown extension from providing suggestions like this?

**Comment by jrieken** [comment]
No, an extension cannot prevent suggestions from other extensions showing up. In this specific case it's actually static snippets and they are contributed static for a certain language. I think of of two ways to tackle this

* don't call it markdown but issue-markdown and thereby not inherit these snippets
* find a way to disable snippet completions for this specific model, tho you might break use-cases where this is wanted

A personal workaround for @lszomoru would be to disable snippet completions, either for markdown or all together.

**Comment by alexr00** [comment]
It is important that the new issue file still be colorized as markdown, since that's one of the best parts of using it. 

It also seems important to preserve the snippet suggestions in the rest of the editor, since that's also an upside of using the new issue editor. 

Since there is not optimal solution right now, I will leave it as is and leave this issue open in case we think of a better idea.

**Comment by alexr00** [comment]
No better ideas thought of yet.
