### ISSUE TITLE
PR comments being added at wrong places, certain parts of the change delta missing from extension view

### ISSUE THREAD

**Issue by brphelps** [microsoft/vscode-pull-request-github#1983]
- Extension version: 0.17.0
- VSCode Version: 1.46.1 (user setup)
- OS: Win 10

Steps to Reproduce:

1. Opened a PR on a github org that is private
2. Certain change types seemed to be "missing" from the extension view (the area in gray was missing in the extension view):
![image](https://user-images.githubusercontent.com/10023676/87085614-05f78300-c1e5-11ea-8450-ac9f4b561ad3.png)
3. When I created a comment, it would appear in the correct location until I refreshed the PR:
![image](https://user-images.githubusercontent.com/10023676/87092685-bc149a00-c1f0-11ea-87eb-d71aba0499b4.png)

Note that after code was closed and reopened the issue is no longer occurring (I see the correct view of the diffed file). I'm not really sure the exact way to reproduce this, but since it resulted in me writing up about 20 comments that I had to manually move, it seemed worth writing up :) .

**Comment by RMacfarlane** [comment]
My suspicion is that your local repo was slightly out of date, which would have resulted in partial content being displayed. This should be fixed with https://github.com/microsoft/vscode-pull-request-github/issues/2070, and commenting on stale diffs should be better handled with https://github.com/microsoft/vscode-pull-request-github/issues/1864.

I'm going to close this since I think it's been fixed, let me know if you see something like this again! Sorry for the frustration of having to move 20 comments 😱
