### ISSUE TITLE
Creating issue failed: No matching repository (name for source repo of my fork) found for (name of source user for my fork)

### ISSUE THREAD

**Issue by Esterni** [microsoft/vscode-pull-request-github#1990]
Issue Type: <b>Bug</b>

Currently working on a fork that has since been renamed. Attempting to create an issue using any method (# TODO, Create Issue..., Create issue from selection...) gives a notification that no matching repos were found, but the names given are for the original repo and author names. 

Unsure of the steps to reproduce specifically. I'm fairly new to using git overall, but have had guidance from someone more experienced. I'm told there's nothing particularly special about how I'm working with this. 

Extension version: 0.17.0
VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
@Esterni I think you need to update your remotes. What is the output of `git remove -v`  in your repo? Does it show the original name or the rename?

**Comment by Esterni** [comment]
@alexr00 since creating this issue I've create moved the project into it's own repo. My apologies for not being able to provide more information or troubleshooting on this

**Comment by sunt05** [comment]
The issue here: I'm working on a forked repo and archived the upstream one; it seems this plugin always tries to create issues in the upstream repo and thus fails.

![image](https://user-images.githubusercontent.com/1802656/104837776-a7574400-58ae-11eb-8bed-d5c83ae790d9.png)

My repos with issues are the following:
1. new one (`origin`): https://github.com/UMEP-dev/SUEWS
2. old/archived one (`upstream`): https://github.com/Urban-Meteorology-Reading/SUEWS

Thanks for your help!

**Comment by alexr00** [comment]
@sunt05  can you try adding this setting 
```
	"githubPullRequests.remotes": [
		"origin"
	],
```
By default, we try to be smart and look for an `upstream` repo. This setting should cause `upstream` to be ignored.

**Comment by sunt05** [comment]
> @sunt05 can you try adding this setting
> 
> ```
> 	"githubPullRequests.remotes": [
> 		"origin"
> 	],
> ```
> 
> By default, we try to be smart and look for an `upstream` repo. This setting should cause `upstream` to be ignored.

Thanks for following up this issue.
The above, however, doesn't work; I have even tried to remove the `upstream` remote with a freshly cloned repo, no success either.

I'm happy to provide more diagnostic info if needed: I really like this feature and would like to use it in a forked repo.

**Comment by burkeholland** [comment]
I'm unable to create the PR without an upstream defined. Which seems logical, but the extension seems like it knows about the upstream without me configuring it.

1. Clone a fork
2. Create a branch
3. Push a change
4. Start a PR

The extension recognizes the "parent repo", but is unable to create the PR for that repo. If you manually add the upstream to the remotes, then the PR works. Are we expecting people to add the upstream, or should GHRPI handle that logic for them if they don't have it defined?

**Comment by RMacfarlane** [comment]
We're expecting people to add the upstream, but we can do a better job of nudging them to do this.

If you don't set the upstream, we also won't try to fetch PRs from it in the tree. (A case where you might intentionally not set an upstream is If you've forked a project with the intent to diverge from the original.) Instead of automatically fetching data from the upstream everywhere, we could show a one-time notification if we detect something is a fork, asking if an upstream remote should be added, or show a message in the create PR view about it

**Comment by burkeholland** [comment]
Yeah - I like the upstream notification. Perhaps we could add it when they try to initiate the PR. This will match what people who are used to GitHub expect.

**Comment by burkeholland** [comment]
Added feature request to automatically create the upstream if it doesn't exist. 

https://github.com/microsoft/vscode-pull-request-github/issues/2439

**Comment by alexr00** [comment]
@sunt05 we have added better upstream support. If you are still seeing this issue then please comment here and I'll reopen this issue and investigate further.

**Comment by sunt05** [comment]
Thanks for your work.
However, I'm sorry that the issue seems to persist: if I have a forked repo and would like a submit an issue to the forked repo, the plugin simply fails. 
I've already set the `Remotes` to include only `origin`:
![image](https://user-images.githubusercontent.com/1802656/121897363-32cbe880-cd1a-11eb-8d12-209878c826e9.png)

**Comment by alexr00** [comment]
@sunt05 thanks for commenting back so quickly. We tried to do something smart when a repo is a fork, but we should not do that if you have your `remotes` configured at all. With the fix I merged, if you have your `remotes` configured, then we won't try to be smart about choosing an upstream repo for you. 

You can try out the fix in our nightly build (extension id `github.vscode-pull-request-github-insiders`) tomorrow.

**Comment by sunt05** [comment]
Great, thanks @alexr00 ! Will try this tomorrow.

**Comment by sunt05** [comment]
Confirmed: it's working now with the nightly build!

Many thanks @alexr00!
