### ISSUE TITLE
Support to navigate to a TODO location in a file from an issue inside VS Code

### ISSUE THREAD

**Issue by ps-jppinto** [microsoft/vscode-pull-request-github#2045]
I add a TODO and that creates an issue, then I can assign it with @ but how do I make it so that an assignee can go directly to that TODO in code? We are mainly working on .ps1 files. 

I see an option to start working on the issue and to open it on the web, but nothing to jump to that section in the file where that TODO was created it.

**Comment by alexr00** [comment]
This is an interesting feature request! I think we should be able to detect if an issue has a code link in the issue body and add a new context menu action to go to that location locally.

**Comment by egamma** [comment]
One idea @alexr00 and I have discussed is to resolve the permalink from the issue description shown in the hover locally inside VS Code by opening the corresponding editor location.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/172399/90265439-e2160580-de52-11ea-93f5-545f34a5f7bf.png">

**Comment by ps-jppinto** [comment]
@egamma The line numbers could change over time. Unless that link is scanning dynamically then in that case, that would be great. Worse case scenario is just a link to the file would help.

**Comment by alexr00** [comment]
To verify:
- Have an issue show in the issues view or an issue link in a comment in a code file. The issue needs to have a GitHub permalink to a file that you have available in your current workspace.
- Using the issue hover, click on the link in the issue.
- Verify that the file is open in VS Code instead of in the browser. If the file hasn't changed much then the correct lines should match the permalink's lines.
- Verify if that the file doesn't exist in the current workspace that the file is open on github.com.

**Comment by JacksonKearl** [comment]
I can't seem to get this to work.. the issue is here https://github.com/JacksonKearl/mixedCase/issues/2, opening that repo and clicking the entry in the hover taakes me to github.com, tested on codespaces and desktop
