### ISSUE TITLE
Weird line in the comments panel

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#214]
When I checked out https://github.com/Microsoft/vscode/pull/56052 and was looking at the comments panel, I resized the panel so that I can see the `...` in the end. Then when hovering on the long comment, the below line appeared

![image](https://user-images.githubusercontent.com/16890566/44177232-d21b8d80-a0a1-11e8-80fb-a7bb0b88573b.png)

**Comment by rebornix** [comment]
@RMacfarlane I probably found the root cause while reviewing https://github.com/Microsoft/vscode-pull-request-github/pull/209 . When we have images in the comment, it's partially rendered and we see it as a line

![image](https://user-images.githubusercontent.com/876920/44359416-b0892000-a46c-11e8-86cc-1a3180888747.png)
