### ISSUE TITLE
Clicking a comment from panel in an unopened file flickers 

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-pull-request-github#2148]
Issue Type: <b>Bug</b>

1. Checkout a PR
2. Open Comments Panel
3. Click a comment for a file that is not currently open

:bug: => file opens but comment is flickered on and off

Extension version: 2020.9.31141
VS Code version: Code - Insiders 1.50.0-insider (f943318042a3b9229049aea86cea04d0ff9c8210, 2020-09-23T06:50:43.482Z)
OS version: Windows_NT x64 10.0.19041

**Comment by RMacfarlane** [comment]
Some notes to myself on why this happens:
- Comments are created for a particular uri. When a PR is checked out and we show diffs from the tree, the right hand side is the same uri as the normal local uri.
- Right now we create comments for these local files once. When we open the local file outside of the diff, the comments should be collapsed, but in the diff, we want to expand them by default.
- Because of this, when a text editor is opened, we check to see which of these cases we are in and try to reset the collapse state.
- VSCode expands the comment when clicked from the panel, but then this is reset by the extension immediately
