### ISSUE TITLE
Problem with TODO comments

### ISSUE THREAD

**Issue by dimaguy** [microsoft/vscode-pull-request-github#2166]
- Extension version:Latest?
- VSCode Version:The one used by codespaces as of 26/09/2020
- OS:Web-based

I tried using this extension as it comes by default on github's codespaces beta. No idea on used version but pretty sure its the latest as I did not change anything on the environment
I have found a problem with TODO comments.

Current Behaviour
When making a TODO comment

```
vb.net
' TODO:placeholder here
```

VSCode suggests creating a github issue

![](https://aws1.discourse-cdn.com/github/original/2X/3/3823e6da8366655f8367bfb0ce10a6dd87d99697.png)

But it actually does not check if the repository is up to date (if the code in the repo matches the local branch) and makes it likely to point the snippet at another line that does not correspond to the TODO comment line that was supposed to be mentioned.

How it was supposed to behave

1-click on “Create GitHub Issue”
2-The issue opens pointing at the correct line of the TODO comment.

Suggested Fixes
1- Quote the code instead of mirroring it from the file and point to which file it is in.
or
2- Not let the github issue be created unless local code matches repository.

**Comment by alexr00** [comment]
Interesting, we are creating a permalink which should avoid this problem entirely.

**Comment by alexr00** [comment]
I can't actually repro this. Because we use permalinks they are, well, permanent. They use the commit number, the same way GitHub.com does, to make sure that they actually point to the location that was there at the time you created the issue. So even if the repository isn't up-to-date with the remote, you still get the correct location because the commit number is used to create the link. 

@dimaguy do you have a public repo where I can take a look at this? I'm interested in:
- The commit+branch that your repo was at locally.
- The permalink that was created when you created the issue.
- The commit that the remote was on when you created the issue.

**Comment by alexr00** [comment]
Ah, this is for a newly written todo comment, where the remote does not have that line. That is fair, the link will not be correct in this case since it isn't possible for it to be correct.

If the permalink can't be correct, it would be better to quote the code and also provide a best guess permalink. An issue author can then decide what is most useful to keep.
