### ISSUE TITLE
Error trying to build - run - debug

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode-pull-request-github#2188]
I'm trying to build and run the extension from source, but the extension does not activate on the `Extension Development Host`. But, if I _package_ the extension (`vsce package`) and install the VSIX file, it works perfectly.

I did take a look at the `Contributing` wiki (https://github.com/Microsoft/vscode-pull-request-github/wiki/Contributing#build-and-run), but it seems a _regular_ environment (no special steps/dependencies). Except the `Architecture` section, where you describe _Some features and bugs may require making changes to VSCode itself instead of the extension_ 😬 .

On my first attempt, it was raising errors about `webviewIndex.js` missing.

After _packaging the extension_ and debugging it again, the `webviewindex.js` error was replaced by `Activating extension 'GitHub.vscode-pull-request-github' failed: t.onDidChangeDecorations is not a function.`

Tracing the error, the latest location was at `prsTreeDataProvider.ts`, at its `constructor`

```
this._disposables.push(vscode.window.registerDecorationProvider(DecorationProvider));
```

Any ideas what I could be doing wrong/what am I missing?

Thank you

**Comment by RMacfarlane** [comment]
> On my first attempt, it was raising errors about webviewIndex.js missing

Running `yarn watch` in a clean state I see this myself, but it then gets corrected. There are three webpack tasks that get run, one for the extension and then two for the webviews, if possible we should make it so that the extension one always runs after these.

> After packaging the extension and debugging it again, the webviewindex.js error was replaced by Activating extension 'GitHub.vscode-pull-request-github' failed: t.onDidChangeDecorations is not a function.

Ah, right now the insider's version of VSCode is required to run the extension. There were some changes to the proposed API we adopted that are only in that version. I'll add a note about this in the contributing guide!

**Comment by ejkim1996** [comment]
Hello! I have a little bit of a different issue, but it relates to the build not working so I thought I'd comment here. Please let me know if I should open a separate issue.

I was looking at the `Contributing` wiki as well and following the instructions, but came across a couple issues. I am using git `2.22.0`, yarn `1.22.10` and VSCode Insiders `1.51.0-insider`
1. When using Node.js `>= 8.9.3, < 9.0.0` like the wiki says, I get the following error: `error node-fetch@3.0.0-beta.9: The engine "node" is incompatible with this module. Expected version "^10.17 || >=12.3". Got "8.17.0"`
    - updating Node.js to `^10.17 || >=12.3` shows errors when installing `fsevents`, and while it does seem to say it is optional, running yarn watch fails because of `fsevents`
2. running `npm install` instead of `yarn install` seems to install `fsevents` properly, but running `yarn watch` afterwards shows a warning:
```
    WARNING in ./node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js
    Module not found: Error: Can't resolve '@opentelemetry/tracing'
```
and throws the following error
```
ERROR in /Users/ejkim/Desktop/Git Repos/vscode-pull-request-github/src/test/view/reviewCommentController.test.ts
    [tsl] ERROR in /Users/ejkim/Desktop/Git Repos/vscode-pull-request-github/src/test/view/reviewCommentController.test.ts(121,4)
          TS2322: Type '{ threadId: string; uri: vscode.Uri; range: vscode.Range; comments: never[]; collapsibleState: vscode.CommentThreadCollapsibleState.Expanded; label: string; readOnly: boolean; dispose: () => void; }' is not assignable to type 'GHPRCommentThread'.
      Object literal may only specify known properties, and 'readOnly' does not exist in type 'GHPRCommentThread'.
```

@RMacfarlane If you have any insights into how I can get past these issues I'd greatly appreciate it! :)

**Comment by ejkim1996** [comment]
Hi, I had some more time to dig into the last error I mentioned, I was able to fix the issue by setting the upstream remote and pulling from master. It's my first time trying to contribute to an open source project so I missed something simple 😅

I'm guessing the issue with `npm install` vs `yarn install` is probably an issue specific to me. Although I believe the Node.js version issue would pop up for others too. Maybe the `Contributing` wiki can be updated to show Node.js versions that work with current modules?

**Comment by RMacfarlane** [comment]
Thanks for pointing out the Node.js version problem, I've updated the `Contributing` wiki to the correct version!

I'm not entirely sure why `yarn install` would have failed for you. 🤔  `npm install` and `yarn install` sometimes resolve dependency versions slightly differently, I always use `yarn`. `fsevents` should be optional on Windows and Linux

**Comment by alefragnani** [comment]
Just to let you know, I was able to build and run/debug the extension 🎉 

I updated my fork with the latest commits and re-cloned the repo. To avoid any _external dependency issues_ I decided to open the repo on a Remote Development (using the _Node 10 and TypeScript_ template), and it worked just fine.

I experienced the same _first time issue_ while running`yarn watch`, but after the second run, the error disappeared. This time, I remembered to copy the log:

```
    [./src/issues/issueFeatureRegistrar.ts] 38.4 KiB {extension} [built]
        + 542 hidden modules
    
    ERROR in ./src/github/activityBarViewProvider.ts
    Module not found: Error: Can't resolve '../../media/activityBar-webviewIndex.js' in '/workspaces/vscode-pull-request-github/src/github'
     @ ./src/github/activityBarViewProvider.ts 20:38-88
     @ ./src/view/reviewManager.ts
     @ ./src/extension.ts
    
    ERROR in ./src/github/issueOverview.ts
    Module not found: Error: Can't resolve '../../media/webviewIndex.js' in '/workspaces/vscode-pull-request-github/src/github'
     @ ./src/github/issueOverview.ts 20:26-64
     @ ./src/github/pullRequestOverview.ts
     @ ./src/commands.ts
     @ ./src/extension.ts
Child webviewIndex.js:
```

Thanks you so much for your help.
