### ISSUE TITLE
Avoid nasty notifications when both stable and nightly are installed

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#2191]
I wonder if there's a smoother user experience when both stable and nightly are installed and activated?

![Screenshot 2020-10-02 111424](https://user-images.githubusercontent.com/22350/95061898-82263780-06fc-11eb-933e-b34bf70f9131.png)

**Comment by RMacfarlane** [comment]
This is actually sort of tricky, because this notification comes from VSCode itself when reading the contribution points of extensions, before the `activate` method is necessarily called. I think we would have to rename the views for the nightly version, and then we could detect that both extensions are installed side by side and show a better notification

**Comment by joaomoreno** [comment]
>  I think we would have to rename the views for the nightly version, and then we could detect that both extensions are installed side by side and show a better notification

Not such a bad idea yeah.

We should really push forward insider extension versions to the Marketplace...

**Comment by alexr00** [comment]
We would have to rename views and commands I think. Lots to rename.

**Comment by alexr00** [comment]
We would have to rename views and commands I think. Lots to rename.

**Comment by joaomoreno** [comment]
Yeah I'm fine we also close this as _not gonna do anything_ 😆

**Comment by alexr00** [comment]
I'm going to close this as "not gonna do anything" since the _real_ solution here is for the marketplace to support insider extension.
