### ISSUE TITLE
Protect "pull" notification if branch changes

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-pull-request-github#2266]
Currently we show a notification to pull changes if the PR branch is behind the upstream, but we should protect it to be a no-op if the current branch changes.

**Comment by rchiodo** [comment]
@alexr00 can you put some repro steps?

I'm not sure what the 'PR' branch is. I thought the pull request extension shows remote PRs so how would my local branch affect it?

**Comment by alexr00** [comment]
To repro/verify:
1. Checkout a PR, either through the PRs view or by checking out a local branch that you have an active PR on.
2. **Not using the PR extension**, so through github.com or through a different clone of the same repo, push a new commit to the PR.
3. Run git fetch in you PR repo.
4. You should see a notification pop up saying that there are changes in your PR and do you want to pull. Don't do anything yet, just leave the notification sitting there.
5. Change branches.
6. Use the "Pull" button in the notification from 4. It should do nothing, because your current branch is no longer the PR branch. The original bug was that it would pull your current branch.
