### ISSUE TITLE
Hover in views shows path with leading slash

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2287]
Noticed that the custom hover shows a leading slash for relative file paths (here in the PR extension). Not sure if this is an issue with VSCode or the extension:

![image](https://user-images.githubusercontent.com/900690/98710756-5e51b380-2384-11eb-8804-882a48c0b31f.png)

**Comment by alexr00** [comment]
It seems that it isn't possible to remove the leading '/' from vscode.Uri.path.

**Comment by alexr00** [comment]
@jrieken I have tried using the following to remove the leading '/' from a vscode.Uri.path, but I believe it isn't possible. Is there a way that extensions should use vscode.Uri to indicate a relative path?
```
		let file = vscode.Uri.file(this.fileName);
		// vscode.Uri.file adds a slash to the front of the path. We should remove this since the path is relative
		if (file.path.startsWith('/')) {
			file = file.with({ path: file.path.substring(1) });
		}
```

**Comment by jrieken** [comment]
No, we don't support relative uris we because we have no concept if a base uri to which they should be relative. The URI class and parts of the file service enforce uris to [be absolute](https://github.com/microsoft/vscode/blob/ba04493467ef26487628d95c701e7858268ff1d4/src/vs/base/common/uri.ts#L57)

**Comment by alexr00** [comment]
We could pretend that the paths in the extension are absolute by adding the workspace folder to the uri, however; this could be a lie since not all of these files have to exist in the user's workspace. We could also check if each file exists, and only prepend the workspace folder if it does. This will result in some files having the workspace prepended, and some not which doesn't seem better than the current behavior.

@bpasero I'm closing as won't fix because I'm claiming that these files are all absolute relative to the PR itself.
