### ISSUE TITLE
Add a secondary button style to the overview page

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#232]
From discussion in https://github.com/Microsoft/vscode-pull-request-github/pull/224

Have primary and secondary button styles on the overview page

**Comment by misolori** [comment]
@RMacfarlane @rebornix what do you think of applying a `-webkit-filter: grayscale(100%)` on the secondary buttons so that we don't have to define a secondary color?

**Dark Theme**
![image](https://user-images.githubusercontent.com/35271042/44432350-8e6bcc80-a556-11e8-8f74-8ac2dfcefd40.png)


**Light Theme**
![image](https://user-images.githubusercontent.com/35271042/44432341-86ac2800-a556-11e8-8c4e-3cdf540d8212.png)

**Comment by misolori** [comment]
We'd either need to use a current color token that has a background and hover color, or create a new one that we would add to VS Code.
