### ISSUE TITLE
Why would 'outline' not work in Pull Request mode ?

### ISSUE THREAD

**Issue by phil-blain** [microsoft/vscode-pull-request-github#2321]
Hi!

I noticed that when I open files from either the read-only "Pull Requests" section of the viewlet (is that what it's called?) or the read-write "Changes in Pull Request" section of the same viewlet, depending on the language, if I then switch to the Explorer viewlet , the Outline is empty. It works for other file types.

For example, for Markdown files I can see an outline but for Fortran files (using [FORTRAN IntelliSense](https://marketplace.visualstudio.com/items?itemName=hansec.fortran-ls) and [Modern Fortran](https://marketplace.visualstudio.com/items?itemName=krvajalm.linter-gfortran)) the outline is empty. (But it works correctly in normal mode, i.e. when editing files normally).

I'm not sure where exactly is the problem, but I figured someone here might be able to help or point me in the right direction...

**Comment by RMacfarlane** [comment]
Hmm, the difference between opening a file from these different places is the file scheme. When opening a file normally, from the explorer or quick search, etc. it has scheme 'file'. When opening a file from the "Pull Requests" section of the viewlet (you're right, this is what it's called 😄 ), a file with scheme 'pr' is opened. This allows the extension to register a content provider that handles documents with that scheme, so that it can fill in the content from GitHub. I'm a bit confused about why this would also impact the "Changes in Pull Request", this tree should also open 'file' scheme documents for the right hand side of the diff, comparing what's actually currently on disk.

I'm not very familiar with how extensions provide outlines, but my hunch is that maybe some of them are doing this specifically for 'file' scheme documents instead of just those that match on language

**Comment by phil-blain** [comment]
Thanks a lot for answering. This should be useful for debugging. Is there a specific "output" channel I should look at that could show me which scheme is in use ?

**Comment by RMacfarlane** [comment]
I couldn't find a place where this is logged in output, but if you're debugging an extension, you can use the `vscode.window.onDidChangeActiveTextEditor` to get info about the current editor. In particular, looking at the document.uri from the text editor for that event

**Comment by RMacfarlane** [comment]
@phil-blain I'm going to go ahead and close this since I think the extension is working as expected, but let me know if there's anything else I can do to help with this

**Comment by phil-blain** [comment]
Great, thanks! :)
