### ISSUE TITLE
Contribute the Copy Permalink command to the Copy As submenu

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#2326]
See the GitLens extension

**Comment by alexr00** [comment]
@eamodio would you be willing to rename the Gitlens "Copy As" submenu to just `editor/context/copy`?

https://github.com/eamodio/vscode-gitlens/blob/bbbbc017aa9fb258a3886e0300cb5c9b51f0c684/package.json#L8360-L8363

**Comment by eamodio** [comment]
Sure, can do.

**Comment by eamodio** [comment]
@alexr00 although in order for us to use `editor/context/copy`, core would need to add that as a built-in submenu -- otherwise we won't be able to target it. Because if we both attempt to contribute it either as a `submenu` or into `editor/context` it will error out, see below.

If we both attempt to contribute it as a `submenu` we will get the following error:
_The `editor/context/copy` submenu was already contributed to the `editor/context` menu_

And if we both attempt to contribute the submenu to `editor/context` we will get the following error:
_The `editor/context/copy` submenu was already previously registered_

**Comment by alexr00** [comment]
Hmm, as you say, looks like it should be added as a core menu. @joaomoreno is there a way to contribute a submenu in the core that only shows if it has items in it?

**Comment by joaomoreno** [comment]
Unfortunately we decided to go with: an empty submenu still renders as empty. We can look into changing that or having a setting for it. cc @jrieken
