### ISSUE TITLE
Cannot create a PR from codespaces 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pull-request-github#2376]
- Create a codespace for https://github.com/microsoft/vscode-java-pack. It forked the repo as I do not have permissions.
- Try to create a PR from the forked repo using following options
  - Using parent repo
  - On master branch
  - Use last commit

🐛 I got following error

![image](https://user-images.githubusercontent.com/10746682/105160125-25feec00-5b10-11eb-9a6b-0c6cf838be8d.png)

**Comment by RMacfarlane** [comment]
@sandy081 It sounds like you're using the stable version of the extension and not insider's, right?

**Comment by bamurtaugh** [comment]
I believe this stems from/relates to https://github.com/github/codespaces/issues/760? We're tracking that issue with the `ghcs-scenario-blocking` label.

**Comment by RMacfarlane** [comment]
In the new create flow, this issue manifests as https://github.com/microsoft/vscode-pull-request-github/issues/2374. I have a fix out for that which ensures the dropdown gets populated, but it only lists the remotes that you have locally. Since we have metadata about whether or not a repo is from a fork, we could have a button or warning to create an upstream remote in this case.

Anyway, since the old create flow is already removed, I'm going to go ahead and close this issue

**Comment by sandy081** [comment]
@RMacfarlane It seems with new flow I can no longer create a PR against main repo from forked repo:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/10746682/106163009-fd6a9800-6188-11eb-847b-033a79e227a2.png">

which I can do it in old flow

<img width="672" alt="image" src="https://user-images.githubusercontent.com/10746682/106162943-ed52b880-6188-11eb-9e6f-4dbbb87db84d.png">

Not sure if this is being tracked by other issue, I would reopen this for this.

**Comment by RMacfarlane** [comment]
@sandy081 The dropdown lists only remotes you have locally. If you want to target the parent repo, add an upstream remote to it
