### ISSUE TITLE
Failing to get any pull requests from remotes

### ISSUE THREAD

**Issue by and-rewsmith** [microsoft/vscode-pull-request-github#2385]
- Extension version: 0.22.0
- VSCode Version: 1.52.1
- OS: Linux Ubuntu 18.04

Steps to Reproduce:

1. Clone repo with ssh key with SSO enabled
2. Get the following error:
[Info] GitHubRepository> Fetching pull requests for branch failed: HttpError: Resource protected by organization SAML enforcement. You must grant your OAuth token access to this organization.

Am I misunderstanding something?

**Comment by thisislawatts** [comment]
Hey @and-rewsmith 

I experienced something similar after our GitHub org was migrated to SSO, I have had success with the following steps:
* Revoking the App https://github.com/settings/applications?page=1
* Uninstalling extension from VSCode
* Installing extension to VSCode
* Reauthenticating

**Comment by carlocardella** [comment]
Thanks @thisislawatts for the suggestion, unfortunately those steps did not fix the problem for me. 
Also, not sure if it really matters, I am not using an OAuth token to sign in, I am using my GitHub credentials (with 2FA); I do not see how to authorize application (`GitHub for VSCode` in this case) to use SSO as it is possible with OAuth tokens

**Comment by alexr00** [comment]
@TylerLeonhardt is this something that the GitHub Authentication extension should handle?

**Comment by TylerLeonhardt** [comment]
@alexr00 this is where the `forceNewSession` property on `getSession` comes into play. GHPR should (if it's not already?) ask for a new session when it's faced with this SAML error. Unfortunately there's nothing the GitHub Auth extension can do because we don't know about the SAML state (since it's case-by-case per repository/org).

**Comment by TylerLeonhardt** [comment]
To everyone on the thread, when you go through the OAuth flow for VS Code, you must must must make sure you authorize the flow to access the SAML'd organization. GitHub auth should show a page with all your SAML-enabled orgs that you must go through 1 by 1 and authorize through their respective SAML flows. Unfortunately, I don't have a screenshot to give you because I'm already "samled" but I'll drop a screenshot tomorrow.

**Comment by alexr00** [comment]
If we get a SAML error, the following should happen:
1. You get a modal dialog saying that you need to SAML
2. You get another modal dialog prompting to auth.
3. The rest of the auth flow happens.

**Comment by roblourens** [comment]
How do I trigger that kind of error?

**Comment by alexr00** [comment]
I think you need to have not SAMLed yet for the day, so if you've already done that on a machine, you can't get this error for one day. Otherwise:
1. From the accounts icon in the activity bar, sign out of your github.com account.
2. Reload.
3. Open the GitHub view.
4. Start to sign in, **but don't finish**. When you get to the web page that shows the organizations that you are a part of, **don't authorize any of them**, but use the big continue button.
5. The sign in flow will complete and you should see the modals as described above.
