### ISSUE TITLE
Not convinced githubPullRequests.pullRequestTitle and githubPullRequests.pullRequestDescription are needed

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#2407]
Refs: https://github.com/microsoft/vscode/issues/114967

Just creating this to share feedback. I am not convinced `githubPullRequests.pullRequestTitle` and `githubPullRequests.pullRequestDescription`. I think here we should just behave like github and try to preserve Title and Descirption if the user canceld the PR creation.

Does GitHub have settings to control this, if yes can we somehow get it from the user profile, it they do not have it then I think we do not either.

I think we can find a smart default value, and add these settings later only if they are needed

**Comment by RMacfarlane** [comment]
This is a good point, previously we had these settings because you weren't really able to edit the title and description when creating.

GItHub doesn't have any user setting for this. Currently, when it is set to "ask", it should try to copy GitHub's behavior for filling these fields. (Title is based on last commit if there's only one, or the branch name. Description comes from template if there is one, or the commit if it has a body)

So, I think it would be reasonable to deprecate them.

**Comment by isidorn** [comment]
I get a nice warning (because it is deprecated) but nowhere does it say "deprecated"
Still adding verified and you can let me know if you would like me to create a new issue, or this is something regarding JSON schema in the settings

![Screenshot 2021-01-28 at 18 24 31](https://user-images.githubusercontent.com/1926584/106175176-1af22e80-6196-11eb-9dc8-e740da7560c6.png)
