### ISSUE TITLE
Revisit comment expansion behavior on local files

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#2506]
1. Check out a pull request
2. Open a file changed in the pull request from the file explorer
3. Add a comment to the file, comment shows as expanded
4. Open a different file so that the active editor changes
5. Go back to the original file, there's a slight flash and the comment is now collapsed

Related https://github.com/microsoft/vscode-pull-request-github/issues/2148

For comments on local files, we are currently try to show them as expanded by default when shown in the context of a diff, and as collapsed when shown just on the file. Reseting the collapse state can be pretty jarring. We specifically have to reset it because the file in the right hand side of the diff and the file from the file explorer are exactly the same.

It seems very difficult to get the correct expansion state - if we try to save off what the previous state was for expansion was on the file in the local vs diff context, opening it from the comments panel is still a challenge. There's a race between VSCode trying to expand the comment, and the extension potentially trying to collapse it.

I'm wondering if a better approach to this would be to simply always show the comments on files as always expanded, and have an easy way to immediately collapse all of them. @bpasero for thoughts on this, since I think the comments on files were really getting in your way when using the extension

**Comment by bamurtaugh** [comment]
Thanks for opening this! I experienced confusion around this at ~12:44 of the video in the 2/17 run https://github.com/microsoft/vssaas-planning/issues/2176#issuecomment-771141071.

I like the idea of always showing the comments as expanded - that was my expectation going in, and I feel like it'd match the GitHub web experience where I'm used to seeing my comments. I'd definitely be interested to hear other thoughts though, too, since this was a smaller use case with just 1-2 comments.
