### ISSUE TITLE
Change wording of pushing up commits before creating a PR

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-pull-request-github#2508]
Change this wording to: `There are currently no commits between 'main' and '<my branch>'. Do you want me to push your local changes for you and try to create the pull request again?`

![image](https://user-images.githubusercontent.com/12758612/108542864-23232280-7299-11eb-940f-6ac961aff695.png)

**Comment by RMacfarlane** [comment]
I actually think the current wording is consistent with other dialogs in VSCode - I don't know of anywhere where we use "I" or "me" to refer to our code.

![Screen Shot 2021-02-19 at 10 03 14 AM](https://user-images.githubusercontent.com/3672607/108543418-ead01400-7299-11eb-8e76-aee5951919f2.png)

I think being more explicit that the PR will be created rather than just "try again" would help, and that this would be easier to read as multiple lines. How about
 ```
 There are currently no commits between 'main' and '<my branch>'
 
 Would you like to push your local commits and create the pull request?
```

with buttons "Cancel" and "Push Commits"

**Comment by tanhakabir** [comment]
Hm very true! I like the button suggestion!
