### ISSUE TITLE
Trying to checkout a merged PR with the branch already deleted shows cryptic error

### ISSUE THREAD

**Issue by lumaxis** [microsoft/vscode-pull-request-github#2524]
Extension version: 0.23.1
Version: 1.54.0-insider
Commit: 9ecd3fc3022e8c154aff868f74bd5d77f7d4a2ea
Date: 2021-02-23T10:44:56.219Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

1. Merge a PR and delete the branch
2. Try to checkout that PR via the extension

![image](https://user-images.githubusercontent.com/406937/108921100-2110e900-7636-11eb-9bd3-743c8a3c8816.png)

**Comment by joyceerhl** [comment]
This works now, but I get an error message  
![image](https://user-images.githubusercontent.com/30305945/144646841-06b4bafd-3668-4ec6-b14d-480517544ca7.png)

Is the error message strictly necessary since GHPRI is able to open the pull request contents?

**Comment by alexr00** [comment]
Huh, I wouldn't have expected you to be able to checkout the PR at all since the branch no longer exists. I see a better error when I try to check out that PR, and the PR isn't checked out.

![image](https://user-images.githubusercontent.com/38270282/145016707-82366375-edb5-49fa-8042-9df6275c2824.png)

**Comment by alexr00** [comment]
Hmm, maybe it's because you still have a local branch.
