### ISSUE TITLE
PR's to review not showing

### ISSUE THREAD

**Issue by tim-field** [microsoft/vscode-pull-request-github#2577]
- Extension version: 0.24.0
- VSCode Version: 1.54
- OS: Apple Silicon Big Sur

Steps to Reproduce:

PR extension only shows my current PR, not PR's pending my review like it used to.

This used to work perfectly, I haven't changed any of the extensions settings 

![image](https://user-images.githubusercontent.com/1326910/111533563-ca797380-87cb-11eb-92cf-f9cf3a7604bf.png)

**Comment by RMacfarlane** [comment]
We recently changed the extension to use two different view containers on the activity bar - the PR icon for the current PR and the GitHub logo for the PR list. So, this is currently expected behavior, but this is causing a lot of confusion so we will likely revert to a single view container again. Tracking that with https://github.com/microsoft/vscode-pull-request-github/issues/2585
