### ISSUE TITLE
Opening a different panel/extension once checking out a PR is confusing

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-pull-request-github#2585]
When you check out a PR another extension page gets loaded which is different from usual extension workflows so it's kind of confusing.

Found in GHPRI study.

![recording (19)](https://user-images.githubusercontent.com/12758612/111689497-564dc880-87e9-11eb-9245-dff9daed0200.gif)

**Comment by alexr00** [comment]
Cramming all 4 views into the PRs view container will make the PRs view container too full. We also tried replacing the views in the PRs view container, but got feedback that people really wanted to the PRs view even when a PR is checked out.

When I've participated in user studies in the past, I saw that some users _don't actually know how to use the activity bar_. This issue was opened sufficiently long ago that you probably can't say if this was one of those users, but instead of not using multiple view containers we should maybe focus (in VS Code core) on encouraging use/understanding of the activity bar in general.
