### ISSUE TITLE
"No commits between master and master" trying to create a pull request

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#2620]
I wanted to put in a quick bugfix for a library, and tried to use Codespaces to do it.

1. "Opened the repo" in a codespace
2. Made the changes and committed them (did not push) via the CLI
3. Thought I should use the built-in PR flow for this, so I tried hitting the "create a pull request" button.
4. I was prompted to push my changes, which I did. Then I got into this state:

![](https://memes.peet.io/img/21-03-a54b117e-b1a6-4377-b259-8a7418181ac2.png)

I couldn't figure out how to create a PR to the original repo, I always landed on this screen and that error. I eventually ended up using the Github UI.

**Comment by RMacfarlane** [comment]
Hmm, I think this is a UX problem - it looks like you have your own repo selected in the first dropdown instead of the upstream. In the nightly version there are two sets of selectors, one for the target and one for the source, so hopefully it would be more clear how to make the PR upstream. Also, the upstream remote  should be added automatically if it's not there, so it should always show up in the dropdown. (when using the nightly version). Going to go ahead and close this since I think the next release should make this easier to understand

**Comment by RMacfarlane** [comment]
Oh, and I guess also a note on using Nightly in codespaces is that since the stable version of the extension is installed as a built in, the stable wins out over it unless you search for it and disable it
