### ISSUE TITLE
Too many notifications

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#267]
![image](https://user-images.githubusercontent.com/323878/44558650-37066180-a6fa-11e8-9686-94f8a5f828cc.png)

- See this notification
- Dismiss it
- A minute later I see it again
- Repeat

Just upgraded from .11 to .14

**Comment by shana** [comment]
I'm not tracking whether you purposefully dismissed the login to avoid showing the dialog. I did that because if you accidentally dismiss it, it would never ask again and then you'd be stuck not knowing how to make things work. It will popup whenever the PR tree tries to load data, which is what I'm guessing is happening here. I can track the dismissal and never ask again, I guess

**Comment by shana** [comment]
Fixed by https://github.com/Microsoft/vscode-pull-request-github/commit/5879c0604b5bd606f74d9cf05cb8a8dd9d6e1c85
