### ISSUE TITLE
Error when checking out a pull request

### ISSUE THREAD

**Issue by anand2312** [microsoft/vscode-pull-request-github#2718]
- Extension version: 0.25.1
- VSCode Version: 1.56.0
- OS: Windows 10

Steps to Reproduce:

1. Try checking out to a pull request without having the GH CLI installed
2. The operation fails, and the error bubble does not give much info 
![preview](https://why.life-is-pa.in/kK6OXE.png)

Although this is a minor issue, it'd be helpful if the error tells you to install the GH CLI first

**Comment by RMacfarlane** [comment]
Hey @anand2312, GH CLI is not required for this extension, this looks like a bug. Can you please open the output panel and share the contents of the "GitHub Pull Request" log and also the "Git" log?

**Comment by anand2312** [comment]
You're right, it doesn't seem related to the GH CLI; initially the error had stopped appearing once I'd installed it, but now the error shows up randomly again. I'll try to post the details you've asked here ASAP

**Comment by anand2312** [comment]
```
[Info] Review> switch to Pull Request #726 - start
[Info] PullRequestGitHelper> Branch pr/Objectivitix/726 is from a fork. Create a remote first.
[Info] PullRequestGitHelper> create remote for git://git@github.com:Objectivitix/sir-lancebot.
[Info] Review> checkout failed #{"message":"Failed to execute git","stdout":"","stderr":"fatal: unable to look up git@github.com:Objectivitix (port 9418) (A non-recoverable error occurred during a database lookup. )\n","exitCode":128,"gitCommand":"fetch","gitArgs":["fetch","Objectivitix2","main:pr/Objectivitix/726","--depth=1"]}
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch main
[Info] Review> no matching pull request metadata found on GitHub for current branch main
```

**Comment by TylerLeonhardt** [comment]
@alexr00 can we get some verification steps?

**Comment by alexr00** [comment]
The "fix" for this was to provide a better error message. Since the error is transient it cannot be reliably reproduced. 
To verify by code review:
- The change is here: https://github.com/microsoft/vscode-pull-request-github/pull/2779
- Take a look at the error message format from the user logs that were posted in this issue, pasted here for convenience:
`{"message":"Failed to execute git","stdout":"","stderr":"fatal: unable to look up git@github.com:Objectivitix (port 9418) (A non-recoverable error occurred during a database lookup. )\n","exitCode":128,"gitCommand":"fetch","gitArgs":["fetch","Objectivitix2","main:pr/Objectivitix/726","--depth=1"]}`
- The change checks if there is a `stderr` message, and uses that if so. Review the code and verify that the change is doing this.
