### ISSUE TITLE
Poor accessibility to pull request review

### ISSUE THREAD

**Issue by ndarilek** [microsoft/vscode-pull-request-github#2737]
- Extension version: latest
- VSCode Version: 1.56
- OS: Windows

Steps to Reproduce:

1. Open a pull request with comments, suggested changes, etc. when using a screen reader.
2. Open a file in the changes view, using whatever is necessary
 to get its annotations (I'm actually not entirely sure of this workflow since I myself am a screen reader user and had a hard time discovering it.)

I did eventually get what appears to be a diff of my file alongside my reviewer's comments. I could also sort of tab to the text of various comments, a few buttons, etc. But it definitely isn't keyboard-friendly. Some suggestions:

1. Put these annotations in some sort of virtual document so they can be interspersed with the comment areas, buttons to mark the conversation closed/resolved, etc.
2. Make it easy, via the keyboard, to jump to a read-write editor so I can make suggested changes, then back to the comments so I can ensure that I'm doing what was suggested.
3. If it isn't already, add keyboard-accessible controls to accept suggested changes.

Thanks.

**Comment by isidorn** [comment]
@ndarilek thanks a lot for creating this issue. 
We do not really give the PR extension a good accessibility testing, so there are definetely ares of improvement here

I am not 100% sure who owns the PR extension atm, for now assigning to @alexr00 and she can correct me if I am wrong
I can do a pass of the extension and provide feedback on how to improve here. Let me know what you think

fyi @RMacfarlane

**Comment by alexr00** [comment]
Most of what is needed is making the comments (buttons, comments view, what line a comment is associated with, the accept suggestion button, etc.) accessible. This is an upstream issue with VS Code: https://github.com/microsoft/vscode/issues/110408

I have tried to improve the accessibility info for some of the tree items so that it's easier to understand what each tree item does (open the PR description page or open a diff for example). I'm not usually a screen reader user, so feedback is more than welcome.

For getting to an editable version of the file where you can make changes, there is the "Open Changes with Working File" action in the editor actions menu. However, if you don't have the PR checked out yet then this probably isn't what you want. You can access the "Check out" action from the PR's context menu in the PR tree view which will checkout the branch that the PR is on so that you can make changes to it.
