### ISSUE TITLE
Got an error: 'No authentication provider 'github' is currently registered'

### ISSUE THREAD

**Issue by danielu221** [microsoft/vscode-pull-request-github#2744]
All the time I can see "Loading" in Github pull requests extension in Pull requests section and issues sections:
<img width="212" alt="Zrzut ekranu 2021-05-21 o 15 56 56" src="https://user-images.githubusercontent.com/9407508/119148837-2fac4800-ba4d-11eb-8caa-1412b1271aa6.png">

Any authentication pop-up never showed up.

I also realised that  console for VScode shows me an errror:

```
No authentication provider 'github' is currently registered.: Error: No authentication provider 'github' is currently registered.
```
Commits and publishing works OK

What can I do with that? Is there any solution to add vscode app to trusted app in github again ?

- Extension version: 0.26.0
- VSCode Version: 1.56.2 (Universal)
- OS: macOS Catalina 10.15.7

Steps to Reproduce:

1. Download Github Pull Requests extension
2. Nothing happened just "Loading..." all the time

**Comment by hdanielsen** [comment]
Hi, 
I was advised by Github Support to let you know that i am having the exact same issue as discussed here. The problem started after enabling 2FA for github. 

----
#### Background and resolved related VScode issue: 

After this VsCode was unable to login/connect when using git in a bash Terminal and the Source Control tab as well as from the github extension tab as addressed here.  The problem with the Terminal tab and SC Tab was resolved by executing a git pull from command line (instead of from VSCode), cancelling the login dialog that pops up and then enter userid and the Personal Access Token in the password prompt. Every attempt to do this from VScode failed because VScode seemed unable to handle the prompts for both userid and password.  

---

But I am still having the issue addressed here. Github Support's suggestion to uninstall the extension, revoke the access form OAuth, close VScode and restart and install the Github Pull Requests extension did not resolve the issue 

Thanks,
Håvard

**Comment by alexr00** [comment]
@danielu221 Did you have a folder open when you downloaded the extension?
