### ISSUE TITLE
Strange avatar is displayed for GitHub Enterprise

### ISSUE THREAD

**Issue by think120** [microsoft/vscode-pull-request-github#2771]
- Extension version:  v0.27.0
- VSCode Version:  Code 1.57.0 
- OS: Win10 1909
- GitHub Enterprise version:  GitHub Enterprise Server 3.0.4 

The avatar of the Pull Request in GitHub Enterprise is strange in "GitHub" and "GitHub Pull Request" tab, as shown in the picture below:
![image](https://user-images.githubusercontent.com/78618719/121686543-3b71b400-cab9-11eb-8a92-f41de9edb321.png)

Looks like it is because in the following postion,  `this.pullRequestModel.userAvatarUri` is used instead of `new vscode.ThemeIcon('github')`
https://github.com/microsoft/vscode-pull-request-github/blob/565d4e6ca5215dfe4b3201f2cbc9d97bd404bbd0/src/view/treeNodes/pullRequestNode.ts#L266-L269

**Comment by think120** [comment]
@alexr00 , I've tested the nightly build, 
1. "GitHub" tab now can display correct avatar
![image](https://user-images.githubusercontent.com/78618719/121695090-a378c800-cac2-11eb-90f9-62b0d8ff3da3.png)

2. For "**GitHub Pull Request**" tab,  still shows the strange avatar
![image](https://user-images.githubusercontent.com/78618719/121695597-1b46f280-cac3-11eb-9c7a-16fcbaa7295a.png)

3. In the `Pull Request Description` page: 

- For the Pull Request created by **myself**, sill shows the strange avatar
![image](https://user-images.githubusercontent.com/78618719/121695745-416c9280-cac3-11eb-9e01-2adc76384aba.png)

- For For the PR created **by other people**,  correct avatar is displayed.
![image](https://user-images.githubusercontent.com/78618719/121695986-8395d400-cac3-11eb-94a4-c5c7027c5456.png)

**Comment by alexr00** [comment]
Thanks for testing this @think120. I've found the source of the bug for the other avatar locations. There will be a new nightly build on Monday. If you could test again with that upcoming build and comment back here about whether the bug is fixed that would be very helpful!

**Comment by think120** [comment]
@alexr00, I've upgraded the nightly build of this extension to v2021.6.19263, but the issue 2 and 3 still exist.  Does that build include your fix? Many thanks!

**Comment by alexr00** [comment]
Yes, that build has the fix. Thanks for testing this out.

**Comment by think120** [comment]
@alexr00 , many thanks for your quick fix! Now, only the "`delete branch`" operation **can't display** the avatar of the user, but it is good enough for me!
![image](https://user-images.githubusercontent.com/78618719/122055686-c9fb7380-cde0-11eb-8e5e-0717b17233e8.png)

**Comment by think120** [comment]
@alexr00 , I just found this issue https://github.com/microsoft/vscode-pull-request-github/issues/416, looks like  #416 has the same problem as I have.

**Comment by kabel** [comment]
The _weird_ avatars were a **purposeful fallback** choice for the enterprise integration. The icon was generated from the [Gravatar](http://en.gravatar.com/site/implement/images/) service since unauthenticated requests to the GHE avatar service is likely disabled for most. If your GHE email didn't exist in the Gravatar service, the default was set to the "retro" [generated default](https://github.com/microsoft/vscode-pull-request-github/blob/6769dd4cba8b3b6bfef20c94ef28918103634680/src/github/utils.ts#L945).

Perhaps I should have implemented this feature behind a feature flag, but now we've regressed back to having no avatars for enterprise, which make me sad.

**Comment by kabel** [comment]
I've also seen the 404 image shown in example 4. These usually come from DOM updates to the webview instead of a full refresh, so some action is inserting a DOM image node that likely assumes a GitHub.com repo instead of GHE.

**Comment by think120** [comment]
And that 404 image is only for "delete branch" operation.

**Comment by alexr00** [comment]
@kabel are you saying that even for enterprise users who have an avatar we now show the wrong thing? If that's the case, I'll just revert the changes I made, call it a day, and not touch enterprise again.

**Comment by think120** [comment]
@kabel , @alexr00, I think may be better to make the feature of using Gravatar configurable. Like in my company, no one use Gravatar and I don't think they will use company email to register Gravatar.  And I think the default octocat icon is nicer than the green "retro" icon 😄

**Comment by kabel** [comment]
@alexr00 
>  are you saying that even for enterprise users who have an avatar we now show the wrong thing?

Yes.

0.27.1:
![image](https://user-images.githubusercontent.com/675956/125088867-71439180-e093-11eb-8e9c-d4750621dfb7.png)


0.28.0:
![image](https://user-images.githubusercontent.com/675956/125088048-ac919080-e092-11eb-9608-1e987cfebf6f.png)

----

@think120 

> And that 404 image is only for "delete branch" operation.

Not _only_, but certainly one of the instances of the webview templates making the wrong assumption about the avatar URL to use. Another example is when I add a reviewer or the rendered PR comments on the Description view:
![image](https://user-images.githubusercontent.com/675956/125089183-c67fa300-e093-11eb-81d3-00a91150b1c9.png)
![image](https://user-images.githubusercontent.com/675956/125089550-11011f80-e094-11eb-8639-dbde9028d55e.png)



> I think may be better to make the feature of using Gravatar configurable.

I agree, so I'll see if I can implement that feature (for the privacy conscious and anti-gravatar folks). I had originally planned to use the SVG icon as the Gravatar fallback instead of the "retro", but couldn't find a publicly hosted version that their proxies could access.

**Comment by think120** [comment]
@kabel , 

https://github.com/microsoft/vscode-pull-request-github/blob/8870a3c77cb09c5cfd0cf3d277b8793fcf418164/webviews/components/user.tsx#L10-L17

This part?

**Comment by alexr00** [comment]
@kabel sorry about the enterprise avatar regression, and thank you for your interest in making Gravatar use configurable. I would love to accept a PR for that.
