### ISSUE TITLE
It's not easy to figure out how to submit a review

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-pull-request-github#2856]
Right now, the only way to submit a review is to do so from the Overview page by leaving a summary comment. It's not clear that that actually submits the review because the button says "Comment".

![image](https://user-images.githubusercontent.com/686963/126676147-9291ff90-3ae7-4cb8-958a-8c0829fdf4a7.png)

Additionally, the "Go To Review" button is located in the comment dialog only after the input box gets focus. It would be nice if there was a submit review button in that dialog. That button could just take you to the overview page where you can type the review description and the button would say "Submit Review" instead of "Comment".

**Comment by alexr00** [comment]
You can also submit a review through the sidebar view when you have a PR checked out.

Renaming the "Comment" button to "Submit Review" is a simple change that I can make now.

We actually used to have a "Finish Review" button on the comments, but got feedback that it was confusing and changed it to "Go to Review". I would stick with that change, since it think it's less confusing. However, it would definitely be better if the "Go to Review" button was more visible (didn't require clicking in the comment area). 

@misolori do you have any ideas/suggestions for how we could show users a "Go to Review" or "Finish Review" button when the user has started a review? We don't have a view in the sidebar in all cases. The buttons in a comment can't currently be made visible without clicking in the comment area, but maybe we could change that.

**Comment by alexr00** [comment]
I like the sidebar change, and I'll add that for cases where we have the sidebar. However, we only show the sidebar when you have the PR checked out, so we'll still have the same problem in cases where some one is reviewing a PR that they don't have checked out.

**Comment by alexr00** [comment]
The button in the sidebar functions as drop down, so I want to keep the text that is shown as one of the dropdown options. 

Here's the new text:
![image](https://user-images.githubusercontent.com/38270282/129353798-57a046b4-a57f-4e03-8d96-81713c587aef.png)

![image](https://user-images.githubusercontent.com/38270282/129353869-c32534ea-7c13-4a12-bc41-cbdbfa4fb662.png)
