### ISSUE TITLE
Too many GetMentionableUsers POST requests

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2892]
In the JS console I can see 51 POST requests having been made to https://api.github.com/graphql. Of those, most are the result of a paginated query called GetMentionableUsers that preloads all mentionable users for this repository.

A giant repository like rails/rails will have 4304 mentionable users, which includes all org members and all prior contributors to the codebase. It will take at least 44 sequential API requests to paginate them all. It's not clear to me why a fresh VS Code instance would preload all this before this information is needed for anything. Could this load to the GitHub API be avoided?

**Comment by alexr00** [comment]
If I remove the pre-fetching of mentionable users entirely, then the @ user completion items in PR comments is unusably slow. Instead of removing the pre-fetching, it is now only done when a PR is checked out.

**Comment by mislav** [comment]
@alexr00 Thanks for the quick fix!

To be clear, since this behavior is still active when a PR is checked out, is the preloading still going to be a thing if someone uses “Open in Codespaces” action for a PR in a project to open VS Code in their browser?

**Comment by alexr00** [comment]
Yes, the preloading will still happen in that case. The mentionable users are used for when the user types `@` in a PR review comment so that we can show suggestions a username to follow the `@`. If we don't preload the mentionable users then we might as well not have that feature since it the suggestions won't show up for a long time (I was seeing over a minute depending on the number of users).

If this preloading is still to much, then we can consider some of the following changes:
- Only preload users who have participated in the PR. 
- Use cached users per repository (only preload once per repository and rely on the VS Code setting sync infra to sync between sessions). If more is needed, then this is the next change I would make.
- I'm also open to other suggestions!

**Comment by mislav** [comment]
I get it that it's too late to start loading the dataset when the user types `@`. What we usually did in github.com frontend in these scenarios is load something at the point where we're fairly certain that the user might intend to interact with this feature soon. For example, we preload some things when you focus the `<textarea>` comment box in a thread. However, when loading mentionable users, github.com frontend has access to a much more efficient loading method (more than a 100 records in a single request, only loads username + full name field, aggressive caching).

Maybe in VS Code the preload can happen when the user shows indication that they might want to leave a code review, rather than on extension load in the context of a pull request? I'm not familiar with how the extension works, but perhaps might be the way to go. Of course, there could also be per-repo caching, since this dataset doesn't change too often.

It's great, though, that the change you've already made fixes this preloading for `github.dev`, which doesn't load in the context of a pull request (as far as I can tell). With github.dev shipping this week, this will make a huge difference. Thank you!

**Comment by alexr00** [comment]
After discussing with some folks I'll look into some further caching so that this is improved for PRs too.

**Comment by alexr00** [comment]
Closing for verification. Caching solution will be implemented with https://github.com/microsoft/vscode-pull-request-github/issues/2897

**Comment by alexr00** [comment]
To verify:

1. Install the nightly build of the extension and disable the stable build if you have it installed.
2. Set the setting `"githubPullRequests.logLevel": "debug"`
3. Open a folder in VS Code that has a GitHub repository. Make sure you're **not** on a branch with a PR. If you are, change branches and reload.
4. Open the Output panel for "GitHub Pull Request". 
5. Open the Pull Requests view and wait until it no longer says "Loading..."
5. Search for the string "Fetch mentionable users" in the Output and verify that it is not present.

**Comment by chrmarti** [comment]
Verified. Also verified that it then loads when I checkout a PR and start writing a comment.
