### ISSUE TITLE
no matching pull request metadata found for current branch

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode-pull-request-github#3043]
- Extension version: 0.31.0
- VSCode Version: 1.61.0
- OS: Gitpod linux container backend, Mac frontend

Steps to Reproduce:

Please see https://github.com/gitpod-io/gitpod/issues/6262 for steps. It seems to happen only for PRs from forks. I can reproduce the same in Codespaces.

Output from the extension:
```
[Info] /home/gitpod/.ssh/config: ENOENT: no such file or directory, open '/home/gitpod/.ssh/config'
[Info] TemporaryState> Error in initialization: Unable to delete nonexistent file 'vscode-remote://indigo-tarsier-p9zs8mmw.ws-eu17.gitpod.io/home/gitpod/.gitpod-code/User/globalStorage/github.vscode-pull-request-github/temp'
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 1 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch pd/fix-workspace-context-url
[Info] Review> no matching pull request metadata found on GitHub for current branch pd/fix-workspace-context-url
```

**Comment by alexr00** [comment]
The remote branch for that PR has been deleted, which is why that PR can't be opened now. A reasonable error message should now show:

![image](https://user-images.githubusercontent.com/38270282/145392089-e1a59093-5ad4-42db-b226-bc498d1b8195.png)


Not sure if it was deleted before or after this issue was made. I can't repro the issue though, so closing.
