### ISSUE TITLE
Add ability to set CLI parameters for merge

### ISSUE THREAD

**Issue by jlk** [microsoft/vscode-pull-request-github#3086]
I'm trying to sign all my commits with my gpg key. (eg `git commit -S...`) It'd be nice if I could sign code merges from within this vscode extension.

Currently, if I merge a PR with this extension, the resulting merge is not signed. If under settings I could specify extra CLI options such as `-S` or `--gpg-sign=<key>` that would be very useful.

**Comment by alexr00** [comment]
I think if you [tell GitHub](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-new-gpg-key-to-your-github-account) about your gpg key then this already works since we just use GitHub API to merge the commit. (All of my PR merges are signed and I usually merge with this extension: https://github.com/microsoft/vscode-pull-request-github/commits/main)

**Comment by jlk** [comment]
OK you're doing the merge GH side, not via cli. thx.
