### ISSUE TITLE
Error while assigning a reviewer

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pull-request-github#3132]
- Created a PR
- Tried to assign a reviewer and I got following error

![image](https://user-images.githubusercontent.com/10746682/143200382-b08119d5-5e41-41b4-be29-3a7156459ca5.png)

**Comment by alexr00** [comment]
Occurs when there are no "assignable" accounts in the repo.

**Comment by alexr00** [comment]
To verify:
- Open a pull request in the extension in a private repository that you're the only contributor on
- Open the description page of the PR and use the + to try to add a reviewer.
- Verify that there is no error.

**Comment by rzhao271** [comment]
Is there a way to display text below the quickpick inputbox, like how pressing on the milestone + with no milestones displays a message saying "No milestones created for this repository"?

**Comment by alexr00** [comment]
@rzhao271 the quick pick doesn't give us a great way to do this and still show progress when the quick pick options are being calculated. Since this quick pick allows multi-select we'd end up with a checkbox next to the "No reviewers available for this repository" message, which also seems confusing.

**Comment by alexr00** [comment]
It does seem better though:
![image](https://user-images.githubusercontent.com/38270282/144590396-e9498ca2-8893-4e4c-8046-fcb2d38f4083.png)

Adding.
