### ISSUE TITLE
Tags are missing for the latest release

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/vscode-pull-request-github#3150]
Hello to the VS Code team!

I wanted to point out that for the latest release (`0.33.2021113015`), there is no release, no tag, and no updated `package.json`, even though the version is published to the Marketplace.

I was curious if this is intentional / and or wanted to raise the awareness of this issue.

**Comment by bigint** [comment]
It seems like they are using 32.0 🤔 

https://github.com/microsoft/vscode-pull-request-github/blob/main/package.json#L16

**Comment by akosyakov** [comment]
Yeah, it looks like `0.33.2021113015` is related to https://github.com/microsoft/vscode/issues/15756. It would be useful nevertheless at least to have a tag associated with `0.33.2021113015` to know from which commit it was produced. GitHub also supports publishing of prereleases.

**Comment by alexr00** [comment]
As you have noticed, the 0.33.* releases are pre-releases. I'm guessing you noticed these new version in the marketplace. My understanding is that the marketplace will soon be updating so that it doesn't show pre-release versions as the new version number.

We have not tagged pre-releases in the past (used to be a separately published extension, but same repo), and VS Code itself doesn't tag insiders releases. We also have a new pre-release ~4 days per week, so we'd have _a lot_ of tags if we stated doing this. Because of all this, we will not start tagging pre-releases. 

@sandy081 and @isidorn FYI as this relates to pre-release extensions.
