### ISSUE TITLE
Too subtle focus indication

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-pull-request-github#319]
Testing https://github.com/Microsoft/vscode/issues/57301

* Write a comment
* Press Tab
Observe: The button is now focused but this is super subtle

Button does not have focus:
![image](https://user-images.githubusercontent.com/5047891/44778187-abb72100-ab7c-11e8-9bc5-0ffdafb77491.png)

Button has focus:
![image](https://user-images.githubusercontent.com/5047891/44778254-cb4e4980-ab7c-11e8-80ce-1d40ecc35e36.png)

**Comment by RMacfarlane** [comment]
Hmm, this is the same themeing used for button focus as other places in the product:

![button_focus](https://user-images.githubusercontent.com/3672607/44868359-77f0ff80-ac3f-11e8-9370-09dde88b19c9.gif)

This one looks much more obvious just because of the size of the button relative to its container

**Comment by alexandrudima** [comment]
I think that button also has a problem. Maybe @misolori has ideas.

**Comment by misolori** [comment]
We could add an outline focus with a 2px offset to help make that more noticeable.
