### ISSUE TITLE
Two tab stops for mark file as viewed with VoiceOver 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-pull-request-github#3341]
Testing #3332

1. Using VoiceOver on MacOS
1. Open a list of files in the PR view
2. Select one
3. Then up arrow to continue going through list
4. Press tab to focus on another item
5. Hit tab to go to the 'mark file as viewed' button
6. Hit tab again

**Bug**
This goes to the originally selected 'mark file as viewed button'

This seems like a confusing UX as these two buttons have the same announcement text which doesn't mention which file will be marked as viewed. I think I'd expect just a single tab stop for button on the currently active tree item

**Comment by alexr00** [comment]
@mjbvz do you have "Tab moves focus" turned on?

My steps:
1. Start NVDA on Windows (no mac to test on).
2. Open a list of files in the PR view
3. Select one
4. Then up arrow to continue going through list
5. Press tab **this causes focus to move to the first inline action on that item, which is "Open File"**
6. Hit tab to go to the 'mark file as viewed' button
7. Hit tab again **This causes focus to move to the fist inline action of the next file in the tree, which is "Open File" for me. It could be "Mark file as viewed" depending on what kind of change that file was.**

Is this what you're seeing?

**Comment by mjbvz** [comment]
Here's a recording of what I'm seeing with VoiceOver on:

![Recording 2022-03-04 at 16 04 15](https://user-images.githubusercontent.com/12821956/156857990-19866910-d027-45ac-96f1-7a54114bd236.gif)

The confusing part is that I end up with two mark file as view tab stops that both have the same generic announcement text on voiceover. I suspect this is a generic tree view issue and not specific to PRs

**Comment by alexr00** [comment]
I understand now, thank you.

@isidorn is there well defined behavior that we should have here? If not, I could just add the aria label for the tree item before each inline action. This seems a bit aggressive though since then if there are 2 inline actions on one tree item then the aria label for the tree item will read before both of them.

**Comment by isidorn** [comment]
I think the problem here is that two inline actions get shown. This should not happen, unless the user is using the mouse hover.

So my suggestion is to only show the inline action item on focused items. But not on selected ones.
And in this case the item is shown both on the focused and the selected one => resulting in two items 🐛

**Comment by alexr00** [comment]
> So my suggestion is to only show the inline action item on focused items. But not on selected ones.

@isidorn, the SCM view also behaves this way, so I don't want to change the tree view's behavior to be different.

I will leave as is for now and see if other feedback comes in.

**Comment by isidorn** [comment]
@alexr00 sounds fair.
fyi @joaomoreno on tree behaviour to show inline actions both on selected and focused items.
