### ISSUE TITLE
Comments panel - comments list randomly changes

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-pull-request-github#3354]
Testing microsoft/vscode#143545

1. Show the comments panel by invoking the command
2. Navigate to a pull request in the pull requests view. I have a pull request that has 4 files - two files have comments while two files do not.
3. Click on each file of the pull request and notice how the list of comments changes randomly

**Comment by alexr00** [comment]
This has to do with how we handle comments for non-checked-out PRs. We have transient comments in this case, and it seems like we're not doing a great deciding when to remove them.

**Comment by alexr00** [comment]
We keep a cache of the last 4 editors (2 diffs) worth of comments because we don't want to infinitely accumulate comments from files opened from the "Pull Requests" view. Whether this cache is the best approach is debatable. 

However, simply sorting the files in the Comments view would be a good first step.

**Comment by alexr00** [comment]
I did two things:
1. In VS Code core, the resources in the Comments view are now sorted, so you won't get unexpected ordering changes
2. In this extension, the cache is now 8 editors (4 diffs), per non-checked-out PR.
