### ISSUE TITLE
Publish no longer prompts to create a PR

### ISSUE THREAD

**Issue by ceedgedev** [microsoft/vscode-pull-request-github#3368]
- Extension version: I don't see a version, but more info says released 9/7/2018, and the last update was 3.2.2022
- VSCode Version: 1.64
- OS: Windows 10

Steps to Reproduce:

1. Made and saved changes
2. Staged changes
3. Signed commit of staged changes
4. Publish button - In the past, at this point, a message would ask if I wanted to create a Pull Request which I do. I no longer get that option. How do I create a PR after I have done a signed commit? Do I hit Publish then something else?
Thanks

**Comment by cbrnr** [comment]
I noticed this too. You can manually create a PR by clicking on the GitHub icon in the left sidebar and then on the "Create Pull Request" icon near the top. However, I would really like to see the automatic prompt again whenever I publish, because this saves a lot of time.
<img width="451" alt="Screen Shot 2022-03-03 at 10 39 36" src="https://user-images.githubusercontent.com/4377312/156538294-40d45a40-08ed-46b3-9e02-852bb9f5a119.png">

**Comment by ceedgedev** [comment]
Thanks, I'll give that a try. Though I wish they would fix it. 
If you create a PR, then want to make more changes in Visual Studio Code, what is the best way to do it. I know to stage the changes then do a commit, so it is signed. What comes after the commit to get it pushed up to the GitHub website, so the change shows in the PR?

**Comment by cbrnr** [comment]
You just synchronize your changes, this will update the PR.

**Comment by ceedgedev** [comment]
Ok, thanks

**Comment by cbrnr** [comment]
It looks like something changed in v0.36 (https://github.com/microsoft/vscode-pull-request-github/releases/tag/v0.36.0) and maybe we clicked on "Don't show again" accidentally. However, I do not know how to revert this choice, I didn't find this setting in the preferences.

**Comment by alexr00** [comment]
The "don't show again" moved into a setting. This should be working now!
