### ISSUE TITLE
There are two sign in prompts when using vscode.dev

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3377]
The first prompt comes from the GitHub Repositories extension.

The second prompt comes from GitHub Pull Requests and Issues extension.

We should only show one prompt.

**Comment by alexr00** [comment]
Thanks for taking a look! I figured it would be the scopes. It looks like the `read:user` and `user:email` scopes may not be needed for GHPRI as I only see that we need the username. I'll do some testing and see if they can be removed. Does RemoteHub definitely need `workflow`?

**Comment by alexr00** [comment]
Tested, and GHPRI needs all the scopes `['read:user', 'user:email', 'repo']`.

@TylerLeonhardt is there anything we can do here to avoid the 2 login prompts?

**Comment by joyceerhl** [comment]
We definitely need `workflow` due to https://github.com/microsoft/vscode-remote-repositories-github/issues/32

It's probably not a good idea for RemoteHub to ask for scopes it doesn't need. Also the authentication api will not hand out tokens which are authorized for more scopes than the extension needs in order to abide by principle of least privilege.

![image](https://user-images.githubusercontent.com/30305945/157272615-3b639343-fad0-4cf8-acca-b1c4e1e2efb8.png)

**Comment by alexr00** [comment]
> Also the authentication api will not hand out tokens which are authorized for more scopes than the extension needs in order to abide by principle of least privilege.

Yep, this is the expected and correct behavior. I was hoping that @TylerLeonhardt might have something like token down-scoping support in the works.

**Comment by TylerLeonhardt** [comment]
@alexr00 

Sadly no. There is nothing on the GitHub side that can help us here. There are plans to introduce the ability to do "token down scoping" which would let us mint a token for just [X] silently if we have a token for [X and Y], but that won't really help us here because the scopes are not a subset of each other...

If we really want to get rid of the second prompt, we can have the two extensions request the same scopes... but I don't particularly like the idea of giving these extensions a token that is more powerful than they need.

**Comment by alexr00** [comment]
Thanks for the details!

**Comment by TylerLeonhardt** [comment]
This should be done... though I don't know where the other issue for this went.
