### ISSUE TITLE
Support permalinks from a git tag

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-pull-request-github#3402]
When trying to create a permalink for https://github.dev/python/cpython/blob/v3.8.12/Objects/typeobject.c#L921 (note the `v3.8.12` tag), I get the following message:

<img width="448" alt="Screen_Shot_2022-03-10_at_20 35 43" src="https://user-images.githubusercontent.com/54418/157923303-d93b161e-e494-4a40-a750-69a483be4010.png">

On github.com I can create the link without issue, so I would love to be able to do the same from github.dev .

**Comment by alexr00** [comment]
@joyceerhl I'm seeing something I don't understand from Remote Repositories, maybe you know what's going on:
When creating a permalink, GHPRI uses the commit hash from `state.HEAD?.commit` on the `Repository` that we get from Remote Repository's git extension API implementation. For the above tag url, this commit hash is `f27882d788badef5b941b3094b3b489d1101d3d8`. What I don't understand is where `f27882d788badef5b941b3094b3b489d1101d3d8` is coming from. It doesn't appear to be the head commit for the `v3.8.12` tag, and in fact I don't see it in that repo at all. Do you know where this commit hash coming from?

**Comment by joyceerhl** [comment]
Super weird--looks like this is what the GitHub APIs are returning to us...
![image](https://user-images.githubusercontent.com/30305945/163652929-8c35f78b-373d-4094-affd-08a3968f4ae5.png)

**Comment by joyceerhl** [comment]
OK, problem is we assumed the OID for a tag is also the associated commit SHA:
![image](https://user-images.githubusercontent.com/30305945/163653864-11c9a2ef-6b5d-45c1-bb81-291bed2dcd5e.png)

I've pushed a change to correctly set `HEAD.commit` for tags in RemoteHub.

Even with this change though, GHPRI cannot generate permalinks for tags (or commits, for that matter).

There are a few issues with the current state of things:
- RemoteHub doesn't support `Repository.log` when a `path` is specified (and also GHPRI is passing `uri.fsPath` as the path to filter on, which is not valid for RemoteHub URIs), so this call will throw https://github.com/microsoft/vscode-pull-request-github/blob/2811810bbf9c26d8d982b56d001d09ad7e7fc4d0/src/issues/util.ts#L480
- When `Repository.log` throws, we end up falling back to `getSimpleUpstream`, and the call to `getSimpleUpstream` always returns `undefined` for commits and tags (even on desktop with the vscode.git IGit implementation) since there is no `repository.state.HEAD.upstream` for commits and tags.
- Even if I fix the `Repository.log` implementation and we get to `getUpstream`, GHPRI runs a search for `getBranches` with `pattern: "remotes/origin/HEAD"` which doesn't seem to be a valid branch name when passed to GitHub APIs https://github.com/microsoft/vscode-pull-request-github/blob/2811810bbf9c26d8d982b56d001d09ad7e7fc4d0/src/issues/util.ts#L409-L414
Also RemoteHub doesn't properly support `getBranches` for a specific commit, and it looks like this would be quite expensive to implement given the state of GitHub APIs: https://github.community/t/is-there-a-way-to-get-which-branch-a-commit-belongs-to-via-graphql/122561/5

Can GHPRI pick a remote in `getSimpleUpstream` when `repository.state.HEAD.upstream` is undefined (which is the case for tags and commits)? Also, can you share more context on how the `remotes/origin/HEAD` branch pattern works? I think ideally I'd fix RemoteHub's `Repository.log` and `Repository.getBranches` implementations so that GHPRI doesn't rely on the `getSimpleUpstream` fallback, but am not sure how to support that query pattern.

**Comment by alexr00** [comment]
> Can GHPRI pick a remote in getSimpleUpstream when repository.state.HEAD.upstream is undefined (which is the case for tags and commits)?

Yes, absolutely. I have pushed a change to do this. If the commit SHA is corrected then we should be good to go there (I tried running out of sources, but I still saw the wrong commit SHA).

**Comment by alexr00** [comment]
For the `pattern` that we pass into `Repository.getBranches` (`remotes/origin/HEAD` above), that comes from the fact that the git extension uses `for-each-ref` in it's implementation of `getBranches` (https://git-scm.com/docs/git-for-each-ref). So for git, only branches that match `refs/remotes/origin/HEAD` will be returned from `getBranches`. As you pointed out, this is basically just a check to make sure the commit belongs to a branch on the remote. For Remote Repositories, I can probably skip a lot of the permalink figuring since by definition the commit exists on the current branch on the remote. This is basically what happens when with the `getSimpleUptream` fallback.

**Comment by joyceerhl** [comment]
Just to make sure we are on the same page here, this is what I see when running GHPRI out of sources against the latest prerelease of RemoteHub--

![image](https://user-images.githubusercontent.com/30305945/164044234-086482ef-6b92-4cde-b148-870e49683ccf.png)

The `commitHash` afaik is now correct, is this the value that you are looking at?

It seems like there was another change in GHPRI so the permalink generation still doesn't work--if `commit` is undefined (which is always the case with RemoteHub until we implement `Repository.log` we aren't going into `getSimpleUpstream` at all.

**Comment by alexr00** [comment]
That `commitHash` looks correct. Something must have been stale somewhere as the one I saw while debugging was the old OID. 

Thanks for checking this and catching my conflicting changes! I pushed the fix for the fix just now.

**Comment by joyceerhl** [comment]
Running GHPRI out of sources against latest RemoteHub and can confirm that GHPRI permalink generation now works when opening the following GitHub urls in RemoteHub (previously, if you had any of these open, permalink generation did not work):
- https://github.com/python/cpython/commit/304f5b63e904c3ab0b746ef7ad58c5c2ff0154a8
- https://github.com/python/cpython/tree/v3.8.12/Objects/typeobject.c#L921
- https://github.com/python/cpython/blob/v3.8.12/Objects/typeobject.c#L921
- https://github.com/python/cpython/blob/aeb66c1abbf4ec214e2e80eb972546996d1a1571/Lib/test/test_finalization.py

**Comment by joyceerhl** [comment]
> Something must have been stale somewhere as the one I saw while debugging was the old OID.

This is because RemoteHub caches metadata on disk and doesn't invalidate that cache appropriately. I have pushed a fix in RemoteHub to ignore cached metadata and ask for the latest info from network when first initializing the repo. Users who have already seen the bad metadata once like @brettcannon should just be able to update RemoteHub and reload.
