### ISSUE TITLE
Unable to open a line on Github

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3418]
![Recording 2022-03-21 at 11 18 26](https://user-images.githubusercontent.com/900690/159242142-989f9c8e-5ac9-44c0-b69e-0590575c0abb.gif)

Opening a line on GitHub instead opens github.dev again.

**Comment by alexr00** [comment]
This is a feature! If you're already in the browser (vscode.dev or github.dev), we create a vscode.dev or github.dev permalink instead of a github.com permalink.

**Comment by alexr00** [comment]
If a user is in vscode.dev or github.dev then they might prefer a vscode.dev or github.dev link over a github.com link since we already know that they link to use those. This is the justification for the copy permalink command.

For the open permalink command, I can see how this would not be useful in vscode.dev and github.dev. I can update the open command to not use the contextualized permalink.
