### ISSUE TITLE
Can't see the comment on a deleted file

### ISSUE THREAD

**Issue by arsdever** [microsoft/vscode-pull-request-github#3421]
- Extension version: V0.38.1
- VSCode Version: 1.65.2
- OS: MacOS Monterey 12.2.1

Steps to Reproduce:

1. Create a PR in `github` with a file deletion change
2. Add a comment on that file
3. Browse the PR in VSCode to see the comment.

<img width="204" alt="Screen Shot 2022-03-21 at 18 25 35" src="https://user-images.githubusercontent.com/22396275/159282971-7fc28804-b8ba-48fa-956f-2f8470f46d01.png">

**Comment by alexr00** [comment]
The notification for this issue fell through the crack. Upstream issue is here: https://github.com/microsoft/vscode/issues/164729

**Comment by sergei-dyshel** [comment]
@alexr00 
Is there anything planned to fix or work around this issue?

Asking because it got closed as duplicate of https://github.com/microsoft/vscode/issues/164729 but that one was resolved with a solution that just disables commenting on deleted lines in inline view. However the problem remains  - if I open a review that has a comment on deleted line this comment won't be shown in inline view with any notification to user. One could argue that it's not that bad and the comment is still visible in "Comments" bottom view but this is not reliable solution - in file with many comments such comment can be easily lost. 

One workaround would be to look at `diffEditor.renderSideBySide` and notify user about presence of "invisible" comment, but this is not reliable anymore now that we have `diffEditor.useInlineViewWhenSpaceIsLimited` option.

I think that even if using full comment widget on deleted line is problematic in inline view, there still must be some visual indication of that comment explaining to user that they should switch to side-by-side view to see/edit it.

**Comment by alexr00** [comment]
There's no plan right now to make further changes to comments on deleted lines for inline diffs. I can put it on the backlog, but I don't think I will get to it any time soon.

**Comment by alexr00** [comment]
On the backlog: https://github.com/microsoft/vscode/issues/192990
