### ISSUE TITLE
Extension stores tons of `mentionableUsers` in storage

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3436]
Reviewing which entries in UI storage DB are large, I found this extension to win: 

```
"github.pullRequest.repos": {
        "repos": {
            "microsoft/vscode": {
                "mentionableUsers": [
...
```

There are around 10k lines of `mentionableUsers` somehow persisted to storage, but why?

**Comment by alexr00** [comment]
The large number of mentionable users in some repositories results in a lot of network requests. I traded network network requests for storage: https://github.com/microsoft/vscode-pull-request-github/issues/2892

**Comment by bpasero** [comment]
Maybe there is a more efficient way of persisting that data, e.g. by excluding falsified values.

**Comment by alexr00** [comment]
> excluding falsified values

The mentionable users are for showing in suggest when triggered by `@`, so I don't know how we could do this.

> And maybe it should be limited too.

There isn't a good subset of mentionable users to store (we get them from the GitHub API with one API call).  I could decide whether or not to store and prefetch based on how many users there are, but that would mean that triggering @user suggestions in repos with lots of users would be very slow since we would wait to fetch them until suggest is triggered (exactly what caching and pre-fetching is trying to avoid. 

I could delete the cache if it isn't used in some amount of time (2 days?). That way, only users who frequently use the feature will use the storage space.

**Comment by alexr00** [comment]
We store this on disk now.
