### ISSUE TITLE
"View: Show GitHub Pull Request" keyboard shortcut focuses wrong activity view

### ISSUE THREAD

**Issue by dschuessler** [microsoft/vscode-pull-request-github#3451]
- Extension version: 0.40.0
- VSCode Version: 1.66.0
- OS: macOS 12.3.1

Steps to Reproduce:

1. Open the "Keyboard Shortcuts" menu from the command palette
2. Set some non-existing keybinding (e.g. Shift+Ctrl+K or Shift+Alt+Cmd+H) for "View: Show GitHub Pull Request"
3. Press the shortcut set in step 2.

Expected behavior: The Github Pull Request activity view is focused.
Actual behavior: The Explorer view is focused.

I reproduced with all extensions disabled except the Github Pull Request extension.

**Comment by dschuessler** [comment]
Thank you. The underlying issue was that I was unaware that the extension has two views: "Show GitHub Pull Request" and "Show Github". I was unaware of the latter because I just looked for the extension name. This is a little confusing but I got it now.

**Comment by tomwyr** [comment]
@alexr00 I observe very similar behavior to what was initially reported in the issue.
1. Assign unique keybind to `View: Show GitHub` command
2. Press the shortcut
3. Explorer view gets opened and focused instead of GitHub view
I've also tested it in a browser instance of VSCode, followed the exact same steps. The issue wasn't present there.

Currently I have version `0.46.1` of the extension installed, VSCode `1.69.2, macos.

**Comment by tomwyr** [comment]
Also if I start typing *View: GitHub* into the command palette, it shows no results.

**Comment by alexr00** [comment]
My comment in https://github.com/microsoft/vscode-pull-request-github/issues/3451#issuecomment-1090428993 is still applicable.
