### ISSUE TITLE
Remove "Signed in" status bar item

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#360]
Follow up from https://github.com/Microsoft/vscode-pull-request-github/issues/274

The status bar item that shows that I am signed in to GH does not seem to have any purpose other than taking away space from the already crowded status bar. It should be removed in its current form.

Reasons to keep it (maybe, under discussion):
* clicking brings me to PR views
* clicking offers actions to quickly checkout to another PR or back to the branch where I left from

**Comment by ramya-rao-a** [comment]
Or it allows you to sign out. Which is what most "Sign in" buttons change to after signing in.

But I would prefer to have it removed.

**Comment by fabiospampinato** [comment]
IMO this statusbar item is totally useless.

> Or it allows you to sign out. 

I see no "Sign Out" command in the command palette, there should be one there. If somebody really wanted to trigger that command from the statusbar there are already extensions for adding custom buttons to the statusbar that trigger a command.

If you want to have this "feature" bundled with the extension at the very least there should be an option for disabling it.

> Reasons to keep it (maybe, under discussion):
> - clicking brings me to PR views
> - clicking offers actions to quickly checkout to another PR or back to the branch where I left from

Maybe it could be useful in these scenarios, but I would definitely remove the username (who finds that useful?).

**Comment by fabiospampinato** [comment]
Also this statusbar item doesn't have any title set, maybe kind of useless informations such as the username can be written there instead.

As an unfortunate consequence without a title I can't write a proper selector for removing this thing via CSS 😩

**Comment by RMacfarlane** [comment]
Talked about this some more in the UX call today - some other possible functionality would be to have this item navigate to the pull request view in SCM viewlet, or bring up a list of actions that changes contextually based on whether you are in review mode.

We also discussed removing the `Pull Request #` status bar item that appears in review mode. Since the branch information is already shown on the left, for branches that the extension creates, the name will already contain the PR number. Also, there are already other visual indicators for review mode and other ways to get to the description page. The item could be removed and the signed in item could pick up the action of opening the current PR description

**Comment by ELLIOTTCABLE** [comment]
A way to configure this would be great, as there's currently *no other way* to remove this from the statusbar … and I have enough other (more important) things down there that it's crowding out my *Vim-mode command line*, which is … a real problem. /=

**Comment by JacksonKearl** [comment]
VS Code has allowed removing status bar items since the June 2019 release. 
![image](https://user-images.githubusercontent.com/8586769/67536049-2fd63d00-f68a-11e9-97d8-fa52deb573c2.png)

With #1410 clicking the status bar item item will give you options for changing queries, remotes, or signing out of GitHub.
