### ISSUE TITLE
Reviewers/Approvers view is out of sync

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-pull-request-github#3615]
- I switched from one branch to another branch with different PRs and this section went out of sync

<img width="1465" alt="Screenshot 2022-06-13 at 11 32 23" src="https://user-images.githubusercontent.com/10746682/173324722-fc828f3f-6aec-4cf8-904f-a7ce8623b120.png">

**Comment by alexr00** [comment]
@sandy081 what version of GHPRI were you using at this time? Do you remember your exact steps (how did you change branches, did you checkout main, etc.)? I'm not able to repro, but this looks a bit like https://github.com/microsoft/vscode-pull-request-github/issues/3431 but that's been fixed in the last 2 releases.

**Comment by sandy081** [comment]
I was on latest version then but I can't reproduce it now. I will keep an eye on it that if I can repro it again and report it. Closing it for now.
