### ISSUE TITLE
Auto-merge button in viewlet needs window reload to reflect state in GitHub

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#3660]
Testing #3657

Changing the auto merge setting in Github requires a window reload to reflect the state in the create PR viewlet. In the PR editor the state is reflected correctly. 

Before reload:

<img width="1080" alt="capture" src="https://user-images.githubusercontent.com/1931590/176143833-5d6a1a31-e6f4-4bff-a8f7-0a420de193a2.png">

After reload:

<img width="1042" alt="capture" src="https://user-images.githubusercontent.com/1931590/176143948-fc200081-f747-4981-a10b-bcf7a7601900.png">

**Comment by dbaeumer** [comment]
Actually you also need to reload if the type of the allowed auto merges changes:

Before reload:

<img width="1024" alt="capture" src="https://user-images.githubusercontent.com/1931590/176144761-b5468a3a-22cd-471e-b199-52eb378f8aa2.png">

After reload:

<img width="549" alt="capture" src="https://user-images.githubusercontent.com/1931590/176144909-0eaa7ce0-c752-4f1e-bf1f-99d040d7bfec.png">

**Comment by alexr00** [comment]
I was trying to be smart and not make the same request multiple times since it's a value that seldom changes and that's a request that will either slow down extension activation or add delay into the "create" view showing.

 Let me see if there's somewhere I can make the request that won't cause slowness at these important points.

**Comment by alexr00** [comment]
I'll update the state when the "Cancel" button is clicked.
