### ISSUE TITLE
Exit Review Mode fails with git.checkout not found

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-pull-request-github#3671]
Using vscode.dev to created a pull request, I got this error when hitting "Exit Review Mode":

<img width="463" alt="image" src="https://user-images.githubusercontent.com/8599/176314352-a10e0838-57e8-4aef-8c28-d27360c04411.png">

Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.20 Safari/537.36 Edg/104.0.1293.5
Embedder: vscode.dev

**Comment by alexr00** [comment]
Only happens in firefox. I'm also not seeing webviews load, but that's not an issue with this extension.

**Comment by alexr00** [comment]
@joyceerhl `repository.getBranch(main)` will return the first branch that contains the string `main` on Remote Hub. I've fixed the error that @digitarald was seeing, but it's a little unexpected that `getBranch` will return a branch that contains the branch name instead of the one that exactly matches it.

**Comment by connor4312** [comment]
I couldn't hit "exit review mode" on Firefox since it seems like webviews are broken there (https://github.com/microsoft/vscode/issues/142813). Are there alternative verification steps?

**Comment by alexr00** [comment]
You should be able to turn off cookie blocking in Firefox and then webviews will work. Or, you can run the "Checkout default branch" command from the command palette.
