### ISSUE TITLE
[Help] - I clicked "Don't show again" for refresh pull requests and it doesn't seem to pull now

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-pull-request-github#3697]
When PR's update I clicked the "Refresh Pull Request" which shows the prompt on the bottom right which says "Pull" or "Don't Show Again".

I wanted it to pull automatically without me having to keep clicking "Pull" so i selected "Don't Show again". But instead of automatically pulling it seems it now doesn't pull at all? I could be wrong but that seems to be the experience.

Is there a way to revert this change? I coudln't find anything in the settings to revert my choice or set it back to ask? Is there a way to pull without the prompt?

Thanks

**Comment by jasonwilliams** [comment]
> When do you usually find yourself wanting to pull?

maybe the UX is confusing or in misunderstanding something, but I assumed it pulls when I press “refresh pull request”. That was my expectation.

**Comment by alexr00** [comment]
Thanks for the details @jasonwilliams. I can see why you'd want to pull when clicking the refresh button. Opened https://github.com/microsoft/vscode-pull-request-github/issues/3711 to add this.

**Comment by jasonwilliams** [comment]
Thanks @alexr00 

In the meantime, is there anything I can do to bring back the “pull” dialog? Or do I need to delete the extension and reinstall it?

**Comment by alexr00** [comment]
@jasonwilliams I've merged the change to use a setting instead of the user-unfriendly global state. If you install the [pre-release version](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) of the extension _**tomorrow**_ (It didn't make it into the daily build today. The build is usually available by 10:00 GMT) then you'll have the setting `githubPullRequests.pullBranch` which you can set to `prompt`.
