### ISSUE TITLE
无法看到本地修改

### ISSUE THREAD

**Issue by Jenniferazeng** [microsoft/vscode-pull-request-github#3803]

**Comment by Jenniferazeng** [comment]
修改后，无法从源代码管理菜单看到修改的文档

**Comment by alexr00** [comment]
Thanks for creating this issue!

Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.

In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.

Otherwise, we have marked this as needing translation and a community member may be able to help out.
