### ISSUE TITLE
Checkbox likes to play Simon Says

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#3972]
1. Double click a checkbox

🐛 It will repeat what you just did a few milliseconds later

![Recording 2022-09-21 at 16 36 44 (1)](https://user-images.githubusercontent.com/22350/191533966-e06d03e3-20fc-4e97-b3ae-4c3f6225a5e9.gif)

**Comment by alexr00** [comment]
This happens because we're still waiting to complete the GitHub API calls required for the first click when you make the second click:
1. First click, checkbox is instantly checked. API to mark the file as viewed gets called
2. Second click, checkbox is instantly unchecked. API to mark the file as unviewed gets called
3. First API call marking the file as viewed returns. We check the box because the file is now viewed
4. Second API call marking the file as unviewed returns. We uncheck the box because the file is now unviewed.

Seems like we need some debouncing.

**Comment by andreamah** [comment]
I don't see this on the latest prerelease. @joaomoreno would you like to also double-check, since you originally saw the bug?
