### ISSUE TITLE
UX issues with adding a comment

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#4]
We show the Add Comment action in the whole file, but comments can only be added within diff hunks.
- I don't have any understanding of where I can add comment.
- The notification is out of my field of sight when it slides in.
- The message talks about diff hunks which is not a term I need to know when looking at a PR

**Comment by rebornix** [comment]
As we discussed last week, we want to put some decorations in the gutter to improve the experience. The gutter consists of three areas, glyph, line number and line decorations(from left to right). Glyph area is now mostly used by breakpoint, line decorations are occupied by folding and git inline decorations. 

In GitHub PR/Review scenario, there are two things users need to be aware of 

1. Diff Hunks. Diff Hunks are content changes ranges with some context (several lines before and after the changed ranges). We are allowed to leave comments directly on diff hunks without any workaround at this moment.
2. Some visual affordance that users can see and interact with. Right now we show a comment icon which is positioned similarly to the light blub.

To solve the first problem, we can put another column in the gutter, similarly to how we show the git dirty decorations

<img width="448" alt="image" src="https://user-images.githubusercontent.com/876920/43191791-7acc7c84-902e-11e8-93d8-9cd27f2058c1.png">
*Orange: Diff Hunk from PR, Green: Local Git Diff*

The catch here is users will get confused with difference between diff hunk ranges and local git diff ranges, the former one is larger than content change ranges most of the time.

Let's say users are already familiar with diff hunk concept, we can put a `+` icon to the diff hunk decorations when users hover on them and then when they are clicked, we can show the Add New Comment Widget.

![clickablegutterdecoration](https://user-images.githubusercontent.com/876920/43192019-099796b0-902f-11e8-97e3-041f26405fa2.gif)

Users won't be confused with on which range they can create new comments.

**Comment by rebornix** [comment]
Right now we have this `commentingRanges` property in our Comment API. For GitHub, this property is necessary as we can only leave comments on diff hunks in a Pull Request. If we don't have this limitation and we can leave comments anywhere, most of the problems mentioned above can be gone. We only need to think about where to draw the *Create New Comment* affordance.

**Comment by rebornix** [comment]
The gutter looks less crowded if we put the diff hunk decorations to the left side of the line numbers

<img width="710" alt="image" src="https://user-images.githubusercontent.com/876920/43207559-e0f37e96-905a-11e8-803c-cf40600d6d0f.png">

![clickableglyphdecoration](https://user-images.githubusercontent.com/876920/43208165-61822b1a-905c-11e8-9d1d-ad45911d8684.gif)

**Comment by kieferrm** [comment]
I prefer the diff hunk decoration next to the git change decoration. It's easier to make the connection that they two are talking about related issues. If there is bit more space between the two lines and the colors for the diff hubs are more subdued it could work.

Currently, the git change decoration expands as soon as the mouse enters the gutter. It stays wide while the mouse is in any of the three areas of the gutter. In your gif in 
https://github.com/Microsoft/vscode-pull-request-github/issues/4#issuecomment-407691448 that's not the case.

Also, I wonder what it looks like if we play with the margin between the diff hunk decoration and the git change decoration.

**Comment by rebornix** [comment]
### Hover for creating new comment

When we hover on the gutter, if there is a git diff decoration, the decoration will increase its width from 3px to 9px and then when you click on it, an inline diff editor will show up.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/876920/43240015-33a05fb2-90c7-11e8-8b76-a15b3fbfa7ea.png">

Once the git diff decoration is 9px wide, it only gives us 2px left on the left side. As you can see above, the diff hunk and git diff decorations start to overlap. We use the same ux for hovering on diff hunk decorations:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/876920/43240158-afbbd2b6-90c7-11e8-80a8-7775c3b54d37.png">

When we hover on it, diff hunk decorations will expand and show a `+` sign. For now, the diff hunk decorations always expand and when a click event triggers, a new comment widget and an inline diff editor will show up at the same time but positioned properly. The problem here is these two decorations overlap more and we only want one mouse click handler at one time instead of two.

**Comment by RMacfarlane** [comment]
Since what we're trying to visualize here is the commenting ranges of a document, which just happen to be diff hunk ranges in this case, I think it's less important to align with git diff decorations. I liked having the decorations on the left side of the gutter, this seems a little crowded to me and harder to immediately understand what line is indicating what. Could we try using a similar color to the comment icon for the decoration instead of green? The spacing on hover in the last gif looks good to me.

When clicking on a comment in the comments panel, I think it would be more useful to show a writeable diff view than just the file on disk. The file itself isn't being reviewed, the changes to it are, and showing just the file misses out on viewing deletions. Do these decorations also get shown in diff editors? Would it make sense to try to restrict commenting to diff views for this extension since comments are tightly coupled with diff hunks?

**Comment by rebornix** [comment]
Thanks @RMacfarlane . Using some grey color to align with the comment icon works better.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/876920/43297281-fcb997d6-9182-11e8-866f-374da7328b18.png">

In above image,

* git diff decorations are moved to the right by 1px
* git diff decorations width on hover are decreased to 7px from 9px. With above change, it still doesn't overlap with folding
* diff hunk decorations are grey

**Comment by rebornix** [comment]
The diff hunk commenting decorations landed in vscode master now.
