### ISSUE TITLE
Prefetch the next file in a PR review

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#4039]
I (and I think a lot of people) review PRs sequentially, or at least semi-sequentially (maybe I focus on one folder first) based on the order in the file tree. When I open a new file, it takes about a second for the file and its content to load. It'd lead to a snappier experience if the extension automatically preloaded the next file in the tree so it's ready instantly when I click on it.

**Comment by alexr00** [comment]
I think we'd really benefit from extension trees knowing when a tree item is rendered for this, since really anything that's currently visible in the tree is a good candidate for fetching additional data. I'll propose this API in a future milestone. 

For now, I'll add pre-fetching for every file in a checked out PR when the number of files is < 20.
