### ISSUE TITLE
Does not display PRs from submodules

### ISSUE THREAD

**Issue by adamhewitt627** [microsoft/vscode-pull-request-github#413]
Issue Type: <b>Bug</b>

1. Clone a repository with a submodule, recursively.
2. Open the root repo. Open pull requests in the submodule do not appear in the list. (they _do_ appear when opening the submodule's folder directly)

Extension version: 0.1.2
VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz (8 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.80GB free)|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by pjbtoo** [comment]
I have the same scenario. It display's PR's from my main root repo. The root repo has a bunch of submodules and I never see any PR's from these.

**Comment by RMacfarlane** [comment]
This should be fixed with the change for https://github.com/microsoft/vscode-pull-request-github/issues/1936, submodules should now show up as a separate entry in the tree. Here I added `pullrequest-demo` as a submodule in this repo:
<img width="400" alt="Screen Shot 2020-09-04 at 11 08 52 AM" src="https://user-images.githubusercontent.com/3672607/92272811-20757200-ee9f-11ea-864a-b784a3b82a64.png">
