### ISSUE TITLE
Change default button in review comment from "Add Comment" to "Start Review"

### ISSUE THREAD

**Issue by CombeeMike** [microsoft/vscode-pull-request-github#4152]
As the title states I'd really like to have the default action button in the comments dialog switched when adding a comment.
If you don't want to change this in a "hard coded" way, I'd also be fine with a new setting which allows me to adjust this.

Something like `Default comment submit button when not in review: Add Comment | Start Review`

# Reason

I usually write the comment & submit with the keyboard without looking at the action buttons.

It already happened multiple times to me that I just left multiple "lose comments" whilst I actually wanted to add comments to a review since I simply forgot to actively use the `Start Review` button in the first comment.

Those lose comments all lead to single notifications for my co workers (the reviewees) which is rather unfortunate as I don't want to spam their inboxes.

**Comment by alexr00** [comment]
I'm worried about changing the default for everyone, as the GitHub behavior around review comments can be confusing: the comment is "pending" until the review is submitted. This can result in users making comments and then not understanding why they are not visible to others. Because of this, the default for most people should still be "Add Comment".

**Comment by CombeeMike** [comment]
A setting for changing the default perfectly fine! I'm really looking forward to this, thank you very much!
