### ISSUE TITLE
No way to `remove` or `rename` remote `upstream`

### ISSUE THREAD

**Issue by mustard-mh** [microsoft/vscode-pull-request-github#4209]
## Steps to Reproduce:

- Start with this Extension with some forked repo
- Remove `upstream` remote
```
git remote remove upstream
```
- `upstream` will be back
- Logs
```
$ git remote -v
origin  https://github.com/gitpod-io/openvscode-server.git (fetch)
origin  https://github.com/gitpod-io/openvscode-server.git (push)
upstream        https://github.com/microsoft/vscode.git (fetch)
upstream        https://github.com/microsoft/vscode.git (push)
$ git remote remove upstream
$ git remote -v
origin  https://github.com/gitpod-io/openvscode-server.git (fetch)
origin  https://github.com/gitpod-io/openvscode-server.git (push)
upstream        https://github.com/microsoft/vscode.git (fetch)
upstream        https://github.com/microsoft/vscode.git (push)
$ 
```
- code https://github.com/microsoft/vscode-pull-request-github/blob/7c3437d461ca2e611a71dbdc638abf67b8595ba3/src/github/folderRepositoryManager.ts#L643

**Comment by alexr00** [comment]
@mustard-mh you should be able to rename it if you also add the new name to the setting `githubPullRequests.remotes`. The extension doesn't work if the parent repository of a fork isn't included in the git remotes. Why do you want to remove the `upstream` remote?

**Comment by mustard-mh** [comment]
@alexr00 Yeah, we want to rename it because of this issue https://github.com/gitpod-io/gitpod/issues/14531#issuecomment-1319020267

When we are going to fork a forked repo:

- Project already has `upstream` and `origin` remote
- If we want to publish a branch to not-owned repo (that `origin` mentioned above), VSCode will prompt ask to **Create a Fork**
- In this case `upstream` already exists, [it will cause an error](https://github.com/microsoft/vscode/blob/1ac5ea41e191611f130e0ae216e4a5dd1966f1f5/extensions/github/src/pushErrorHandler.ts#L70)

And we have other options to do it: rename or delete`upstream` ourselves first. But GH PullRequsest extension just keep re-create upstream

**Comment by alexr00** [comment]
@mustard-mh does this work for you?
- Add the name you want rename `upstream` to in the setting `githubPullRequests.remotes`.
- Rename `upstream`.

**Comment by jeanp413** [comment]
@alexr00 updating `githubPullRequests.remotes` works but I feel it's not obvious, I'd expect all git commands work as expected and are not overridden silently by the GHPR extension, running `Git: Remove Remote` command doesn't work either.

I think it's fine for GHPR extension to set upstream remote when opening/reopening a folder but then it should show some dialog to confirm or cancel it

**Comment by alexr00** [comment]
A few reasons why I don't want to require user confirmation before adding the upstream:
- In most cases, users don't care if we automatically add an `upstream` remote (supported by this only being reported as an issue 6 days ago) and it provides a much better experience for users.
- Many of our users are students or otherwise new to source control. They won't know how to answer a confirmation dialog about this and making them go through additional steps provides additional places for them to make a choice that they don't actually want and get stuck.

How about I add a setting for controlling whether we ever try to add the upstream remote? That way the extension will never add the remote and you'll be able to delete or rename your remotes however you wish. 

We can even go one step further: if we notice that we've add the same upstream remote twice in one "session", which would imply that you're trying get rid of or otherwise modify the upstream remote that we depend on, we can show a notification suggesting that you change some settings.

**Comment by jeanp413** [comment]
> We can even go one step further: if we notice that we've add the same upstream remote twice in one "session", which would imply that you're trying get rid of or otherwise modify the upstream remote that we depend on, we can show a notification suggesting that you change some settings.

Sounds good, thanks :+1:

**Comment by froboy** [comment]
@alexr00 as the original reporter of the Gitpod issue I really appreciate your solution - protecting existing functionality for novice users but attempting to take notice when folks doing advanced stuff (like me in this situation) try to push against it. Thank you!

**Comment by joyceerhl** [comment]
> Verify that it gets added back

I tried this with the GHPRI repo and both `origin` and `upstream` remotes, but after deleting `upstream` using `Git: Remove Remote`, I do not see the remote getting added back. Any tips?

**Comment by alexr00** [comment]
@joyceerhl if you don't see it get added back, can you refresh the git SCM view then wait a few seconds? It's possible the git event was lost.

**Comment by joyceerhl** [comment]
I still do not see the remote getting added back after waiting a minute, maybe someone else should verify

**Comment by roblourens** [comment]
This worked for me
