### ISSUE TITLE
The review requires status icon is not very informative

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#4259]
Testing #4257

<img width="364" alt="image" src="https://user-images.githubusercontent.com/1931590/204499121-52577f08-563e-4932-8a9f-09c4ab362b49.png">

What's about an icon showing a pen and a piece of paper.

**Comment by alexr00** [comment]
I think we need to go with very simple icons since it can look very busy otherwise. We don't currently have a pen and paper icon, but I suspect it would look too busy. We have a pencil icon, but that's often used to indicate that you can modify something. 

Some options:

`book` (too busy looking)
![image](https://user-images.githubusercontent.com/38270282/204502233-743febc6-f460-47b1-a694-d129670d35c1.png)

`eye` (this one's not bad)
![image](https://user-images.githubusercontent.com/38270282/204502845-439fe0a5-3180-4948-8660-8ca0a0406024.png)

@daviddossett, what do you think?

**Comment by rzhao271** [comment]
For me, the fact it was grey made the PR seem unimportant to me. I'd think the PR would be important to me if it was assigned to me, though, or maybe if I was mentioned on it. Therefore, I wonder whether the "needs review" icon should be saved for those specific PRs?

**Comment by daviddossett** [comment]
Should it use the same color/filled icon as GH does to help convey that something is required? Screenshot in #4272

**Comment by alexr00** [comment]
I'll change to a yellow `circle-filled` as suggested in https://github.com/microsoft/vscode-pull-request-github/issues/4272
