### ISSUE TITLE
Collapse state not preserved in Issues view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#4359]
1. Open PR viewlet
2. Collapse some nodes in the PULL REQUEST view and some in the ISSUES view
3. Reload
4. Notice how the collapse state is preserved in the PULL REQUEST view, but it is not preserved in the ISSUES view 🐛 

![Recording 2022-12-22 at 18 19 34](https://user-images.githubusercontent.com/1926584/209190645-c033e8ae-eac8-4b28-866f-a45e6467c1a2.gif)

**Comment by alexr00** [comment]
We can easily start preserving the collapse state in Issues too. The reason we have this difference now is because we fetch issues for all queries in advance to populate the `#` completions and because they're cheaper to fetch than PRs. Preserving the collapse state is less important there because of this. We preserve the collapse state in PRs because they are expensive to fetch, but if a user has already indicated that they want to display the PRs for a query, then we can guess that they'll want to see those PRs again.

**Comment by isidorn** [comment]
Thanks for the explanation.
It makes sense what we do for PRs. Since you say preserving the collapse state for issues is easy - I suggest we do just that if you agree :)
It will make it consistent will all other tree views in VS Code. I think it is rare that we do not preserve View State.

Also my use case is that I never care about my backlog issues. I always want it collapsed to save on screen real estate.

**Comment by isidorn** [comment]
Awesome! 
@alexr00 how often do we release a new pre-release version in general?

**Comment by alexr00** [comment]
Pre-release build are done Monday-Thursday. Looks like it's failed the last couple runs though so running again now.
