### ISSUE TITLE
Don't reload entire DOM when getting data from GitHub

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vscode-pull-request-github#4371]
A few days before Christmas, this extension started to refresh the PR view and the active pull request panel more often. The problem is that the entire DOM will be recreated when the state changes. While the contents of the "add comment" textarea in the PR view survive the reload, unsaved changes to the PR title/ description do not survive this which is very annoying when editing it. 

Steps to Reproduce:

1. Open PR view
2. Change PR title but don't submit your changes
3. Wait a few minutes until PR view reloads (manually reload PR view doesn't reproduce the issue entirely)
4. Notice in VS Code dev tools that the entire DOM disappears and is recreated and changes to e.g. the PR title are not preserved

Expected behaviour:

To not reload everything and therefore not loose any unsaved changes. When you pull refresh on the GitHub website, e.g. while writing this issue, no data is lost although the entire DOM gets recreated. However, GitHub is able to show new comments/ commits without reloading everything.

**Comment by philip-n** [comment]
Just had the same issue multiple times, both when using github.dev to review a PR and when doing it within VSCode with this extension.

I like to include some high-level feedback in the review summary, so writing in an actionable way can take a couple of minutes. It is quite unexpected to have the form spontaneously reload and clears the review summary field :/

On a slightly related note (not exactly this issue, but potentially fixable in the same way?): It would be great if the review summary could also be preserved when navigating between files, e.g. "Start writing summary" --> "Jump to file XYZ to check something" --> "Go back to summary" --> "Continue with previous state (instead of starting with a blank field)".
