### ISSUE TITLE
not working in vscode custom build

### ISSUE THREAD

**Issue by ashwin31** [microsoft/vscode-pull-request-github#4384]
- Extension version: 0.56.0
- VSCode Version: 1.72
- OS: ubuntu 20.04

Steps to Reproduce:

1. git pull https://github.com/microsoft/vscode.git .
2. yarn
3. ./scripts/code-server.sh  --without-connection-token
4. open the vscode in port 9888
5. install GitHub Pull Requests and Issues
6. then we can't see signin button but seeing empty panel

![Screenshot from 2023-01-06 22-15-50](https://user-images.githubusercontent.com/365610/211058006-3cd1ef0d-4791-4e3c-a0fb-cf333db83b46.png)

I am using https://open-vsx.org/ as plugin repository

I guess that I am missing some configuration parameter in vscode product.json 
can anyone tell me how to use it with https://github.com/microsoft/vscode.git

**Comment by alexr00** [comment]
> then we can't see signin button but seeing empty panel

It looks like you don't have a git repository open. If you open a folder that's backed by a git repo then you'll see the sign in button.

**Comment by alexr00** [comment]
Could you set `"githubPullRequests.logLevel": "debug"`, reload then share the output from GitHub Pull Request and form the chrome dev tools developer console?

**Comment by abhijeet-1110** [comment]
Hello @alexr00 ,

I got this error on the console.
  ERR [GitHub.vscode-pull-request-github]: file/share is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["contribShareMenu"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api GitHub.vscode-pull-request-github

**Comment by alexr00** [comment]
That's probably why the extension doesn't work in your custom build then. We often use our first party extensions to test out proposed API so that we can gain confidence in it before finalizing.  When we make a product build of VS Code we indicate which extensions are allowed to use proposed API (more on proposed API here: https://github.com/microsoft/vscode/wiki/Extension-API-process). I don't know what you need to do to enable this for a custom build though. You could see what other forks of VS Code do and then do the same.

**Comment by abhijeet-1110** [comment]
Got it.Thank you so much @alexr00
