### ISSUE TITLE
Comments panel appears when expanding tree node

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode-pull-request-github#4390]
👋

- Extension version: v0.57.2022122310 (pre-release)
- VSCode Version: Version: 1.74.3 (Universal)
- OS: 12.6.1 (21G217)

Steps to Reproduce:

1. Open GitHub view
2. Expand an item from the pull requests view
3. :bug: comments panel appears even though it was hidden previous

https://user-images.githubusercontent.com/35271042/211974694-468d01a5-4280-4093-b835-3616085bcb31.mp4

**Comment by alexr00** [comment]
👋

It looks like the Comments view is just restoring, as expected:
1. You have the vscode-symbols workspace open
2. There are comments in the vscode-symbols workspace so the Comments view exists.
3. You close the workspace.
4. Next time you open the vscode-symbols workspace there are no comments in the workspace so the Comments view is hidden.
5. You expand the PR tree node and now comments exist in the workspace (via a commenting range provider).
6. The Comments view is un-hidden because comments now exist.

I think the best fix is for the extension to register in a way that causes the comments view to always be un-hidden.
