### ISSUE TITLE
Show a message when opening a file change redirects to GitHub

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#442]
If you open a file from a PR that contains an unsupported file type, it automatically opens your browser and navigates to the GitHub website and shows the preview. This is quite jarring and we should provide a better experience by showing a message and giving the user an option to preview on the web.

**Repro steps**
1. Navigate to PR that has changes to an svg/ttf/unsupported file type (i.e. https://github.com/jesseweed/seti-ui/pull/504)
2. Click on file in the GitHub PR Viewlet
3. You are re-directed to the GitHub that shows the file

**Expected**
1. Show a message that explains that file is not supported with a link to preview on the web

**Comment by RMacfarlane** [comment]
Updated the title, since there are other situations where we open the file on GitHub that we should explain, for example when it's too large. The GitHub API doesn't actually return a reason for why the patch isn't include, so we can either try to infer it or have a more generic message

**Comment by thisissami** [comment]
Yeah I 100% agree on this. It definitely breaks my flow when doing a peer review in VSCode to unexpectedly have my browser open when clicking on the next file in the directory. In my case it was purely a renamed file - I see no reason why it can't just be shown in VSCode, or at the very least - a message saying something along the lines of `This has solely been renamed and is accordingly not available here. Do you wish to view it on GitHub?`

**Comment by eamodio** [comment]
Unsupported types are one thing, but for a file that is too large (or doesn't have the patch included), can't you just get the whole contents of the file at that version to provide the diff?

**Comment by RMacfarlane** [comment]
@Maskime Thanks for your feedback! This sounds similar to https://github.com/microsoft/vscode-pull-request-github/issues/1160.

I've previously reached out to GitHub to try to clarify what the exact circumstances are for patches not being returned and am still waiting for a response. This is definitely a pain point! With some refactoring we may be able to handle this by just making additional network calls when trying to open the diff to resolve the whole file contents of both sides instead of working with a patch.
