### ISSUE TITLE
Editing a "Suggested Change" comment does not reflect new change.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-pull-request-github#4454]
Testing #4434

Editing and hitting "Save" does not update the comment. 
Clicking "Make a Suggestion" in edit mode adds the same lines again.

**Comment by eleanorjboyd** [comment]
follow these steps and got the ```suggestion markdown ``` text to input again.

1. make a suggestion
2. open the comment via the edit button
3. click the `make a suggestion` button again
4. the extension will add ```suggestion markdown ``` to the comment again. It will only do it once each time you click edit
5. So for example if I click `make a suggestion` twice without saving it will only add ```suggestion markdown ```once

**Comment by alexr00** [comment]
@eleanorjboyd is this the kind of thing that you're seeing? Where multiple suggestions get rendered as one?

![image](https://user-images.githubusercontent.com/38270282/214812147-53524c8a-5298-46ff-ae56-173b516d578f.png)

Can you share a screen shot?

Think this bug is still verifiable. To verify:
1. Make a suggestion and save the comment.
2. Edit the comment and change a few characters in the suggestion.
3. Save the comment.
4. Verify that the suggestion in the comment includes your changes.

**Comment by eleanorjboyd** [comment]
following those verification steps you included does work as expected! This is the issue I came across, I am not sure if it is just a design choice but the `make suggestion` button is clickable multiple times when first creating the comment then when editing the comment you can only click it once.

https://user-images.githubusercontent.com/26030610/214892515-6933053c-19fe-4a55-bd0a-d856848fd54d.mov

**Comment by alexr00** [comment]
@eleanorjboyd created a new issue for that: https://github.com/microsoft/vscode-pull-request-github/issues/4470
