### ISSUE TITLE
Missing pull request number on a head of title

### ISSUE THREAD

**Issue by ryo-yamaoka** [microsoft/vscode-pull-request-github#4463]
Please tell me how to show number on a head of title if this issue is specification.

- Extension version: [0.56.0](https://github.com/microsoft/vscode-pull-request-github/releases/tag/v0.56.0)
- VSCode Version: Version: 1.74.3, Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
- OS: macOS Monterey 12.6.2 (21G320)

Steps to Reproduce:

1. Show pull requests in the side bar

### 0.56.0

Missing PR number

![Screen Shot 2023-01-26 at 12 13 26](https://user-images.githubusercontent.com/20574684/214750982-03a257c7-c200-4514-b5cc-9821b99cb68b.png)

### 0.54.1

Shown PR number

![Screen Shot 2023-01-26 at 12 12 26](https://user-images.githubusercontent.com/20574684/214751002-5a072d8b-0ddf-4a37-bfab-611dcfb5d1be.png)

**Comment by alexr00** [comment]
I removed the PR number from the list as it was taking space away from the PR title.

**Comment by ryo-yamaoka** [comment]
I see, could we make that an optional?
I often get review requests in repositories with lots of PRs, so it is easier to see them if they are numbered.

**Comment by prenaux** [comment]
In our case the title is not useful, we use the number since its much easier to track down through tickets in various tools and to communicate through chat/email/etc. We also use stacks of PRs and without the number its impossible to track which is which, a stack will have sequential numbers so you know in which order to do reviews - without them it becomes a lot harder to do, to the point where we cant really use this extensions as stack can have 5+ PRs and trying to remap them from title is just not possible.

Please make it an option.
