### ISSUE TITLE
Comment submit keyboard needs to be configurable

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode-pull-request-github#451]
#300 I found this reported but should note that CTRL + ENTER is used by breadcrumbs feature and many other things in VS Code by default.

I would not call this more a bug than a feature request, but will maintainer decide...I can resubmit if needed.

The keyboard mapping does not exist that allows us to modify this on Windows. The issue though is that CTRL + ENTER is used for other items in VS Code (e.g. breadcrumbs, etc.). So we are not able to use the mapping by default and have to click the button, at least in Windows.

**Comment by RMacfarlane** [comment]
This should be fixed in this next release of VSCode, there's now a `workbench.action.submitComment` command that can be configured to a different keybinding

There's also `workbench.action.addComment`, which starts a new comment on the current line or toggles the existing comment open, that has no default keybinding

https://github.com/Microsoft/vscode/commit/72a18e636b2d9f1ad866f0c9b3563b7d91973809
