### ISSUE TITLE
github-pr-owner-number is always back in .git/config whenever I open vscode with PR already merged

### ISSUE THREAD

**Issue by alanwilter** [microsoft/vscode-pull-request-github#4596]
I've seen several related bugs but none exactly like mine.

I'm using:
```
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:06.752Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No
```

My project has only `main` branch and no PR opened in GitHub.

Even if I manually remove line:

```
github-pr-owner-number
```

from my `.git/config`. Everytime I open my project in `vscode`, it will write that line back annoying me about a PR long merged.

How can I get this sorted?

**Comment by alexr00** [comment]
Setting this setting should prevent that from being added to your git config

```
"githubPullRequests.useReviewMode": {
  "merged": false
}
```

**Comment by alexr00** [comment]
> First, if doing as said, why the warning?

I failed to copy the whole setting. You fixed it correctly.

> Second, whenever I open my workspace in vscode, vscode will go do write this again in my .git/config:

I'm not able to reproduce this with `"githubPullRequests.useReviewMode"` set as described above. My repro steps:
1. Clone a GitHub repository that has a merged PR associated with the `main` branch.
2. Open the .git config and see a `github-pr-owner-number` associated with the `main` branch.
3. Set
```
"githubPullRequests.useReviewMode": {
		"merged": false,
		"closed": false
	}
```
4. Manually delete the `github-pr-owner-number` from step 2. 
5. Reload VS Code.
6. Open the .git config and see that the `github-pr-owner-number` has not come back.

> Where is vscode fetching this info? Because I can't find it in GitHub or with git commands.

We use GitHub's API to see if there's a PR associated with the current branch. This is so that we can auto detect when you're on a PR branch and enter review mode.
