### ISSUE TITLE
Comments do not show reactions

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#46]
Reactions are often important to show acknowledgement.

![image](https://user-images.githubusercontent.com/2193314/41948159-4339145a-7970-11e8-815e-0a0bb13b1f07.png)

vs

![image](https://user-images.githubusercontent.com/2193314/41948184-5776f5e0-7970-11e8-9977-8b88b1146e85.png)

**Comment by xavdid** [comment]
+1 here! I find reactions very useful during a review because it allows me to mark comments on a PR as addressed or ignorable.

**Comment by JeffreyCA** [comment]
I'd like to work on this, where is a good place to start?

**Comment by RMacfarlane** [comment]
@JeffreyCA The comments widget that's shown in editors is implemented by VS Code itself. The extension just passes data about the position, text, etc. of the comment. So to get this to work, we actually need to propose new API for VS Code to allowing rendering additional data. I would hold off on working on this issue because of that

**Comment by rebornix** [comment]
It's already supported now.
