### ISSUE TITLE
Re-request review from one reviewer will remove other reviewers.

### ISSUE THREAD

**Issue by np-22** [microsoft/vscode-pull-request-github#4830]
- Extension version: v0.64.0
- VSCode Version: Version: 1.78.2 (Universal)
- OS: macOS 13.4 (22F66)

Steps to Reproduce:

1. (I am on Github Enterprise) Publish a PR. 
2. Get reviews from one reviewer. 
3. Push changes and re-request review from this review.

All other reviewers are removed except this reviewer.

**Comment by alexr00** [comment]
> re-request review from this review.

Can you show a screenshot of where you're re-requesting a review from the reviewer?

**Comment by alexr00** [comment]
Actually, I can repro.

**Comment by np-22** [comment]
Thanks for looking into this issue @alexr00 !

**Comment by kudamhazo** [comment]
To reset or dismiss all approvals on a Pull Request (PR) using GitHub's GraphQL API, you would need to perform two main steps:

1. Fetch all the reviews of the PR.
2. Dismiss each review that has been approved.

Below is the guide on how to do it.

## Step 1: Fetch all the reviews of the PR

To fetch all the reviews of the PR, you would use the `pullRequest` endpoint with the `reviews` field. Here is an example query:

```graphql
query {
  repository(owner:"OWNER", name:"REPO") {
    pullRequest(number:PR_NUMBER) {
      reviews(first: 100) {
        nodes {
          id
          state
        }
      }
    }
  }
}
```

Replace `OWNER`, `REPO`, and `PR_NUMBER` with the owner's username, repository name, and pull request number respectively.

This will return a list of all reviews and their states.

## Step 2: Dismiss each review that has been approved

For each review that is in the `APPROVED` state, you would call the `dismissPullRequestReview` mutation. Here is an example:

```graphql
mutation {
  dismissPullRequestReview(input:{pullRequestReviewId:"REVIEW_ID", reason:"DISMISS_REASON"}) {
    clientMutationId
  }
}
```

Replace `REVIEW_ID` with the id of the review you want to dismiss, and `DISMISS_REASON` with the reason for dismissal.

Please note that in order to dismiss a review, the authenticated user must have write access to the repository, or be the author of the review. The review must also be in an `APPROVED` or `CHANGES_REQUESTED` state.

Remember, due to GitHub's API rate limit, if you have a large number of reviews to dismiss, you may need to handle this in your code.

**Important Note:** GitHub's GraphQL API does not currently have a way to dismiss all reviews at once, so you have to dismiss them individually.
