### ISSUE TITLE
Go to definition would be usefull

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-pull-request-github#486]
I think that being able to go to definition (if in different file ask user if they want to open changes or file) or at least peak definition. I find myself opening up the original often file and using go to definition.
Also I'm not sure if this is the right place to ask for this but if the changes view could keep it's scroll position when swapping to another file, that would be really handy.

**Comment by danvk** [comment]
In general it seems like all the intellisense features are disabled for diff views. I assume this is intentional but I'd love to see this added. In my mind this is the main win of doing code reviews in your editor.

**Comment by scrossan-crown** [comment]
I agree, I noticed that the diff window is read only and that could be the reason you don't get any intellisense features. One thing I've found that's good about that is you can do some changes check if they work then go to the diff view and suggest them and the diff view shows the unchanged code.

**Comment by alexr00** [comment]
This works now.

**Comment by LondonAppDev** [comment]
Hey @alexr00, was point 1 meant to say "The definition *is* part of the PR?" I ask because I have a PR checked out and I can only "Go to Definition" for items that are included in that PR (using Python).

**Comment by alexr00** [comment]
Thanks @LondonAppDev you are correct!

**Comment by glarsennordic** [comment]
@alexr00 

Even after right clicking on the PR and selecting "checkout this PR", I still cannot use F12, and the "go to definition" option in the context menu is still missing.

I assume I'm doing something wrong, but googling the issue has proved quite impossible: "Github PR extension intellisense" will match basically any intellisense issue on any github repo. I was only able to find this Github issue by searching the repo directly, an this appears to be the only issue regarding the matter, so asking here seems the most appropriate.

How can I get intellisense working within the diff view brought up by this extension, and/or are there any docs out there describing the process?

Thank you for your time

**Comment by alexr00** [comment]
@glarsennordic let's confirm some things first so I can make sure I'm understanding your problem:
1. What programing language is this? 
2. Do you already have an extension installed that provides intellisense for this language?

Assuming your answer to question 2 is "yes", here's what I think is happening to you, please confirm if you agree!
1. Go to the Pull Requests view.
2. Expand a Pull Request there. Open a diff. Keep this diff open.
3. Decide you now want to check out the PR and right click -> checkout PR.
4. From your tabs or your currently open editors, you navigate back to the diff in step 2. 
5. Intellisense does not work in this diff. This is happening because the diff came from the "Pull Requests" view instead of the "Changes in Pull Request" view.

Does that sound like what's happening? If so, I agree that this behavior is very confusing and unintuitive. I think this will be a large change to fix, so I've opened https://github.com/microsoft/vscode-pull-request-github/issues/3631 to track it.
