### ISSUE TITLE
Conversations marked resolved via the web require a full window reload to appear in VS Code

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4875]
1. Have a PR open in both GitHub.com and VS Code
2. Mark a comment on that PR resolved on GitHub.com
3. :bug: comment doesn't become resolved in VS Code

Similarly, if I leave a comment on GitHub.com after opening VS Code, that comment doesn't appear in the comments widgets or panel, although it does appear on the PR description

**Comment by alexr00** [comment]
> Have a PR open in both GitHub.com and VS Code

Is the PR checked out? We should be refreshing comments every 2 minutes. Do you get the comment if you use the refresh action on the changes view?

**Comment by joyceerhl** [comment]
Yeah the PR is checked out. 2 minutes is longer than I hung around waiting for the comments to appear 😅

**Comment by alexr00** [comment]
Confirmed that after 2 minutes the resolved state is synced. 

We can fetch a lot of data for a PR. I'm not sure refreshing more frequently than 2 minutes is worth it, especially when the refresh button on the "Changes" view will also fetch changes immediately.

**Comment by Thomas1664** [comment]
I have the same issue and it's very annoying. Currently, pressing refresh isn't really an option because it reloads everything and things like scroll position get lost. This is the reason why it feels for me more natural to open the PR in GitHub instead. Ideally, you won't notice a refresh in the UI at all because React only updates components with changed state. See also #4371.

**Comment by alexr00** [comment]
@Thomas1664, there's a refresh comments button that should do what you want. It's available on the comment widget and in the Comments view.
