### ISSUE TITLE
Working with multiple repositories in workspace

### ISSUE THREAD

**Issue by AlexSenchenko** [microsoft/vscode-pull-request-github#493]
Hi,

My project contains multiple repositories. Typical front, back + services.

Need that extension scan all repos in workspace and bring all PR's to front. 
Now I see that PR's are not shown for multiple repos in workspace.

Thanks.

**Comment by ggriffithsIDBS** [comment]
This would be awesome, we have many small repos, which i have checked out into one workspace, this feature working across multiple repositories would be fantastic

**Comment by aarongustafson** [comment]
It would also be good to be able to ignore a remote (I push to a production build server which is a remote, for instance).

**Comment by scrossan-crown** [comment]
I'd love to be able to switch between my "Source Control Providers" in vscode and it retrieve the pr's for that repo when I click "Refresh Pull Request List"

**Comment by ronjouch** [comment]
> *I'd love to be able to switch between my "Source Control Providers" in vscode and it retrieve the pr's for that repo when I click "Refresh Pull Request List"*

Or better: like clicking a  `Source Control Provider` in a multi-root workspace updates the `Changes` sub-pane (the one where it's possible to enter a message and commit changes), it could/should update the `GitHub Pull Requests` sub-pane.

**Comment by RMacfarlane** [comment]
Basic support for this was added in version 0.2.0 of the extension. The behavior is what @ronjouch describes:

![folder_select](https://user-images.githubusercontent.com/3672607/45836568-119d5100-bcc2-11e8-83bb-e009dac24c8c.gif)

Note that multiselect isn't supported yet

**Comment by scrossan-crown** [comment]
I work in a wasy

**Comment by RMacfarlane** [comment]
We have recently checked in a change to make the roots of the pull request the repo names in the case of multiple repositories (https://github.com/microsoft/vscode-pull-request-github/commit/b629b113f28050d5f311fae196b4297029eb7c89):
![Screen Shot 2020-08-18 at 10 43 39 AM](https://user-images.githubusercontent.com/3672607/90547045-c6a34700-e13f-11ea-9d5e-d20adfe01c6e.png)
The is more in line with the recent SCM viewlet changes for handling multiple repositories:
![Screen Shot 2020-08-18 at 10 44 50 AM](https://user-images.githubusercontent.com/3672607/90547159-ea668d00-e13f-11ea-9475-67bd1083363f.png)

**Comment by vuon9** [comment]
Hi, although the issue is closed but I'm curious if there is a mode for using GH Pull Requests + VSCode like a pull request review tool without opening a root with multi cloned repos inside, as I have too many repos (50-100 repos)?

I assume it can't because the code should be fetched and be compared to local source and then show the diffs. I would say the extension is so useful for me when doing code review without opening web browsers. It would be really nice if I could use just a single VSCode window as code review tool. I think opening the root folder of multi cloned repos wouldn't be a problem if it can skip tracking the file tree changes as I would do it in another VSCode window.

I wish this question won't bother anybody, and I really appreciate any help in guiding me to the right topic/answer if that's possible.

Thanks a lot!
