### ISSUE TITLE
✨ emoji autocomplete via colon (`:`) prefix like github while reviewing the PR.

### ISSUE THREAD

**Issue by jd-solanki** [microsoft/vscode-pull-request-github#4994]
Hi 👋🏻 

Thanks for this extension. It'll be great to add emoji autocmoplete support when colon is prefixed like github 👀 

GitHub:

https://github.com/microsoft/vscode-pull-request-github/assets/47495003/217390d1-7d96-4fb2-86f6-90bc80912af5

Extension:

https://github.com/microsoft/vscode-pull-request-github/assets/47495003/b1bd76e5-8507-4b32-be6d-ed0c31a75435

**Comment by jd-solanki** [comment]
BTW, feel free to close this if this is out of contex of this extension.

thanks.

**Comment by ian-h-chamberlain** [comment]
For search purposes, this auto-complete mechanism is often called `shortcode`:
https://emojipedia.org/shortcodes/

I didn't find anything when I looked for "shortcodes" or "shortcode" so thought it would be good to mention in the comments here.

**Comment by alexr00** [comment]
Thanks for the pointer @ian-h-chamberlain! I wasn't aware that this was a common pattern. 

Since it's not just used on GitHub, it might make sense for there to be a small extension that adds support for shortcodes. Since most operating systems already offer a different shortcut for adding emojis, I'm going to close this as out of scope.

**Comment by ian-h-chamberlain** [comment]
As it happens, since I left that comment I found out there already is an extension for this!

https://marketplace.visualstudio.com/items?itemName=bierner.emojisense

Linking here in case it's helpful for others who find this issue. It works in review comments since those are just markdown editors.

It might still be nice to autocomplete in the pull request webview when editing descriptions / leaving an overall PR comment, but I can understand if that's out of scope as well.

**Comment by alexr00** [comment]
> It might still be nice to autocomplete in the pull request webview when editing descriptions / leaving an overall PR comment, but I can understand if that's out of scope as well.

This would be very nice, but since it's a webview it's a complex problem to solve. There's another issue somewhere tracking this.
