### ISSUE TITLE
Create PR view: hover colour for branch picker too strong

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#5134]
Hover over the branch picker. Notice the strong hover colour.
Do we use this strong of a hover colour in other parts in the VS Code UI? 
I suggest to use something more subtle and to align with existing hover colours in VS Code core (if we have any).

![Screenshot 2023-07-27 at 14 11 31](https://github.com/microsoft/vscode-pull-request-github/assets/1926584/b7fb5a38-9b49-4797-8995-93bffc8c6bc4)

fyi @alexr00

**Comment by hbons** [comment]
The only colour that comes close is `--vscode-inputOption-hoverBackground`.
It makes the dark theme less contrasty, but the opposite will happen in the light theme:

<img width="329" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/103326/1ea534b1-a61e-4f1d-830f-8210a726aa9d">

<img width="325" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/103326/dfb32a60-3eb7-47b6-984e-68feda8f4b07">

I think it's a slight improvement. Since this is a composed control (somewhere in between a button and an input) everything will be a tradeoff unless we introduce new colors (but then we have to wait for all themes to update).

**Comment by isidorn** [comment]
Yes. I agree this would be an improvement. Would love to try it out :)

**Comment by karthiknadig** [comment]
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/69cf3f9f-68d1-4457-9c23-3904fbb3c253)
