### ISSUE TITLE
"Checkout PR" does not allow contributor editing

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#5147]
1. Have a PR made by some 3rd party who "allow[s] edits from maintainers"
2. From the GH PRs view, use the context menu action to check out a PR
3. Make some edits, commit, and try to push 
4. 🐛 you get access denied since it tries to make a new branch called `pr/<username>/<pr number>` on the contributor's remote repo
5. Manually run `git checkout -b <actual branch name> && git push <username> <actual branch name>` to fix it

**Comment by alexr00** [comment]
>  try to push

How are you trying to push? I make changes like this all the time and push using the command line.

**Comment by alexr00** [comment]
Interesting. It seems that somehow the push remote has already been set. When I do the exact same flow, I get a prompt to choose the remote to push to: 

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/ed48f8ab-7526-406b-ba35-fa4f006fa764)

Either way, I can probably fix this so that either the error or the extra step doesn't occur.

**Comment by connor4312** [comment]
In my gitconfig I have

```
[push]
    default = current
```

to avoid having to `git push -u ...` on new branches. Maybe that's the culprit?

**Comment by alexr00** [comment]
That probably is the culprit.

I don't actually see a way to fix this with git without changing the git config for the repo, which I don't think is the right thing to do.

**Comment by connor4312** [comment]
Could the branch automatically be set to track the submitter's origin and branch as part of the "Checkout PR flow"?

**Comment by alexr00** [comment]
That's what I wanted to do, but I'm having trouble finding a way to accomplish this with git.
