### ISSUE TITLE
Standardise naming branches when using start working on button

### ISSUE THREAD

**Issue by gannaramu** [microsoft/vscode-pull-request-github#5223]
Github Web allows you to create branches from the issues page and usually has the issue title as the branch name on the other hand when using this vscode extension it names it a user/issue72. 
![image](https://github.com/microsoft/vscode-pull-request-github/assets/12237488/856b1888-1ec8-4efe-ab56-1773f43b1822)

I personally feel both the Github Web and the extension should stick to a same naming standard.

**Comment by alexr00** [comment]
We do have a setting for this, and it does support using the issue title: `"githubIssues.issueBranchTitle": "${sanitizedIssueTitle}"`.

**Comment by alexr00** [comment]
I see your point, but I don't want to disrupt current users by changing the default.

**Comment by gannaramu** [comment]
Sweet. was not aware of that setting. that works thanks for the help!

**Comment by arnodunstatter** [comment]
My organization uses issue types, but I can't seem to find the keyword to use - this didn't work

<img width="1120" height="193" alt="Image" src="https://github.com/user-attachments/assets/2c02c4af-5bb7-496e-a1bd-fb24041dba18" />

Alternatively, is there a way to have the branch creation caused by the "Start Working on Issue and Checkout Topic Branch" prompt me for a branch title?
This seems like what I would want, but despite setting it to `prompt` I never actually get prompted for a name.

<img width="944" height="194" alt="Image" src="https://github.com/user-attachments/assets/f70f8828-6694-468d-a9e5-ddcaa71af862" />

**Comment by alexr00** [comment]
Issue type isn't one of the supported variables.

`"githubIssues.useBranchForIssues": "prompt"` is the setting you want. I'm seeing it work as expected and show a quick input for entering a branch name. Make sure you're trying it out on an issue you haven't started working on before. Once you've started working on an issue we remember the branch name and won't ask again.
