### ISSUE TITLE
Create suggestions from working tree changes

### ISSUE THREAD

**Issue by nabeel-halo** [microsoft/vscode-pull-request-github#5256]
Hi, thanks for the extension, we love using it.

Wondering what we think of this as a feature. Currently, making a suggestion on a PR is a multi-step process. You highlight the line numbers you want to suggest, click the left "+" on the bottom of the lines, then make your edits without syntax highlighting or Intellisense support.

It would be cool if instead, we could make changes directly to the working tree (creating unstaged changes), and then have a way to "Add suggestions from working tree diff" (or something similar), where it goes through each of the diffs you've made and allows you to transform it into a suggestion with a comment.

This would particularly be helpful for making suggestions on larger PRs, and for making them much faster (just make the change and import rather than click-click-click-type).

Thanks again for creating a great tool :)

**Comment by alexr00** [comment]
This is a reasonable request, and would really add value over making a suggestion from github.com.

**Comment by diminutivesloop** [comment]
This works in a limited sense already where if you add a suggestion to a line that already has working copy changes it will use the working copy change for the initial suggestion, however when I've done this the resulting diff for the suggestion isn't right. Instead of using the PR change as the "base" for the diff it appears to use the target branch instead which makes the content of the suggestion difficult to distinguish.
