### ISSUE TITLE
Comment locations error messages after deleting PR branch

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#5281]
1. Create a PR
2. Open in VS Code desktop
3. Merge PR and delete branch
4. :bug: GHPRI shows notifications about being unable to get comment locations

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/30305945/1a5c21c3-a747-46fc-8995-74c8fa27b081)

**Comment by alexr00** [comment]
This usually happens with the remote PR branch is ahead of the local PR branch. The comments are associated with a commit that doesn't exist locally and so we can't show them. 

The fix is to prompt the user to pull, or if the remote PR branch has been deleted, then let the user know that the situation is unrecoverable (we will not be able to show the latest comments). Just showing a notification might be too subtle. This might need to be a modal dialog.

**Comment by joyceerhl** [comment]
> if the remote PR branch has been deleted, then let the user know that the situation is unrecoverable (we will not be able to show the latest comments)

I suspect this was the case I was in, and I would actually rather not see any notification at all. Generally if the PR has merged then the comments don't matter as much to me since my work on it is "done", and I find having to action the error notification an added nuisance. If I'm missing some other reason that it is important to show that message, then perhaps a Don't Show Again is appropriate here?

**Comment by alexr00** [comment]
Let's see if I can add a welcome view to the Comments view when the branch is deleted. Then I'll only show the notification or modal if the PR is still open.

**Comment by alexr00** [comment]
I can't show a welcome view in the Comments view as there may still be other comments associated with the PR. I'll just not show the error if the PR is closed.
