### ISSUE TITLE
Comment lines are all joined

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#5289]
Testing microsoft/vscode#194011

Not sure this is by design or a regression, but I entered these comments with a newline before each number and the newlines are not shown after submitting the comment (they are again shown when editing, so they are not lost):

![Image](https://github.com/microsoft/vscode/assets/9205389/b86d73e6-de6d-4e8a-8860-5bf1e7574a27)

**Comment by DonJayamanne** [comment]
Still get the single line comments.
But after a few seconds, the comments appear in separate lines.

Feels very weird, because when I edit the comments and save again, then the new lines are lost untill its updated again a few seconds later.

![Recording 2023-10-25 at 12 14 12](https://github.com/microsoft/vscode-pull-request-github/assets/1948812/e1ff56c6-bb82-46eb-8562-72548dc123dd)

**Comment by alexr00** [comment]
This is by design. GitHub's markdown is different from ours. We can do some processing in the extension to make it look more similar but that requires a delay as we have to make a round trip to the extension to get the content.
