### ISSUE TITLE
Pasting an image into the PR comment results in plain  `image.png` text

### ISSUE THREAD

**Issue by AxTrusov** [microsoft/vscode-pull-request-github#5348]
- Extension version: v0.74.0
- VSCode Version:1.83.1
- OS: Windows 11 Pro, Version 22H2

Steps to Reproduce:

You can use Shift+WindowsKey+S to take a quick screenshot of some specific area and immediately Ctrl+v it into the PR comment to embed an image. In Web GitHub UI this works. In VSCode will just produce an `image.png`  text. 
Expected behavior - ideally - to be able to embed an image. Not ideally - just `image.png` text is misleading.

**Comment by alexr00** [comment]
I am sad to say that GitHub's API doesn't support this and likely never will :( 
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/320

**Comment by vipulgupta2048** [comment]
I built [gitshot](https://github.com/vipulgupta2048/gitshot) to upload screenshots directly to PRs, issues, or comments from the CLI. One command, works everywhere. Hope this helps!

**Comment by drogers0** [comment]
![banner.png](https://github.com/user-attachments/assets/d3ed9430-827a-49d9-9e9d-c2f0bbaa4d5f)

I built [`gh-image`](https://github.com/drogers0/gh-image) as a `gh` CLI extension to solve this. It replicates the browser's own upload flow, so images land at `github.com/user-attachments/assets/…`.
The same URLs you get from drag-and-drop. **Images on private repos stay private**, since the URLs inherit repo visibility.

```bash
gh extension install drogers0/gh-image

IMG=$(gh image banner.png --repo microsoft/vscode-pull-request-github)
# => ![banner](https://github.com/user-attachments/assets/...

gh issue comment 5348 --repo microsoft/vscode-pull-request-github --body "$IMG
I built gh-image as a \`gh\` CLI extension to solve this...."
```
^ That's the command I used to post this.

It automatically pulls your browser's session cookie, no tokens or OAuth setup required.
