### ISSUE TITLE
PR status badge background color

### ISSUE THREAD

**Issue by wyze** [Microsoft/vscode-pull-request-github#535]
More of a question if this is wanted or not. I noticed there is a function in the code to get the color for a given PR status, but it was not used in the codebase, outside of it's definition.

Should we use it to color the background of the status badges on the overview/description view? If desired, I already have the code working and can send a PR. See a preview of Open and Merged below:

![image](https://user-images.githubusercontent.com/186971/46346762-c1ea4e00-c60e-11e8-83c1-e4e979801893.png) ![image](https://user-images.githubusercontent.com/186971/46346780-d0386a00-c60e-11e8-8d50-d1cd036e585d.png)

**Comment by RMacfarlane** [comment]
In a previous iteration of the description view, we did have colors for these. This made them look like buttons even though they are merely status indicators, so we decided to change it. The other issue was with theme compatibility - we're trying to use the theme colors exposed by VSCode instead of hardcoding our own colors that may clash or make things difficult to read on someone's theme

**Comment by wyze** [comment]
Ah okay, thanks for the explanation. Would you consider an option to toggle to opt-in to having them colored? If not that, I would be happy to open a PR removing the dead code. :)

**Comment by RMacfarlane** [comment]
Hmm, my preference would be to remove the dead code. If this gets requested again we could consider add a setting for it, but I'd prefer to add settings for only larger or highly requested UI changes
