### ISSUE TITLE
Test GitHub CLI with extension

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#5384]
Refs: #4464

- [x] anyOS @ulugbekna 
- [x] anyOS @bhavyaus 

Complexity: 3

---

Setup
- Install the pre-release version of GitHub Pull Requests and Issues
- Install the GitHub cli: https://docs.github.com/en/github-cli/github-cli/quickstart

Testing
1. Checkout a PR using the GitHub CLI:
    - `cd` into a cloned repo directory then `gh pr checkout <PR number>`
2. Open your repo directory in VS Code
3. Verify that the extension goes into "review mode" for the PR that you checked out in step 1.

**Comment by bhavyaus** [comment]
The first time I tried this I saw this error after opening the repository directory. 

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/25044782/89dcd49b-03b2-40bd-bfc3-8d1e2067b0c6)

On repro, this issue went away. I believe it was due to stale credentials on my machine but wanted to mention it here anyways.
