### ISSUE TITLE
Failed to save 'index.tsx': The content of the file is newer

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#5943]
Testing #5939

Failed to save 'index.tsx': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes.

![chrome_f0ohKlDYwq](https://github.com/microsoft/vscode-pull-request-github/assets/2931520/93e07426-f1e1-453e-b81c-e298aad19956)

**Comment by alexr00** [comment]
@bpasero maybe you can help with a better solution. What happens:
1. User enters conflict resolution mode. This causes GHPR to register a file system provider for the merge output.
2. When the merge editor opens, it reads the merge output file.
3. When the user exits conflict resolution mode, the file system provider is disposed.
4. User enters conflict resolution mode again. The file system provider for the merge output is re-registered.
5. When the merge editor opens, *it reads the merge output file, but instead of reading it from the files system provider, it reads whatever the text model had from last time*, even though a new file system provider was registered.

What I would like is when the file system provider is disposed, VS Code deletes all text models that used to "belong" to the file system provider. I haven't found a way to do this though. My quick fix is to use a different scheme each time I register the file system provider.

**Comment by bpasero** [comment]
> What I would like is when the file system provider is disposed, VS Code deletes all text models that used to "belong" to the file system provider

I think that is dangerous and could result in data loss. I might have an extension installed that allows to make changes to an editor with a custom FSP and scheme and when I disable that extension, my changes are lost? We are very very restrictive when to dispose a text file model, we actually only allow it unless the changes have been discarded or saved.

**Comment by bpasero** [comment]
Maybe I do not fully understand why the file system provider is created and disposed when this happens. We do have a similar flow in core where we have a custom FSP only for resolving dirty writes (the conflict resolution to this error).

**Comment by alexr00** [comment]
@bpasero what if I fire a `Deleted` file change event from my file system provider before disposing? Is there any way a file system provider can tell VS Code that next time a file for that provider is opened it should go to the file system provider for the data?

**Comment by alexr00** [comment]
I only need the file system provider to be registered when in conflict resolution mode, that's why I create and dispose it when entering and leaving conflict resolution mode.

**Comment by bpasero** [comment]
> When the merge editor opens, it reads the merge output file, but instead of reading it from the files system provider, it reads whatever the text model had from last time, even though a new file system provider was registered.

There may be a bug here that we can fix, but to clarify: if an editor is dirty (has changes), we never go to the file system to resolve it but always resolve it from the editor model because the file will not have the changes and the content is in memory anyway.

In order to prevent going to the file system if there are no changes, we actually have a logic in place to figure out if the file has changed on disk compared to the version we have in memory (this requires the text model to be still around and not disposed). This depends on `mtime` and `size` information from the `stat` method:

https://github.com/microsoft/vscode/blob/0ed0a9fe1395f8263ba31f7a20cf8987666ac21d/src/vs/platform/files/common/fileService.ts#L701-L704

Maybe thats whats happening here? Are you implementing `mtime` and `size` properly in your FSP?

See also the docs around this:

https://github.com/microsoft/vscode/blob/0ed0a9fe1395f8263ba31f7a20cf8987666ac21d/src/vscode-dts/vscode.d.ts#L8732-L8747

**Comment by bpasero** [comment]
Yeah thats true, another optimisation is that opening a model that is in-memory (e.g. still opened as tab) does not wait for the file service call but would show as it is in-memory and then try to see if newer content is there.

**Comment by alexr00** [comment]
This optimization makes sense, but I think as an extension I expect that if the tab is closed and I have disposed my filesystem provider then the in-memory model would not be used. 

I've worked around this by having my file system provider register with a different scheme each time.

**Comment by bpasero** [comment]
@alexr00 yeah so another thing that likely hits you is that text models are kept in-memory even after closing the tab for I think 3 minutes. @jrieken would be able to tell more, I think we do this because there is no explicit lifecycle in extension API to dispose a text model that has been opened (but I maybe wrong).

**Comment by andreamah** [comment]
@alexr00 @bpasero are there verification steps for this?
@hediet is this still happening for you?

**Comment by andreamah** [comment]
hmm, I get an error
![image](https://github.com/microsoft/vscode-pull-request-github/assets/31675041/cd166538-e577-4d50-b6f8-e6fe341412d0)

I tried with this repo https://github.com/andreamah/test-repo and this branch https://github.com/andreamah/test-repo/pull/1

**Comment by alexr00** [comment]
Good find @andreamah!
