### ISSUE TITLE
Override Default Branch no longer working

### ISSUE THREAD

**Issue by eladiosch** [microsoft/vscode-pull-request-github#5995]
- Extension version: v0.88.0
- VSCode Version: 1.89.0
- OS: Ubuntu 22.04.4 LTS (64-bit)
- Repository Clone Configuration: cloned private repository (not a fork)
- Github Product : Github.com

Steps to Reproduce:

1. In VsCode go to Preferences and search `githubPullRequests.overrideDefaultBranch`
2. Set value to "develop"
3. Try to create a new PR
4. Base branch is now "main" (default in repo config) instead of "develop"

This used to work fine but stopped working maybe a couple of weeks ago. I've talked with other people working on the same repo with the same extension and are experiencing the same behaviour.

![image](https://github.com/microsoft/vscode-pull-request-github/assets/3090613/7148119a-2bf2-4f85-9fb3-8b1e25cea122)

![image](https://github.com/microsoft/vscode-pull-request-github/assets/3090613/7e70dceb-dc0a-4b30-a811-878589609923)

**Comment by alexr00** [comment]
What is the value of the setting `githubPullRequests.createDefaultBaseBranch`? We try to guess the "best" base branch by default.

**Comment by eladiosch** [comment]
It's `auto`. However, shouldn't the `githubPullRequests.overrideDefaultBranch` value have the highest priority when deciding the branch?

**Comment by eladiosch** [comment]
Any news on this issue?

**Comment by alexr00** [comment]
Sorry for the slow response, I lost your reply in May!

`githubPullRequests.overrideDefaultBranch` overrides the default branch for you repo (ex., you can use it to have the extension consider `release` your default branch instead of `main`).

`githubPullRequests.createDefaultBaseBranch` just controls what is in the base branch drop down when you open the "Create" view. The default setting value`auto` , means that we guess the base branch based off of what your current branch was branched off from (assuming you're not on a fork, for a fork, this will work differently). If you don't want that behavior and you always want it to be the value of `githubPullRequests.overrideDefaultBranch` then you should set `githubPullRequests.createDefaultBaseBranch` to `repositoryDefault`.
