### ISSUE TITLE
Command to close all 'pull request related' editors

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode-pull-request-github#6234]
Hello, and thanks for this extension, I use it extensively to review PRs.
However, a problem I'm facing is that the editors that open when I visit each file are kept open. A lot of times, this editors interfere with my normal work, as many times I jump to the read-only file rather than opening the real file in my filesystem.
I can manually close all the editors, but I will be very grateful if there be a command that takes care of this in a single go for me. Just what you can do with diff editors (you can close them all with a single command)

Thanks

**Comment by danielo515** [comment]
Is this being considered then?

**Comment by danielo515** [comment]
Thank!

**Comment by alexr00** [comment]
To verify:
- Make sure you have the latest pre-release version of the extension installed
- Open some PR diffs from non checked out PRs. Make sure they aren't in preview mode so that they stick around
- Check out a PR. Open some diffs from the checked out PR.
- Open an original file from the checked out PR.
- Run the command "Close all Pull Request Editors"
- Verify that all your PR related editors have closed.
