### ISSUE TITLE
Inconsistency between buttons in PR comments

### ISSUE THREAD

**Issue by Henri-ColibrITD** [microsoft/vscode-pull-request-github#6518]
Type: <b>Bug</b>

When posting a comment on a specific line of code, between the buttons on github.com and the extention, there is ordering and highlighting differences that make the process extremely confusing when jumping between the two.
For each of these, the buttons are ordered as:

- github.com: `cancel`, `add single comment`, `start a review`
- VS code github PR extention: `make a suggestion`, `start a review`, `add comment`

And in both cases the last button is in the highlight color.

I think I understand why the first button is different (something about UI guidelines I guess), but the 2nd and 3rd feel like they are plainly trying to make me do the wrong action.

Extension version: 0.100.3
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by Henri-ColibrITD** [comment]
So you have in mind exactly what I mean, here are screenshots of the corresponding bits of UI:

- github.com: ![Image](https://github.com/user-attachments/assets/095dff2b-d437-4ca8-87f3-4b97ef24b74c)
- VS code github PR extention: ![Image](https://github.com/user-attachments/assets/32be1cdd-1a3f-4733-b97c-c229a355fc87)

**Comment by alexr00** [comment]
We have a setting for this `githubPullRequests.defaultCommentType`. 

I'm always a bit hesitant to change the defaults as it can break muscle memory, especially since it can be tough for user to figure out that they need to submit a review for their comments to become visible. I'm going to leave the default as is since you can change the default with the setting.
