### ISSUE TITLE
"Checkout Pull Request" doesn't check out the right branch

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode-pull-request-github#674]
Steps to reproduce:

1. Be on `master`
2. In the sidebar, find a PR you want to check out locally (say, it's `feature-branch-1`) and invoke "Checkout Pull Request" from context menu.

I'd expect a new local branch created, `feature-branch-1` pointing at the same commit as `origin/feature-branch-1` but that's not the case; the extension creates a new local branch, `feature-brach-1`, pointing at the same commit as `master`. So there are immediately many commits to pull and push, like this:

![image](https://user-images.githubusercontent.com/101152/48195324-9cf4a380-e34f-11e8-887a-22e013fbc404.png)

I'm not sure if I'm doing something wrong or am misunderstanding what "Checkout Pull Request" should do but this feels "wrong".

**Comment by RMacfarlane** [comment]
@borekb This sounds like a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/594. This extension uses the builtin VSCode git extension to run git commands, the issue was there. It's fixed in VSCode version 1.29, which is currently still the insiders version but will be released soon

**Comment by borekb** [comment]
Thanks, @RMacfarlane! I actually saw #594 but was not sure if it's the same thing.
