### ISSUE TITLE
Make it super easy to add a remote

### ISSUE THREAD

**Issue by jongio** [Microsoft/vscode-pull-request-github#716]
Related to #381 

I think it would be great to make is super easy for a user to add a remote.

I'm usually working from my fork locally, so to see any pull request, I need to add a remote with `git remote add upstream ....`

Consider adding this to the VS Code git extension `....` menu
![image](https://user-images.githubusercontent.com/2163001/49467314-0765fb80-f7b7-11e8-9500-49dcff162e0d.png)

Something like "Add Remote", which prompts for name (defaults to upstream) and URI, which is automatically pulled from the GitHub API.

**Comment by RMacfarlane** [comment]
Actually, thinking about this more, I think this feature makes sense as a core part of VSCode and not something from the extension, since anyone using Git could benefit.

There's already [this](https://github.com/Microsoft/vscode/issues/21189) issue tracking it in the VSCode repo, so I'll close this

**Comment by jongio** [comment]
Makes sense.  Thanks for having a look.
