### ISSUE TITLE
[feature request] Allow setting preferences for the remote when creating PR

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-pull-request-github#829]
When working off a fork and creating a pull request, it appears the default list for both the selection for the remote to submit the PR to and the selection to push the local branch to uses alphabetical sort for the defaults.
It would be nice to be able to configure through the settings, or change the default behaviour so that I can select the `upstream` as the default remote for creating the PR, and the `origin` as the default remote for pushing the branch.

Using the `upstream` for the target (if it exists as a remote), and `origin` for the branch might also make sense as defaults given the common Git naming conventions for remotes.

Thanks for considering this!

**Comment by cegekaJG** [comment]
I'd like to +1 this feature request. Our fork of a public repository is for internal use only, so I don't want to push something upstream, ever. Still, since this is the only forked repo I work with, I keep accidentally selecting `upstream/main` as the target branch, which just clutters up the PRs of the public repo with personal edits.

**Comment by alexr00** [comment]
We have `githubPullRequests.createDefaultBaseBranch`, which I think will solve your case!
