### ISSUE TITLE
There is no category for "Mentioned Me"

### ISSUE THREAD

**Issue by mayrock** [microsoft/vscode-pull-request-github#881]
Our organization usually uses at-mention in PR description to tag someone for review, instead of explicitly assign someone as reviewer. Such PR will not show up in the VSCode Pull Request list.

It would be great to add a `Mentioned Me` category to the tree to solve this.

**Comment by mayrock** [comment]
I submitted a PR to address this: https://github.com/Microsoft/vscode-pull-request-github/pull/882

**Comment by mayrock** [comment]
Can I get some attention to the issue & PR? It is a simple enough change and should be helpful for a lot of people.

**Comment by meaghanlewis** [comment]
@mayrock apologies for not responding to this sooner. Thanks for adding in this category! It seems like it can be helpful for users to know which PRs they need to address. 

One thing we have a concern about is that this list will continue to build up because PRs will only get added to the list and not removed. This means that over time the list of PRs here will become unmanageable. Do you have any thoughts about how to address this?

**Comment by mayrock** [comment]
@meaghanlewis thanks for the comment! 
I have been using a private build with this change for some time, and it behaves similarly as other categories: only active PRs show here. So I don't think it will be unmanagement, unless people keep tagging you in new PRs and do not close them. And even if that happens, the same problem apply to other categories like `Assigned To Me`.

So I don't think this will be a problem, unless I missed something ...

**Comment by meaghanlewis** [comment]
@mayrock thanks, you answered the questions I had. It's good to know that you have been using this yourself for some time and that this will only show open PRs. 

Let me go ahead and add a few reviewers to your PR. cc/ @RMacfarlane @StanleyGoldman @queerviolet

**Comment by RMacfarlane** [comment]
@mayrock I'm wondering if there is a more generic solution to this. We have several other issues in this repository asking for categories with different queries. I asked my own team what categories they use with the extension, and most people are using only a couple of them, but not the same ones. So I think instead of adding more categories, we should make it possible to configure the categories that are shown, like the idea here: https://github.com/microsoft/vscode-pull-request-github/issues/1106

**Comment by RMacfarlane** [comment]
Hey @mayrock, I merged the more generic solution described in #1106. Now you can change the `githubPullRequests.queries` setting to include whatever categories you want. There’s an example in the readme here: https://github.com/microsoft/vscode-pull-request-github#configuring-the-extension
