### ISSUE TITLE
Crazy long tab title

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#952]
Thank you for the fix for #288, this is now really making me move faster when reviewing PRs.

However, there is a small nit-pick. The title of the tabs created by your extension is insanely huge:

![image](https://user-images.githubusercontent.com/5047891/52782297-01aa5300-304f-11e9-8002-605597e637f5.png)

This makes it annoying to open them, as they eat up all of my tab space. Maybe the open command that you are calling is accepting an argument to define a custom title and maybe you can check what vanilla `git` is doing to do something similar.

Thanks!

**Comment by alexandrudima** [comment]
I've also noticed something else which is weird about this tab. I think you are constructing the URI for the right hand side editor in a funny way because when I click to jump to file the same file is opened (presumably because the URIs are not equal). Perhaps you can ask @joaomoreno or @bpasero how to create a `file` URI such that they are equal and we don't end up opening the file twice:
 
![kapture 2019-02-14 at 12 29 47](https://user-images.githubusercontent.com/5047891/52784122-58fef200-3054-11e9-8fde-5a628a1c3092.gif)
