### ISSUE TITLE
Repo is null error when the remote url has username in it

### ISSUE THREAD

**Issue by arjun27** [Microsoft/vscode-pull-request-github#97]
The extension is not able to fetch pull requests when the `origin` remote url has the following format, with the error "repo is null".

```
https://username@github.com/username/reponame.git
```

Changing the url to remove the `username@` fixes the issue. Ideally the username/password modifier should be handled in the url parser.

**Comment by rebornix** [comment]
@shana would we use the username/password or token in scp like remote url for authentication ?

**Comment by shana** [comment]
If there's only a username in the url, then we should probably ignore it, as there's no authentication happening at that level. What the username@ portion is doing in the url is hinting to the git credential manager that it should look up a username@github.com entry in the system if there is one. If there isn't, it might fall back to looking for an entry with only the host portion (or fail, it's really iffy). Since we only deal with host+token pairs, the username isn't much help as a key (we have no idea what the username is for a token unless we ping the api for it).

If there's a username+password in the url, then that might be useful. That is, assuming that the password is a token, and that the token has the correct scopes that the PR feature needs (so basically it's the same scenario has the codepath that looks up the token in git and checks whether the token is usable).

**Comment by rebornix** [comment]
@shana thanks for the detailed information. To unblock users from using this extension in this case, I'll ignore the username/token for now. We can use this issue to continue investigating how we can use the user/token info for authentication.

**Comment by RMacfarlane** [comment]
This has been fixed by https://github.com/Microsoft/vscode-pull-request-github/commit/ff9cfa16688f467c3f166d8c963b44b469a21c0f
